#+TITLE: History 001

#+BEGIN_EXPORT html
<div class="engt">History</div>
<div class="japt">病歴聴取</div>
<div class="engt">Page 001</div>
#+END_EXPORT

[[https://github.com/ahisu6/ahisu6.github.io/edit/main/src/h/001.org][Edit]]

[[file:./index.org][Home]]

[[file:./002.org][Next page >>]]

-----

#+TOC: headlines 2

* Advance Directive
:PROPERTIES:
:CUSTOM_ID: org4b25905
:END:

Posted: 2023-06-19 | Updated: 2023-06-19

Advance directive is used when the patient no long has capacity to make decision. So, for example, if the patient loses consciousness, then the medical team can use the advance directive to see what treatment the patient refuses. @@html:<span class="ja">「事前指示書 / advance directives」は、患者さんに意思決定能力がなくなったときに使用されます。例えば、患者さんが意識を失った場合、医療チームは「事前指示書 / advance directives」を使って、患者さんが拒否する治療を確認することができるわけです。</span>@@

So basically, an advance directive is a document which tells us what future treatment that the patient does NOT wants. @@html:<span class="ja">つまり、基本的に「事前指示書 / advance directives」とは、患者さんが望まない将来の治療法を記した文書です。</span>@@

For example, some patients might say that they do not want these things in the future @@html:<span class="ja">例えば、患者さんの中には、「今後はこんなものはいらない」とおっしゃる方もいらっしゃるかもしれませんが</span>@@:
- I do NOT want antibiotics.
- I do NOT want CPR.
- I do NOT want ventilation.
- I do NOT want NG tube.
- I do NOT want catheter.
- I do NOT want pain killers.
- I do NOT want blood transfusion.

As you can see, this is related to the stuff that the patient refuses. @@html:<span class="ja">お分かりのように、これは患者が拒否するものに関係しています。</span>@@

The patient cannot request treatment. So, the patient cannot say "Give me antibiotics"! This is very important to remember!!! @@html:<span class="ja">患者は治療を要求できない。ですから、患者は「抗生物質をくれ」と言うことができません！これはとても重要なことなので、覚えておいてください！！！</span>@@

If the patient has capacity, then the advance directive can be changed at any time the patient wants! @@html:<span class="ja">患者さんに能力があれば、「事前指示書 / advance directives」は、患者さんが望む時にいつでも変更することができます！</span>@@

But, if the patient does NOT have capacity, then we cannot change it! @@html:<span class="ja">しかし、もし患者さんに能力がないのであれば、それを変えることはできません！</span>@@

Advance directive can be split into 3 main types @@html:<span class="ja">「事前指示書 / advance directives」は、大きく3つのタイプに分けられます</span>@@:
1. Advance Decision to Refuse Treatment: this is a legal document which lists the things which the patient refuses in the future. This is for medical treatment ONLY. @@html:<span class="ja">これは、患者が将来的に拒否するものを列挙した法的文書です。これは医療行為に限ったものです。</span>@@
2. Lasting Power of Attorney: this is a person which can make decisions for the patient. This person can be anyone (brother, sister, friend, wife, husband, uncle, etc.). There are different types: some types can manage healthcare only, and some types can manage money only. @@html:<span class="ja">永続的な委任状 / 最後の委任状：これは、患者さんのために意思決定を行うことができる人です。この人は誰でもいい（兄弟、姉妹、友人、妻、夫、叔父など）。医療だけを管理できるタイプや、お金だけを管理できるタイプなど、さまざまなタイプがあります。</span>@@
3. Advance statement: this is just a small letter which the patient writes. It talks about other things (religion, wishes, beliefs, moral values, etc.). This is NOT a legal document. @@html:<span class="ja">これは、患者さんが書く小さな手紙です。他のこと（宗教、希望、信念、道徳観など）についても書かれています。これは法的な文書ではありません。</span>@@

The patient cannot be forced to make advance directives. If you think that the patient is being forced, then the advance directive will be ignored. @@html:<span class="ja">患者は「事前指示書 / advance directives」を作ることを強制されることはありません。もし、患者が強制されていると考えるなら、「事前指示書 / advance directives」は無視されるでしょう。</span>@@

Say these things in order:
1. Good morning, my name is Dr. XYZ. Can I get your name and date of birth please? @@html:<span class="ja">おはようございます、私はドクターXYZと申します。あなたのお名前と生年月日をお聞かせください。</span>@@
2. Thank you for coming today. @@html:<span class="ja">本日はご来場いただきありがとうございました。</span>@@
3. So, before we begin, I would like to ask you a question if you do not mind. @@html:<span class="ja">では、その前に、差し支えなければ質問させてください。</span>@@
4. Could you tell me what you know so far? @@html:<span class="ja">これまでに分かっていることを教えていただけますか？</span>@@
5. /Give the patient some time to explain./ @@html:<span class="ja"><i>患者さんに説明する時間を与えてください。</i></span>@@
6. Thank you for sharing this with me. Now, you may have thought about this already, but since your condition is at a critical stage, one topic that is crucial for us to discuss is your future treatment if you become unable to make a decision. This is called "advance directives". @@html:<span class="ja">この度は、ご報告ありがとうございます。さて、すでにお考えになられているかもしれませんが、あなたの病状は重要な段階にあるため、決定できない状態になった場合の今後の治療について話し合うことが重要なテーマの一つです。これは「事前指示書 / advance directives」と呼ばれるものです。</span>@@
7. Do you know what that means? @@html:<span class="ja">その意味がわかりますか？</span>@@
8. /Give the patient some time to explain./ @@html:<span class="ja"><i>患者さんに説明する時間を与えてください。</i></span>@@
9. Before I contiue, would you like anyone else to be present with you? @@html:<span class="ja">続ける前に、他にどなたか同席してほしい方はいらっしゃいますか？</span>@@
10. Advance directives are only used if you lose capacity. So, for example, if you go into a coma, we will use the advance directives to help us give you the best treatment. @@html:<span class="ja">「事前指示書 / advance directives」は、あなたが能力を失った場合にのみ使用されます。ですから、例えば、あなたが昏睡状態に陥った場合、私たちは「事前指示書 / advance directives」を用いて、あなたに最善の治療を施すことができるようにします。</span>@@
11. There are different types of advance directives. The first one is called "Advance Decision to Refuse Treatment". This is a legal document that talks about which treatment you refuse in the future. @@html:<span class="ja">「事前指示書 / advance directives」には、さまざまな種類があります。まず、「治療拒否の事前決定 / Advance Decision to Refuse Treatment」と呼ばれるものがあります。これは、将来どの治療を拒否するかということを語る法的文書です。</span>@@
12. You can discuss this with your family and friends, and then you can make a decision about what treatment you do not want in the future. @@html:<span class="ja">ご家族やご友人と相談しながら、今後どのような治療を望まないか、決めていくことができます。</span>@@
13. /Give the patient few seconds of silence./ @@html:<span class="ja"><i>患者に数秒の沈黙を与える。</i></span>@@
14. Do you have any questions so far? @@html:<span class="ja">ここまでで何か質問はありますか？</span>@@
15. The other type is called "Lasting Power of Attorney". This is a person which you can choose. This person can manage various aspect of your health and finances. @@html:<span class="ja">もう一つは、「Lasting Power of Attorney / 永続的な委任状 / 最後の委任状」と呼ばれるタイプです。これは、あなたが選ぶことができる人です。この人は、あなたの健康や経済に関するさまざまな面を管理することができます。</span>@@
16. /Give the patient few seconds of silence./ @@html:<span class="ja"><i>患者に数秒の沈黙を与える。</i></span>@@
17. Do you have any questions so far? @@html:<span class="ja">ここまでで何か質問はありますか？</span>@@
18. You can discuss this topic with your family and friends, and you can get legal advice about it. Here is an information leaflet to explain where you can get legal advice. @@html:<span class="ja">この話題については、家族や友人と話し合うこともできますし、法的なアドバイスを受けることもできます。ここでは、どこで法的アドバイスを受けることができるかを説明するための情報リーフレットを紹介します。</span>@@
19. If you still have capacity to make decisions, then you can change the advance directive whenever you want. As long as you have capacity, it is okay. @@html:<span class="ja">まだ意思決定能力があるのであれば、いつでも「事前指示書 / advance directives」を変更することができます。能力がある限り、大丈夫です。</span>@@
20. /Give the patient few seconds of silence./ @@html:<span class="ja"><i>患者に数秒の沈黙を与える。</i></span>@@
21. Is that clear so far? Do you have any questions for me? Could you repeat back to me what I have said just to make sure that I explained it clearly for you?  @@html:<span class="ja">ここまででクリアでしょうか？何か質問はありますか？私が言ったことをもう一度言ってもらえますか？あなたのために明確に説明したことを確認するために。</span>@@
22. /Give the patient some time to explain./ @@html:<span class="ja"><i>患者さんに説明する時間を与えてください。</i></span>@@
23. There is a third type of advance directives. This is called "advance statement". This is basically a statement that talks about your beliefs and values. This is useful for use to take your wishes into consideration. @@html:<span class="ja">「事前指示書 / advance directives」には3つ目のタイプがあります。これは「事前の説明 \ advance statement」と呼ばれるものです。これは基本的に、あなたの信念や価値観について語る声明です。これは、あなたの希望を考慮するために使用するのに便利です。</span>@@
24. Do you have any questions for me? @@html:<span class="ja">何か質問はありますか？</span>@@
25. /Give the patient some time to explain./ @@html:<span class="ja"><i>患者さんに説明する時間を与えてください。</i></span>@@
26. That is all I have for you. I will just give you a quick summary of what we discussed today. @@html:<span class="ja">以上、ご報告させていただきます。今日お話ししたことを簡単にまとめておきますね。</span>@@
27. /Do a quick summary./ @@html:<span class="ja"><i>簡単なまとめをしてください。</i></span>@@
28. Would you like me to inform anyone else about this? @@html:<span class="ja">このことを他の人に知らせた方がいいでしょうか？</span>@@
29. Please, do not hesitate to talk to us if you need anything. Thank you once again for talking to me. @@html:<span class="ja">どうぞ、何かありましたら遠慮なくお話しください。改めてお声がけいただきありがとうございました。</span>@@

* Do Not Attempt Resuscitation (DNAR)
:PROPERTIES:
:CUSTOM_ID: orgc29f40c
:END:

This is the same as Do Not Attempt Cardiopulmonary Resuscitation (DNACPR).

When someone becomes very ill, the heart might stop working. If the heart stops working, then we would need to do CPR. @@html:<span class="ja">誰かが重病になると、心臓が止まることがあります。もし心臓が止まってしまったら、心肺蘇生をしなければならないでしょう。</span>@@

Sometimes, doctors will think that CPR might cause more harm to the patient, and it might make the patient disabled. @@html:<span class="ja">時には、医師が心肺蘇生をすることで患者さんにもっと害が及ぶかもしれない、患者さんに障害が残るかもしれないと考えることもあるでしょう。</span>@@

This is a medical decision. That means that the patient cannot reject the decision. @@html:<span class="ja">これは医学的な決定である。つまり、患者さんはその決定を拒否することはできません。</span>@@

An important thing to note is that DNACPR only applies when the patient's heart stops beating. So, if the patient's is fine, then we continue to give the best treatment. @@html:<span class="ja">重要なのは、DNACPRが適用されるのは、患者さんの心臓が停止したときだけだということです。ですから、患者さんの心臓が元気であれば、私たちは最善の治療を続けます。</span>@@

Say these things in order:
1. Good morning, my name is Dr. XYZ. Can I get your name and date of birth please? @@html:<span class="ja">おはようございます、私はドクターXYZと申します。あなたのお名前と生年月日をお聞かせください。</span>@@
2. Thank you for coming today. @@html:<span class="ja">本日はご来場いただきありがとうございました。</span>@@
3. So, before we begin, I would like to ask you a question if you do not mind. @@html:<span class="ja">では、その前に、差し支えなければ質問させてください。</span>@@
4. Could you tell me what you know so far? @@html:<span class="ja">これまでに分かっていることを教えていただけますか？</span>@@
5. /Give the patient some time to explain./ @@html:<span class="ja"><i>患者さんに説明する時間を与えてください。</i></span>@@
6. Thank you for sharing this with me. Now, you may have thought about this already, but since your condition is at a critical stage, one topic that is crucial for us to discuss is resuscitation. @@html:<span class="ja">このようなことを教えていただき、ありがとうございます。さて、すでにお考えかもしれませんが、あなたの状態は危機的な段階にあるため、私たちにとって極めて重要な話題のひとつが「蘇生」です。</span>@@
7. Do you know what that means? @@html:<span class="ja">その意味がわかりますか？</span>@@
8. /Give the patient some time to explain./ @@html:<span class="ja"><i>患者さんに説明する時間を与えてください。</i></span>@@
9. As your sickness worsens, you can experience a cardiac arrest, which is when your heart stops beating. @@html:<span class="ja">病気が悪化すると、心臓が止まる「心停止」を起こすこともあります。</span>@@
10. Sometimes, when the heart stops beating, we do something called Cardiopulmonary Resuscitation, or CPR. @@html:<span class="ja">心臓が止まったときに、心肺蘇生法（CPR）ということをすることもあります。</span>@@
11. CPR is when we try to make the patient's heart start beating again. We do something called "chest compressions". The chest compressions will try to make the heart pump blood around the body. @@html:<span class="ja">CPRとは、患者さんの心臓を再び鼓動させようとすることです。私たちは「胸骨圧迫」と呼ばれるものを行います。胸骨圧迫は、心臓が体中に血液を送り出すようにするものです。</span>@@
12. /Give the patient few seconds of silence./ @@html:<span class="ja"><i>患者に数秒の沈黙を与える。</i></span>@@
13. Is that clear so far? Do you have any questions for me? Could you repeat back to me what I have said just to make sure that I explained it clearly for you?  @@html:<span class="ja">ここまででクリアでしょうか？何か質問はありますか？私が言ったことをもう一度言ってもらえますか？あなたのために明確に説明したことを確認するために。</span>@@
14. /Give the patient some time to explain./ @@html:<span class="ja"><i>患者さんに説明する時間を与えてください。</i></span>@@
15. CPR is a very aggressive thing to do. During CPR, sometimes the ribs of the patient might break. Sometimes brain damage can happen because there was not enough blood. This can make the patient become disabled. @@html:<span class="ja">心肺蘇生は、とてもアグレッシブな行為です。CPR中に、時には患者の肋骨が折れるかもしれません。血液が足りなかったために、脳が損傷することもあります。その結果、患者さんに障害が残ることもあります。</span>@@
16. So, as a medical team, we believe that CPR in this case will not be successful. Even if CPR is successful, it might cause a lot of harm to the you. @@html:<span class="ja">ですから、医療チームとしては、このケースでの心肺蘇生は成功しないと考えています。仮に心肺蘇生が成功したとしても、あなたに多くの害を与えるかもしれません。</span>@@
17. We are doing this in the best interest of the patient. @@html:<span class="ja">私たちは、患者さんの最善の利益のためにやっているのです。</span>@@
18. /Give the patient few seconds of silence./ @@html:<span class="ja"><i>患者に数秒の沈黙を与える。</i></span>@@ 
19. This is a medical decision. So, I am telling you about this just to keep everything transparent, and to keep you informed. @@html:<span class="ja">これは医学的な判断です。だから、すべてを透明にして、情報を提供し続けるために、このことをお話ししているのです。</span>@@
20. One important thing to say is that DNACPR only applies when your heart stops beating. So, we will continue to give you all the best treatment that you need. So, we will keep giving you antibiotics and other medications. @@html:<span class="ja">ひとつ重要なことは、DNACPRは心臓が停止したときにのみ適用されるということです。ですから、私たちは、あなたが必要とするすべての最善の治療を与え続けます。ですから、抗生物質やその他の薬も与え続けます。</span>@@
21. Do you have any questions for me? @@html:<span class="ja">何か質問はありますか？</span>@@
22. /Give the patient some time to explain./ @@html:<span class="ja"><i>患者さんに説明する時間を与えてください。</i></span>@@
24. That is all I have for you. I will just give you a quick summary of what we discussed today. @@html:<span class="ja">以上、ご報告させていただきます。今日お話ししたことを簡単にまとめておきますね。</span>@@
25. /Do a quick summary./ @@html:<span class="ja"><i>簡単なまとめをしてください。</i></span>@@
26. Would you like me to inform anyone else about this? @@html:<span class="ja">このことを他の人に知らせた方がいいでしょうか？</span>@@
27. I understand that this may be upsetting. Please, do not hesitate to talk to us if you need anything. Thank you once again for talking to me. @@html:<span class="ja">ご不快な思いをされることもあるかと思います。どうぞ、何かありましたら、遠慮なくお話しください。改めて、お話してくださってありがとうございました。</span>@@

The patient might say "I want CPR." or they might say "No, I disagree with you." If they say that, then you should reply with this sentence @@html:<span class="ja">患者さんは「I want CPR」 と言うかもしれませんし、「No, I disagree with you」と言うかもしれません。もしそう言われたら、この文章で返すといいでしょう</span>@@:
- DNACPR is a medical decision, and it is not possible to refuse it or appeal against it. But, if you would like, I can arrange a meeting with the consultant to discuss this further. @@html:<span class="ja">DNACPRは医学的な決定であり、それを拒否したり、不服申し立てをしたりすることはできません。しかし、もしご希望であれば、コンサルタントとの面談をアレンジして、さらに詳しくお話することも可能です。</span>@@

* Chest symptoms
:PROPERTIES:
:CUSTOM_ID: orgbf282eb
:END:

Posted: 2023-05-12 | Updated: 2023-05-12

In the chest we have the heart and the lung. This is basic anatomy. @@html:<span class="ja">胸には、心臓と肺がある。これが基本的な解剖学です。</span>@@

The heart can cause pain (for example, if the patient has heart attack). The lung can also cause pain (for example, if the patient has pneumothorax). @@html:<span class="ja">心臓は痛みを引き起こすことがあります（例えば、患者さんが心臓発作を起こした場合）。肺も痛みを引き起こすことがあります（例えば、患者さんが気胸になった場合）。</span>@@

The heart can cause shortness of breath (for example, if the patient has heart failure which causes fluid to go to the lungs). The lung can also cause shortness of breath (for example, if the patient has asthma). @@html:<span class="ja">心臓は息切れの原因になることがあります（例えば、肺に水分が行くような心不全の場合など）。肺も息切れを起こすことがあります（例えば、患者さんが喘息持ちの場合など）。</span>@@

The heart can cause cough (for example, if the patient has heart failure which causes fluid to go to the lungs, and that makes the patient cough). The lung can also cause cough (for example, if the patient has lung infection). @@html:<span class="ja">心臓が原因で咳が出ることがあります（例えば、心不全で肺に水が溜まり、それが原因で咳が出る場合など）。肺も咳を引き起こすことがあります（例えば、患者さんが肺に感染している場合など）。</span>@@

So, it's important that we come up with a way to help find the cause! @@html:<span class="ja">だから、原因究明のための方法を考えることが重要なんです！</span>@@

- If a patient comes with pain, then just do the normal SOCRATES. @@html:<span class="ja">痛みを伴う患者さんが来たら、普通にSOCRATESをやればいいんです。</span>@@
- If a patient comes with anything else, then do the @@html:<mark>DOP</mark>@@. Click [[#org8c96f99][here]] to learn more about the DOP. @@html:<span class="ja">それ以外の症状で来院された場合は、DOPを行います。DOPについて詳しく知りたい方は、リンクをクリックしてください。</span>@@

Now then, let's move on the fun part. @@html:<span class="ja">さて、それではお楽しみに移らせていただきます。</span>@@

Now, you need to ask the patient more specific questions. If the patient answers "yes", to any of these questions, you must do @@html:<mark>DOP</mark> for that symptom. This is what you need to ask <span class="ja">次に、患者さんにもっと具体的な質問をする必要があります。これらの質問のいずれかに患者さんが「はい」と答えた場合、その特定の症状を分析するためにDOPを実施する必要があります。以下は、質問すべき内容である</span>@@:
1. Do you have any wheeze or shortness of breath? @@html:<span class="ja">喘ぎ声や息切れはないか？</span>@@
2. Do you have any cough? @@html:<span class="ja">咳はないか？</span>@@
3. Do you have any chest pain? If yes, then do SOCRATES. @@html:<span class="ja">胸の痛みは？ある場合は、SOCRATESを行う。</span>@@
4. Do you have any palpitations? @@html:<span class="ja">ドキドキしたことはありますか？</span>@@
5. Do you have any fever? @@html:<span class="ja">熱はないのですか？</span>@@
6. Do you have any night sweats? @@html:<span class="ja">寝汗をかくことはないですか？</span>@@
7. Do you have any weight changes? @@html:<span class="ja">体重の変化はありますか？</span>@@
8. Are you opening your bowels? @@html:<span class="ja">ウンチは出ていますか？</span>@@
9. Are you passing urine? @@html:<span class="ja">尿は出ていますか？</span>@@
10. Do you have any nausea or vomiting? @@html:<span class="ja">吐き気や嘔吐はないですか？</span>@@

After you do these questions, do a summary and then ask about ICE. @@html:<span class="ja">これらの質問をした後、サマリーを行い、その後ICEについて質問します。</span>@@

Finally, do these:
1. Medical, surgical, drug, family, and social history
2. In the social history, remember to ask about previous jobs. If they works in a coal mine, this is worrying (because they will get lung issues). @@html:<span class="ja">ソーシャルヒストリーでは、以前の仕事について尋ねることを忘れないようにしましょう。炭鉱で働いていた場合は心配です（肺に問題があるため）。</span>@@

Look at this [[https://drive.google.com/uc?export=view&id=10bsmx4apyOAErXArjB7mOvKM474UdEx6][picture]], and then read this story:

@@html:Once upon a time, there was an <mark>asthmatic weasel (WHEEZE and SHORTNESS OF BREATH)</mark> in the forest. That weasel likes to eat <mark>coal (COAL MINE JOB)</mark>. One day, the weasel ate too much coah and he started <mark>coughing a lot of nuts (COUGH)</mark>. The nuts were suuuuuper big, and they caused the weasel a lot of <mark>pain (PAIN)</mark>. The weasel was in so much pain, he started to get <mark>ドキドキドキドキドキドキドキドキドキドキ (PALPITATIONS)</mark>. His heart became soooo hot, and the weasel started <mark>burning (FEVER)</mark> and <mark>sweating (NIGHT SWEATS)</mark>. <span class="ja">むかしむかし、森にイタチさんがいました。その<mark>喘息持ちのイタチさん(WHEEZE and SHORTNESS OF BREATH)</mark>は、<mark>石炭(COAL MINE JOB)</mark>を食べるのが好きです。ある日、イタチさんが石炭を食べ過ぎて、<mark>木の実をたくさん咳き込むようになりました(COUGH)</mark>。その木の実はとても大きく、イタチさんを<mark>大苦しめました(PAIN)</mark>。イタチさんはあまりの痛さに、<mark>ドキドキドキドキドキドキドキドキドキドキ(PALPITATIONS)</mark>してきました。心臓は大熱くなり、イタチさんは<mark>火照り(FEVER)</mark>、<mark>汗をかき(NIGHT SWEATS)</mark>はじめました。</span>@@

Done!

* Basics of symptoms
:PROPERTIES:
:CUSTOM_ID: org8c96f99
:END:

Posted: 2023-04-14 | Updated: 2023-04-14

Yo, what's up? How is life? Have you eaten your dinner yet?! @@html:<span class="ja"> よ～、調子はどうですか？生活はどうですか？もうご飯は食べましたか？！</span>@@

Do you want to know a really cool trick to make sure that your history is /amazing/? @@html:<span class="ja">あなたの歴史を素晴らしいものにする、とてもクールなトリックを知りたくありませんか？</span>@@

Keep reading. @@html:<span class="ja">読み進めてください。</span>@@

Every time we get a patient, they will have some kind of symptom which is bothering them. They will complain about that symptom. This is called the "presenting complaint". @@html:<span class="ja">患者さんが来院されると、必ず何らかの症状があり、それを気にされます。そして、その症状を訴える。これを「主訴」と呼びます。</span>@@

Now, as a detective, you need to figure out the cause of that symptom. So... you have to ask questions. A /lot/ of questions. @@html:<span class="ja">さて、探偵としては、その症状の原因を突き止める必要があります。だから...質問する必要があるんだ。たくさん質問するんだ。</span>@@

But... how do we know what to ask? @@html:<span class="ja">でも... どうやって聞けばいいんだろう？</span>@@

Easy!! @@html:<span class="ja">簡単なことです！！</span>@@

There are 4 main questions which apply to /all/ symptoms. If you learn them, then you will be 90% of the way there! @@html:<span class="ja">すべての症状に当てはまる、4つの主要な質問があります。それを覚えれば、9割は解決します！</span>@@

Okay, ready? Here we go.

You need to ask these questions for any presenting complaint @@html:<span class="ja">どのような症状に遭遇しても、これらの質問をする必要があります</span>@@:
1. @@html:<mark>D</mark>uration@@: how long has this been going on for? @@html:<span class="ja">症状の持続時間: いつからそうなっているのでしょうか？</span>@@
2. @@html:<mark>O</mark>nset@@: when did it start? @@html:<span class="ja">症状の発現時間: いつから始まったのですか？</span>@@
3. @@html:<mark>P</mark>rogress and time@@: did it get better or worse? Is it there all the time? Is there just in the morning? Is there after food/drink? @@html:<span class="ja">症状の進行と時期: 良くなったのか、悪くなったのか？ずっとあるのでしょうか？朝だけですか？食べ物や飲み物の後にありますか？</span>@@

@@html:So, to remember these, you can use the word <mark>DOP</mark>! Like the DOPs that you have to do in the hospital!!!! <span class="ja">で、これらを覚えるには、<mark>DOP</mark>という言葉を使うといいんです！病院でやらなければならないDOPsのようにね！！！！</span>@@

すごいね？！
