#+TITLE: History 002

#+BEGIN_EXPORT html
<div class="engt">History</div>
<div class="japt">病歴聴取</div>
<div class="engt">Page 002</div>
#+END_EXPORT

[[https://github.com/ahisu6/ahisu6.github.io/edit/main/src/h/002.org][Edit]]

[[file:./index.org][Home]]

[[file:./001.org][<< Previous page]] - [[file:./003.org][Next page >>]]

-----

#+TOC: headlines 2

* Progesterone-only Pill
:PROPERTIES:
:CUSTOM_ID: org87e7518
:END:

Posted: 2023-06-27 | Updated: 2023-06-27

The progesterone-only pill (POP) is different from the COCP. @@html:<span class="ja">プロゲステロンのみのピル（POP）はCOCPとは異なる。</span>@@

I like the name "POP"... it sounds like "pop" (pop = 弾ける). For example, when you pop a balloon 笑

Anywayyyyyyyyy 笑

The POP does not have oestrogen. So, this pill will not stop ovulation. @@html:<span class="ja">POPにはエストロゲンは含まれていません。ですから、このピルで排卵が止まることはありません。</span>@@

This means that the woman must take the pill at the /exact/ same time each day. @@html:<span class="ja">つまり、女性は毎日まったく同じ時間にピルを服用しなければならない。</span>@@

If the woman does not do that, then her uterus will pop (like a balloon)... no, I'm joking lol. Sorry. @@html:<span class="ja">もし女性がそうしなければ、子宮が「pop / 弾ける」をすることになる (風船のように)...。いや、冗談だよ笑。ごめん。</span>@@

Yeahhhhh, maybe I should sleep now... 笑

But, seriously, the woman should take the pill at the /same time/ every day. @@html:<span class="ja">しかし、真面目な話、女性は毎日同じ時間にピルを飲むべきだ。</span>@@

Say these things in order:
1. Good morning, my name is Dr. XYZ. Can I get your name and date of birth please? @@html:<span class="ja">おはようございます、私はドクターXYZと申します。あなたのお名前と生年月日をお聞かせください。</span>@@
2. Thank you for coming today. @@html:<span class="ja">本日はご来場いただきありがとうございました。</span>@@
3. So, before we begin, I would like to ask you a question if you do not mind. @@html:<span class="ja">では、その前に、差し支えなければ質問させてください。</span>@@
4. What do you already know about the progesterone-only pill? @@html:<span class="ja">プロゲステロンのみのピルについて、すでに知っていることはありますか？</span>@@
5. /Give the patient some time to explain./ @@html:<span class="ja"><i>患者さんに説明する時間を与えてください。</i></span>@@
6. Is there anything in particular that worries you about the progesterone-only pill? @@html:<span class="ja">プロゲステロンのみのピルで特に心配なことはありますか？</span>@@
7. /Give the patient some time to explain./ @@html:<span class="ja"><i>患者さんに説明する時間を与えてください。</i></span>@@
8. What are your expectations regarding the progesterone-only pill? @@html:<span class="ja">プロゲステロンのみのピルについて、どのようなことを期待していますか？</span>@@
9. /Give the patient some time to explain./ @@html:<span class="ja"><i>患者さんに説明する時間を与えてください。</i></span>@@
10. @@html:<mark>Your body releases an egg every month. The pill thickens the mucus at the tip of your womb, which makes it difficult for sperm to swim up and reach an egg. <span class="ja">あなたの体は毎月卵子を放出します。ピルは子宮の先端の粘液を厚くし、精子が卵子まで泳いで到達するのを難しくします。</span></mark>@@
11. /Give the patient few seconds of silence./ @@html:<span class="ja"><i>患者に数秒の沈黙を与える。</i></span>@@
12. Is that clear so far? Do you have any questions for me? Could you repeat back to me what I have said just to make sure that I explained it clearly for you? @@html:<span class="ja">ここまででクリアでしょうか？何か質問はありますか？私が言ったことをもう一度言ってもらえますか？あなたのために明確に説明したことを確認するために。</span>@@
13. /Give the patient some time to explain./ @@html:<span class="ja"><i>患者さんに説明する時間を与えてください。</i></span>@@
14. That is great. Thank you. @@html:<span class="ja">それは素晴らしい。ありがとう。</span>@@
15. So, the pill is 99% effective at preventing pregnancy if you take it correctly, but it does not offer protection against sexually transmitted infections. @@html:<span class="ja">だから、ピルは正しく飲めば99％妊娠を防ぐ効果がありますが、性感染症を防ぐ効果はありません。</span>@@
16. @@html:<mark>To take the pill correctly, you need to take it each day at the /exact/ same time. Also, you must not miss pills. <span class="ja">ピルを正しく服用するには、毎日まったく同じ時間に服用する必要があります。また、ピルの飲み忘れも禁物です。</span></mark>@@
17. /Give the patient few seconds of silence./ @@html:<span class="ja"><i>患者に数秒の沈黙を与える。</i></span>@@
18. I will just do a quick summary of what I have told you so far. @@html:<span class="ja">これまでお話ししたことを簡単にまとめておこう。</span>@@
19. /Do a quick summary./ @@html:<span class="ja"><i>簡単なまとめをしてください。</i></span>@@
20. Would you like me to talk about the advantages and disadvantages of the pill? @@html:<span class="ja">ピルのメリットとデメリットについて話しましょうか？</span>@@
21. @@html:<mark>Some of the advantages are: this pill is safe to take if you are breastfeeding. Another advantage is that it is a non-invasive method. Finally, it is 99% effective. <span class="ja">利点としては、授乳中でも安全に服用できることです。もう一つの利点は、非侵襲的な方法であるということです。最後に、99％効果的です。</span></mark>@@
22. @@html:<mark>Some of the disadvantages are: it does not prevent STIs. Another bad thing is that you have to remember to take it at the same time every day. Finally, some patients might get headache and breast tenderness. <span class="ja">欠点としては、性病を予防できないこと。もう一つの悪い点は、毎日同じ時間に服用することを忘れなければならないことです。最後に、患者によっては頭痛や乳房の圧痛を感じることがあります。</span></mark>@@
23. There are more advantages and disadvantages. So, here is an information leaflet which talks about all of them. If you have questions, then please ask me. @@html:<span class="ja">メリットもあればデメリットもある。そこで、これらすべてについて書かれたインフォメーション・リーフレットを用意しました。ご質問があれば、私にお尋ねください。</span>@@
24. /Give the patient few seconds of silence./ @@html:<span class="ja"><i>患者に数秒の沈黙を与える。</i></span>@@
25. I will just do a quick summary of what I have told you so far. @@html:<span class="ja">これまでお話ししたことを簡単にまとめておこう。</span>@@
26. /Do a quick summary./ @@html:<span class="ja"><i>簡単なまとめをしてください。</i></span>@@
27. There are some risks associated with taking the pill. I feel like you should know about this so that you can make an informed decision. Would you like me to discuss this now? @@html:<span class="ja">ピルの服用にはいくつかのリスクがあります。あなたが十分な情報を得た上で決断できるように、このことについて知っておくべきだと思います。今お話ししましょうか？</span>@@
28. @@html:<mark>The pill increases your risk of developing breast cancer. <span class="ja">ピルは乳がんの発症リスクを高めます。</span></mark>@@
29. So, if you have a family history of breast cancer, then you must not take the pill. @@html:<span class="ja">ですから、乳がんの家族歴がある人は、ピルを飲んではいけません。</span>@@
30. /Give the patient few seconds of silence./ @@html:<span class="ja"><i>患者に数秒の沈黙を与える。</i></span>@@
31. Is that clear so far? Do you have any questions for me? Could you repeat back to me what I have said just to make sure that I explained it clearly for you? @@html:<span class="ja">ここまででクリアでしょうか？何か質問はありますか？私が言ったことをもう一度言ってもらえますか？あなたのために明確に説明したことを確認するために。</span>@@
32. /Give the patient some time to explain./ @@html:<span class="ja"><i>患者さんに説明する時間を与えてください。</i></span>@@
33. Now, you might be thinking, "what if I miss a pill?" @@html:<span class="ja">「ピルを飲み忘れたらどうしよう」と思うかもしれない。</span>@@
34. @@html:<mark>If you miss one pill by MORE than 3 hours, then take the missed pill right away and then use condoms for the next two days. Also, keep taking the pill as normal. <span class="ja">ピルを3時間以上飲み忘れた場合は、飲み忘れたピルをすぐに服用し、その後2日間はコンドームを使用します。また、通常通りピルを飲み続ける。</span></mark>@@
35. @@html:<mark>If you miss one pill by less than 3 hours, then take a pill as soon as you remember. By doing this, you will be protected against pregnancy. <span class="ja">ピルを3時間以内に飲み忘れた場合は、思い出し次第、すぐにピルを飲む。そうすることで、妊娠を防ぐことができます。</span></mark>@@
36. /Give the patient few seconds of silence./ @@html:<span class="ja"><i>患者に数秒の沈黙を与える。</i></span>@@
37. Is that clear so far? Do you have any questions for me? Could you repeat back to me what I have said just to make sure that I explained it clearly for you? @@html:<span class="ja">ここまででクリアでしょうか？何か質問はありますか？私が言ったことをもう一度言ってもらえますか？あなたのために明確に説明したことを確認するために。</span>@@
38. /Give the patient some time to explain./ @@html:<span class="ja"><i>患者さんに説明する時間を与えてください。</i></span>@@
39. Good. @@html:<span class="ja">いいです。</span>@@
40. 笑。 This is a smile :)))
41. If you have any questions, let me know. @@html:<span class="ja">何か質問があれば言ってくれ。</span>@@
42. Thank you for speaking to me today. @@html:<span class="ja">今日は話してくれてありがとう。</span>@@

The patient might ask the following questions @@html:<span class="ja">患者は次のような質問をするかもしれない</span>@@:
- Do certain medications interact with the pill? @@html:<span class="ja">ある種の薬はピルと相互作用がありますか？</span>@@
  - Yes, some drugs interact. A few examples are HIV drugs, epilepsy drugs, and St John's Wort. There are more drugs mentioned in the information leaflet that I have provided you with. @@html:<span class="ja">はい、相互作用がある薬もあります。例えば、HIV治療薬、てんかん治療薬、セント・ジョーンズ・ワートなどです。私がお渡しした情報リーフレットには、もっと多くの薬剤が記載されています。</span>@@
- What if I am vomiting or have diarrhoea? @@html:<span class="ja">嘔吐や下痢の場合はどうすればいいですか？</span>@@
  - If you vomit within 2 hours after taking the pill, then you should take another pill. @@html:<span class="ja">ピルを服用後2時間以内に嘔吐した場合は、別のピルを服用する必要があります。</span>@@
  - If you have severe diarrhoea in the last 24 hours, then this is considered as a missed pill. So, follow the instructions that are shown in the leaflet. @@html:<span class="ja">もし、24時間以内にひどい下痢をした場合は、飲み忘れとみなされます。そのため、リーフレットに記載されている指示に従ってください。</span>@@
- What if I want to get pregnant? @@html:<span class="ja">妊娠を希望する場合は？</span>@@
  - If you want to get pregnant, then stop taking the pill. Then, wait for the first natural period to come. After the natural period comes, you can become pregnant. @@html:<span class="ja">妊娠を望むなら、ピルの服用を中止すること。そして、最初の自然な生理が来るのを待ちます。自然な生理が来れば、妊娠することができます。</span>@@

* Vaccination
:PROPERTIES:
:CUSTOM_ID: org54d2dc9
:END:

Posted: 2023-06-25 | Updated: 2023-06-25

1. Good morning, my name is Dr. XYZ. Can I get your name and date of birth please? @@html:<span class="ja">おはようございます、私はドクターXYZと申します。あなたのお名前と生年月日をお聞かせください。</span>@@
2. Thank you for coming today. @@html:<span class="ja">本日はご来場いただきありがとうございました。</span>@@
3. So, before we begin, I would like to ask you a question if you do not mind. @@html:<span class="ja">では、その前に、差し支えなければ質問させてください。</span>@@
4. What do you already know about vaccinations? @@html:<span class="ja">予防接種についてすでに知っていることは？</span>@@
5. /Give the patient some time to explain./ @@html:<span class="ja"><i>患者さんに説明する時間を与えてください。</i></span>@@
6. Is there anything in particular that worries you? @@html:<span class="ja">特に心配していることはありますか？</span>@@
7. /Give the patient some time to explain./ @@html:<span class="ja"><i>患者さんに説明する時間を与えてください。</i></span>@@
8. What are your expectations regarding the consultation today? @@html:<span class="ja">今日の相談について、どのようなことを期待していますか？</span>@@
9. /Give the patient some time to explain./ @@html:<span class="ja"><i>患者さんに説明する時間を与えてください。</i></span>@@
10. A vaccination is a kind of medication that teaches your body how to combat a disease without actually catching it. @@html:<span class="ja">予防接種とは、実際に病気にかかることなく、その病気と闘う方法を体に教える一種の薬である。</span>@@
11. This is accomplished by encouraging your immune system to develop a defence against the illness even before you are exposed to it. @@html:<span class="ja">これは、病気にかかる前から、免疫系が病気に対する防御機能を発達させるよう促すことで達成される。</span>@@
12. By doing this, your body will be ready to fight off the disease if you ever come into contact with it. @@html:<span class="ja">そうすることで、万が一病気に接触した場合でも、体がその病気を撃退できるようになるのだ。</span>@@
13. So, in the future, you will not get sick at all or only suffer mild symptoms. @@html:<span class="ja">そのため、将来はまったく病気にならないか、軽い症状で済むようになる。</span>@@
14. /Give the patient few seconds of silence./ @@html:<span class="ja"><i>患者に数秒の沈黙を与える。</i></span>@@
15. Is that clear so far? Do you have any questions for me? Could you repeat back to me what I have said just to make sure that I explained it clearly for you? @@html:<span class="ja">ここまででクリアでしょうか？何か質問はありますか？私が言ったことをもう一度言ってもらえますか？あなたのために明確に説明したことを確認するために。</span>@@
16. /Give the patient some time to explain./ @@html:<span class="ja"><i>患者さんに説明する時間を与えてください。</i></span>@@
17. There is something called a vaccination schedule. This is noted in your Red book. The schedule starts when the baby is 8 weeks old. @@html:<span class="ja">予防接種のスケジュールというものがある。これは「Red Book」に記載されています。スケジュールは生後8週から始まります。</span>@@
18. Most vaccines need a booster. This means that the baby will get mulitple injections. @@html:<span class="ja">ほとんどのワクチンはブースターが必要である。つまり、赤ちゃんは何度も注射を受けることになる。</span>@@
19. After the booster doses, the baby will have a lifetime immunity. This means that they will protected from severe infections in the future. @@html:<span class="ja">ブースター接種後、赤ちゃんは生涯免疫を持つことになる。つまり、将来、重症の感染症から赤ちゃんを守ることができるのです。</span>@@
20. /Give the patient few seconds of silence./ @@html:<span class="ja"><i>患者に数秒の沈黙を与える。</i></span>@@
21. Is that clear so far? Do you have any questions for me? Could you repeat back to me what I have said just to make sure that I explained it clearly for you? @@html:<span class="ja">ここまででクリアでしょうか？何か質問はありますか？私が言ったことをもう一度言ってもらえますか？あなたのために明確に説明したことを確認するために。</span>@@
22. /Give the patient some time to explain./ @@html:<span class="ja"><i>患者さんに説明する時間を与えてください。</i></span>@@
23. Good. @@html:<span class="ja">いいです。</span>@@
24. So, now, how do you feel about getting the vaccination for your baby? @@html:<span class="ja">さて、赤ちゃんのために予防接種を受けることについてどう思いますか？</span>@@
25. Here is an information leaflet which explains everything we have talked about. @@html:<span class="ja">このリーフレットには、これまでお話ししたことがすべて説明されています。</span>@@
26. 笑。 This is a smile :)))
27. If you have any questions, let me know. @@html:<span class="ja">何か質問があれば言ってくれ。</span>@@
28. Thank you for speaking to me today. @@html:<span class="ja">今日は話してくれてありがとう。</span>@@

The patient might ask the following questions @@html:<span class="ja">患者は次のような質問をするかもしれない</span>@@:
- What should I expect on the vaccination day? @@html:<span class="ja">予防接種当日の注意点は？</span>@@
  - You will be asked few questions about your baby's health, including whether they have recently been ill and whether they have any health issues or allergies. This is done to ensure that the vaccine is appropriate. @@html:<span class="ja">赤ちゃんの健康状態について、最近病気にかかったことがないか、健康上の問題やアレルギーがないかなど、いくつかの質問をされます。これは、ワクチンが適切であることを確認するために行われます。</span>@@
  - Then, the baby will be given an injection. This is usually in the thigh. @@html:<span class="ja">その後、赤ちゃんに注射をします。これは通常、太ももに行われます。</span>@@
- Are there any side effects? @@html:<span class="ja">副作用はありますか？</span>@@
  - The baby might get a low fever. The baby might also feed annoyed. This is normal. Just keep feeding the baby as usual, and give Calpol when needed. @@html:<span class="ja">赤ちゃんが微熱を出すかもしれない。また、赤ちゃんは哺乳を催すかもしれません。これは正常なことです。いつもと同じように授乳を続け、必要に応じてカルポールを与えてください。</span>@@
  - The baby might also get some mild pain in the thigh because of the injection. @@html:<span class="ja">赤ちゃんは、注射のために太ももに軽い痛みを感じるかもしれません。</span>@@
  - About 1 in 500,000 babies will get an allergic reaction. This will be a swelling of the lips and face. Seek immediate medical help if that happens. @@html:<span class="ja">約50万人に1人の赤ちゃんがアレルギー反応を起こす。これは唇や顔の腫れになります。このような場合は、ただちに医療機関を受診してください。</span>@@
- Does the MMR cause autism? @@html:<span class="ja">MMRは自閉症の原因か？</span>@@
  - No, the MMR does not cause autism. This area of medicine has been studied heavily over the last years, and it has been shown that the MMR does not cause autism. @@html:<span class="ja">いいえ、MMRは自閉症の原因ではありません。この分野の医学はここ何年も研究が重ねられ、MMRが自閉症を引き起こさないことが明らかになっている。</span>@@
- Can I wait few more years before giving my baby the vaccine? @@html:<span class="ja">赤ちゃんにワクチンを接種する前に、あと数年待つことはできますか？</span>@@
  - It is better to give the vaccine at a young age. @@html:<span class="ja">ワクチンは若いうちに接種したほうがいい。</span>@@
  - Babies are vulnerable, and the vaccine will protect them from serious diseases. @@html:<span class="ja">赤ちゃんは傷つきやすいので、ワクチンは深刻な病気から守ってくれる。</span>@@
  - But, the choice is yours. @@html:<span class="ja">でも、選ぶのはあなた自身だ。</span>@@

* Combined Oral Contraceptive Pill (COCP) Counselling
:PROPERTIES:
:CUSTOM_ID: org7d34bc2
:END:

Posted: 2023-06-24 | Updated: 2023-06-24

COCP is a hormonal pill. @@html:<span class="ja">COCPはホルモン剤である。</span>@@

COCP has oestrogen and progestogen. @@html:<span class="ja">COCPにはエストロゲンとプロゲストゲンがある。</span>@@

The high level oestrogen and progestogen trick the body. They will tell the body to stop ovulation. @@html:<span class="ja">高濃度のエストロゲンとプロゲストゲンが体をだます。それらは排卵を止めるよう体に指示する。</span>@@

The patient will have to take a pill every day. @@html:<span class="ja">患者は毎日錠剤を飲まなければならない。</span>@@

Some COCP plans have 21 hormonal pills, and 7 fake pills. @@html:<span class="ja">COCPプランの中には、21種類のホルモン剤と7種類の偽薬があるものもある。</span>@@

These fake pills cause something called a "withdrawal bleed." @@html:<span class="ja">これらの偽薬は「禁断症状出血」と呼ばれるものを引き起こす。</span>@@

Here is a diagram which explains what happens to your hormones when you take the pill @@html:<span class="ja">ピルを飲むとホルモンに何が起こるかを説明した図がある</span>@@:
1. [[https://drive.google.com/uc?export=view&id=1pfveJK3RKz8i1EBhCCAFGCa6jBZfPq4X][Japanese version]].
2. [[https://drive.google.com/uc?export=view&id=1hzge3qHcbc1JtLYj9WeFeglsEBF6owiC][English version]].

Say these things in order:
1. Good morning, my name is Dr. XYZ. Can I get your name and date of birth please? @@html:<span class="ja">おはようございます、私はドクターXYZと申します。あなたのお名前と生年月日をお聞かせください。</span>@@
2. Thank you for coming today. @@html:<span class="ja">本日はご来場いただきありがとうございました。</span>@@
3. So, before we begin, I would like to ask you a question if you do not mind. @@html:<span class="ja">では、その前に、差し支えなければ質問させてください。</span>@@
4. What do you already know about the combined oral contraceptive pill? @@html:<span class="ja">経口避妊薬配合ピルについてすでに知っていることは？</span>@@
5. /Give the patient some time to explain./ @@html:<span class="ja"><i>患者さんに説明する時間を与えてください。</i></span>@@
6. Is there anything in particular that worries you about the combined oral contraceptive pill? @@html:<span class="ja">経口避妊薬併用ピルについて、特に心配なことはありますか？</span>@@
7. /Give the patient some time to explain./ @@html:<span class="ja"><i>患者さんに説明する時間を与えてください。</i></span>@@
8. What are your expectations regarding the combined oral contraceptive pill? @@html:<span class="ja">複合経口避妊ピルについて、どのようなことを期待していますか？</span>@@
9. /Give the patient some time to explain./ @@html:<span class="ja"><i>患者さんに説明する時間を与えてください。</i></span>@@
10. The pill contains hormones that stop your ovaries from releasing an egg each month. Without an egg, you can't get pregnant. The pill also thickens the mucus at the tip of your womb, which makes it difficult for sperm to swim up and reach an egg. @@html:<span class="ja">ピルには、毎月卵巣から卵子が放出されるのを止めるホルモンが含まれています。卵子がなければ妊娠することはできません。また、ピルは子宮の先端の粘液を厚くし、精子が卵子まで泳いで到達するのを難しくします。</span>@@
11. /Give the patient few seconds of silence./ @@html:<span class="ja"><i>患者に数秒の沈黙を与える。</i></span>@@
12. Is that clear so far? Do you have any questions for me? Could you repeat back to me what I have said just to make sure that I explained it clearly for you? @@html:<span class="ja">ここまででクリアでしょうか？何か質問はありますか？私が言ったことをもう一度言ってもらえますか？あなたのために明確に説明したことを確認するために。</span>@@
13. /Give the patient some time to explain./ @@html:<span class="ja"><i>患者さんに説明する時間を与えてください。</i></span>@@
14. That is great. Thank you. @@html:<span class="ja">それは素晴らしい。ありがとう。</span>@@
15. So, the pill is 99% effective at preventing pregnancy if you take it correctly, but it does not offer protection against sexually transmitted infections. @@html:<span class="ja">だから、ピルは正しく飲めば99％妊娠を防ぐ効果がありますが、性感染症を防ぐ効果はありません。</span>@@
16. To take the pill correctly, you need to take it each day and don't miss pills. @@html:<span class="ja">ピルを正しく服用するには、毎日欠かさず服用する必要があります。</span>@@
17. /Give the patient few seconds of silence./ @@html:<span class="ja"><i>患者に数秒の沈黙を与える。</i></span>@@
18. I will just do a quick summary of what I have told you so far. @@html:<span class="ja">これまでお話ししたことを簡単にまとめておこう。</span>@@
19. /Do a quick summary./ @@html:<span class="ja"><i>簡単なまとめをしてください。</i></span>@@
20. Would you like me to talk about the advantages and disadvantages of the pill? @@html:<span class="ja">ピルのメリットとデメリットについて話しましょうか？</span>@@
21. Some of the advantages are: it is 99% effective. Another advantage is that it is a non-invasive method. Finally, the pill can improve acne. @@html:<span class="ja">利点としては、99％効果があることです。もう一つの利点は、非侵襲的な方法であるということです。最後に、ピルはニキビを改善することができる。</span>@@
22. Some of the disadvantages are: it does not prevent STIs. Another bad thing is that you have to remember to take it every day. Finally, some patients might get headache and breast tenderness. @@html:<span class="ja">欠点としては、性病を予防できないことが挙げられる。もう一つの悪い点は、毎日忘れずに服用しなければならないことです。最後に、患者によっては頭痛や乳房の圧痛を感じることがあります。</span>@@
23. There are more advantages and disadvantages. So, here is an information leaflet which talks about all of them. If you have questions, then please ask me. @@html:<span class="ja">メリットもあればデメリットもある。そこで、これらすべてについて書かれたインフォメーション・リーフレットを用意しました。ご質問があれば、私にお尋ねください。</span>@@
24. /Give the patient few seconds of silence./ @@html:<span class="ja"><i>患者に数秒の沈黙を与える。</i></span>@@
25. I will just do a quick summary of what I have told you so far. @@html:<span class="ja">これまでお話ししたことを簡単にまとめておこう。</span>@@
26. /Do a quick summary./ @@html:<span class="ja"><i>簡単なまとめをしてください。</i></span>@@
27. There are some risks associated with taking the pill. I feel like you should know about this so that you can make an informed decision. Would you like me to discuss this now? @@html:<span class="ja">ピルの服用にはいくつかのリスクがあります。あなたが十分な情報を得た上で決断できるように、このことについて知っておくべきだと思います。今お話ししましょうか？</span>@@
28. There are two main risks. @@html:<span class="ja">主なリスクは2つある。</span>@@
29. The first risk is that there is a small chance that the pill can clots in your legs and lungs. @@html:<span class="ja">第一のリスクは、ピルが足や肺に血栓を作る可能性があることです。</span>@@
30. It is very important that you do not take the pill if you had blood clots or heart issues in the past. @@html:<span class="ja">過去に血栓や心臓に問題があった場合は、ピルを服用しないことが非常に重要です。</span>@@
31. Also, if you have migraine, then you must not take the pill as it can increase the risk of a blood clot forming. @@html:<span class="ja">また、片頭痛のある人は、血栓ができるリスクが高まるので、ピルを服用してはならない。</span>@@
32. Another risk is cancer. The pill increases your risk of developing breast and cervical cancer. @@html:<span class="ja">もう一つのリスクは癌である。ピルは乳がんや子宮頸がんの発症リスクを高めます。</span>@@
33. So, if you have a family history of breast cancer, then you must not take the pill. @@html:<span class="ja">ですから、乳がんの家族歴がある人は、ピルを飲んではいけません。</span>@@
34. /Give the patient few seconds of silence./ @@html:<span class="ja"><i>患者に数秒の沈黙を与える。</i></span>@@
35. Is that clear so far? Do you have any questions for me? Could you repeat back to me what I have said just to make sure that I explained it clearly for you? @@html:<span class="ja">ここまででクリアでしょうか？何か質問はありますか？私が言ったことをもう一度言ってもらえますか？あなたのために明確に説明したことを確認するために。</span>@@
36. /Give the patient some time to explain./ @@html:<span class="ja"><i>患者さんに説明する時間を与えてください。</i></span>@@
37. Now, you might be thinking, "what if I miss a pill?" @@html:<span class="ja">「ピルを飲み忘れたらどうしよう」と思うかもしれない。</span>@@
38. If you miss one pill, then take the missed pill right away and carry on as usual with the other pills in the pack. No need for emergency contraception. @@html:<span class="ja">1錠飲み忘れた場合は、飲み忘れた錠剤をすぐに服用し、パック内の他の錠剤を通常通り服用する。緊急避妊の必要はありません。</span>@@
39. If you missed more than one pill, then you should take the most recent missed pills immediately. Leave any earlier missed pills. Use condoms or skip intercourse for the following 7 days. If you've had sex within the last week, you should get advice on emergency contraception. @@html:<span class="ja">複数の錠剤を飲み忘れた場合は、飲み忘れた直近の錠剤をすぐに服用すること。以前に飲み忘れたピルは残しておく。その後7日間はコンドームを使用するか、性交を控える。最近1週間以内に性交渉を持った人は、緊急避妊のアドバイスを受けるべきです。</span>@@
40. If there are seven or more pills left, then you should finish the pack and have the usual 7-day break. @@html:<span class="ja">残りが7錠以上ある場合は、1パックを飲み終え、通常の7日間の休薬期間を設ける。</span>@@
41. If there are less than seven pills left in the pack, you should finish the pack. Then, after the pack is finished, you should start a new pack the next day. This means taking the pills one after the other without skipping any days. @@html:<span class="ja">パックに残っている錠剤が7錠未満の場合は、残りの錠剤を服用する。パックが終わったら、次の日に新しいパックを始める。つまり、1日も欠かさずに次々と錠剤を飲むということだ。</span>@@
42. /Give the patient few seconds of silence./ @@html:<span class="ja"><i>患者に数秒の沈黙を与える。</i></span>@@
43. Is that clear so far? Do you have any questions for me? Could you repeat back to me what I have said just to make sure that I explained it clearly for you? @@html:<span class="ja">ここまででクリアでしょうか？何か質問はありますか？私が言ったことをもう一度言ってもらえますか？あなたのために明確に説明したことを確認するために。</span>@@
44. /Give the patient some time to explain./ @@html:<span class="ja"><i>患者さんに説明する時間を与えてください。</i></span>@@
45. Good. @@html:<span class="ja">いいです。</span>@@
46. 笑。 This is a smile :)))
47. If you have any questions, let me know. @@html:<span class="ja">何か質問があれば言ってくれ。</span>@@
48. Thank you for speaking to me today. @@html:<span class="ja">今日は話してくれてありがとう。</span>@@

The patient might ask the following questions @@html:<span class="ja">患者は次のような質問をするかもしれない</span>@@:
- Do certain medications interact with the pill? @@html:<span class="ja">ある種の薬はピルと相互作用がありますか？</span>@@
  - Yes, some drugs interact. A few examples are HIV drugs, epilepsy drugs, and St John's Wort. There are more drugs mentioned in the information leaflet that I have provided you with. @@html:<span class="ja">はい、相互作用がある薬もあります。例えば、HIV治療薬、てんかん治療薬、セント・ジョーンズ・ワートなどです。私がお渡しした情報リーフレットには、もっと多くの薬剤が記載されています。</span>@@
- What if I am vomiting or have diarrhoea? @@html:<span class="ja">嘔吐や下痢の場合はどうすればいいですか？</span>@@
  - If you vomit within 2 hours after taking the pill, then you should take another pill. @@html:<span class="ja">ピルを服用後2時間以内に嘔吐した場合は、別のピルを服用する必要があります。</span>@@
  - If you have severe diarrhoea in the last 24 hours, then this is considered as a missed pill. So, follow the instructions that are shown in the leaflet. @@html:<span class="ja">もし、24時間以内にひどい下痢をした場合は、飲み忘れとみなされます。そのため、リーフレットに記載されている指示に従ってください。</span>@@
- What if I want to get pregnant? @@html:<span class="ja">妊娠を希望する場合は？</span>@@
  - If you want to get pregnant, then stop taking the pill. Then, wait for the first natural period to come. After the natural period comes, you can become pregnant. @@html:<span class="ja">妊娠を望むなら、ピルの服用を中止すること。そして、最初の自然な生理が来るのを待ちます。自然な生理が来れば、妊娠することができます。</span>@@
