#+TITLE: History 003

#+BEGIN_EXPORT html
<div class="engt">History</div>
<div class="japt">病歴聴取</div>
<div class="engt">Page 003</div>
#+END_EXPORT

[[https://github.com/ahisu6/ahisu6.github.io/edit/main/src/h/003.org][Edit]]

[[file:./index.org][Home]]

[[file:./002.org][<< Previous page]] - [[file:./004.org][Next page >>]]

-----

#+TOC: headlines 2

* Explaining things
:PROPERTIES:
:CUSTOM_ID: org245ca4e
:END:

Posted: 2024-03-31 | Updated: 2024-03-31

When someone asks you to explain something, you need to have a template in your head which you can follow.

As you can see, there is a structure @@html:<span class="ja">見ての通り、構造がある</span>@@:
1. Brief history: symptoms, recent investigations, PMH/PSH, DH, FH, and SH. @@html:<span class="ja">簡単な病歴をつける：症状、最近の検査、PMH/PSH、DH、FH、SH。</span>@@
2. ICE.
3. Setting: ask if they want anyone to be present. Ask if they are ok to talk now. @@html:<span class="ja">舞台：誰かに同席してほしいかどうか尋ねる。今すぐ話したいかどうか尋ねる。</span>@@
4. Perception: @@html:what does the patient know about the <mark><u>disease</u></mark>? AND What does the patient know about the <mark><u>treatment of the disease</u></mark>? <span class="ja">知覚：患者は<mark><u>病気</u></mark>について何を知っているか？そして、患者はその<mark><u>病気の治療法</u></mark>について何を知っているか？</span>@@
5. Knowledge of disease: explain the normal human function of the organ (for example, the normal function of the thyroid). Explain the broken function (for example, underactive thyroid). Explain the investigations that the patient had. @@html:<span class="ja">病気に関する知識：臓器の正常な機能を説明する（例えば、甲状腺の正常な機能）。壊れた機能を説明する（例えば、甲状腺機能低下）。患者が受けた検査を説明する。</span>@@
6. Check if they understand. @@html:<span class="ja">彼らが理解しているかどうかを確認する。</span>@@
7. Knowledge of treatment: explain the treatment. Explain how to take the treatment. Explain side effects. Explain if there is any monitoring (for example, blood tests, monitoring symptoms etc.). Explain if there are any serious side effects that the patient should pay attention to. @@html:<span class="ja">病気の治療に関する知識：治療について説明する。治療の受け方を説明する。副作用について説明する。モニタリング（例えば、血液検査、症状のモニタリングなど）の有無を説明する。患者が注意すべき重大な副作用があるかどうか説明する。</span>@@
8. Check if they understand. @@html:<span class="ja">彼らが理解しているかどうかを確認する。</span>@@
9. Exploration: /What are your current thoughts about what I told you today? Any questions?/ @@html:<span class="ja"><i>今日お話ししたことについて、今のお考えは？何か質問はありますか？</i></span>@@
10. Give the patient some time to talk. @@html:<span class="ja">患者に話す時間を与える。</span>@@
11. Strategy: explain next steps, give leaflet, and do safety netting. @@html:<span class="ja">次のステップを説明し、リーフレットを渡し、病気についてのセーフティネットを行う。</span>@@

Here is a SPIKES template for you. This scenario talks about hypothyroidism and levothyroxine, but you can use this for every explanation @@html:<span class="ja">ここにSPIKESのテンプレートを用意しました。このシナリオは甲状腺機能低下症とレボチロキシンについて話していますが、どの説明にも使えます</span>@@:
1. Introduce yourself, gain consent, and tell them that this chat is confidential.
2. Take a brief history to get an idea of the patient and see what has been happening. You can ask few open questions about the symptoms that the patient has been experiencing: /Mr. Musashi, this is the first time I meet you. So, could you please tell me a little bit more about what has been happening?/
3. Let the patient explain the symptoms.
4. Ask about PMH/PSH, DH, FH, and SH.
5. Now, you should do ICE. /Mr. Musashi, do you have any idea what might be causing this? Any concerns? Any expectations?/
6. Setting: /Thank you for sharing this with me. Before we start, would you like to have anyone with you?/
7. Setting: /Is this a good place for us to talk?/
8. Perception: /Before we start, I would like to ask you few more questions. What do you know so far about underactive thyroid?/
9. Let the patient tell you about what they know.
10. Perception: /Thank you for this. And, what do you know about levothyroxine?/
11. Let the patient tell you about what they know.
12. Knowledge: explain underactive thyroid. /From what you have told me today, it sounds similar to something called "underactive thyroid". The thyroid is a part of your body which make hormones that help your body with energy management. In your case, your thyroid is not making a lot of these hormones. So, this is why you are feeling tired./
13. /Is that clear so far? Do you have any questions for me? Could you repeat back to me what I have said just to make sure that I explained it clearly for you?/
14. Give the patient some time to explain.
15. Knowledge: explain levothyroxine. /However, there is treatment for this. There is a drug called "levothyroxine". Levothyroxine is used to raise the amount of thyroid hormones in your body. With the help of this drug, we can get your thyroid hormone levels back to normal and help reduce your symptoms./
16. Knowledge: /Levothyroxine should be taken every morning before breakfast. This is because coffee and food can decrease the absorption. Unfortunately, your thyroid will no longer make enough thyroid hormones. So, you will need to keep taking this drug for the remainder of your life./
17. Knowledge: /We will need to check your thyroid levels again after 6 weeks to make sure that the dose of the drug is suitable for you. Then, we will check your levels after a few months./
18. /Is that clear so far? Do you have any questions for me? Could you repeat back to me what I have said just to make sure that I explained it clearly for you?/
19. Give the patient some time to explain.
20. Knowledge: /Now, when the drug dose is right for you, there are very few side effects. If the dose is too high, you would get overactive thyroid symptoms like tremor and weight loss. If the dose is too low, your current symptoms will not improve. To ensure that we determine the proper dose for you as soon as possible, we will be monitoring your thyroid levels more often in the beginning./
21. /Is that clear so far? Do you have any questions for me? Could you repeat back to me what I have said just to make sure that I explained it clearly for you?/
22. Give the patient some time to explain.
23. Exploration: /What are your current thoughts about what I told you today? Any questions?/
24. Give the patient some time to talk.
25. /Would you like to talk to anyone else?/
26. /Here is a leaflet which tells you more details. If your symptoms do not improve, or if they worsen, please get in touch again. Thank you./
27. /Thank you for your time./

* Neurology
:PROPERTIES:
:CUSTOM_ID: orgeeaa9d8
:END:

Posted: 2024-03-06 | Updated: 2024-03-06

Here is the [[https://drive.google.com/uc?export=view&id=1-yr808gQoPAphcVsRXU8Uv0T-jjQfBMf][picture]]:
- @@html:Do 1. DOP@@
- @@html:This is a <mark>2. cog (cognitive symptoms) 歯車</mark> wheel that is spinning and feeling <mark>3. dizzy (dizziness)</mark>.@@
- @@html:The cog wheel felt very dizzy and it has <mark>4. lost its balance (losing balance)</mark> and so it <mark>5. fell (any falls?)</mark> through a glass window and into a museum.@@
- @@html:It has fallen through museum roof. The museum had many <mark>6. sculptures that have weird body postures (abnormal muscle movements) 奇妙な姿勢の彫刻</mark>. The sculptures <mark>7. looked spiky (sensation) 彫刻がトゲトゲに見えた</mark>.@@
- @@html:The cog wheel <mark>8. tried to lift the sculpture, but it was soooo weak (weakness)</mark>. The cog wheel <mark>9. spinal disc slipped and caused a lot of pain (pain)</mark>.@@
- @@html:The cog wheel was very angry and <mark>10. tried to eat the sculptures (5 senses: taste, smell, hearing, touch, seeing)</mark>, but the sculptures was too big and spikey... so it was <mark>11. difficult to swallow (dysphagia)</mark>.@@
- @@html:Oh no! The <mark>12. cog wheel cannot talk (speech)</mark> anymore! So, it <mark>13. drank urine (urinary symptoms: incontinence, difficulty passing urine)</mark> because urine helps with speech... ew...@@
- @@html:The urine drink made the cog wheel get <mark>14. diarrhoea (bowel symptoms: incontinence, numb around the anus)</mark>.@@

* Urology
:PROPERTIES:
:CUSTOM_ID: org14cc3e3
:END:

Posted: 2024-02-13 | Updated: 2024-02-13

In urology, there are a couple of possible symptoms that patients might have:
- Haematuria
- Dysuria
- Polyuria
- Urethral discharge
- Urgency

Here is a [[https://drive.google.com/uc?export=view&id=1l8-uVy31-iD7duS57OoPkA5oaxKJS1cU][picture]] to help you remember the important questions:
- @@html:<span class="ja">Once upon a time, <mark>Socrates</mark> was <mark>travelling through a stream</mark>, using a <mark>boat</mark>. 昔々、<mark>ソクラテス</mark>は<mark>小舟</mark>で<mark>小川</mark>を旅していた。</span>@@
  - SOCRATES, urinary stream (小川), blood at which point along stream (小舟)
- @@html:<span class="ja">He had a <mark>big bag of coins</mark> that were <mark>running through an hourglass</mark>, this helped Socrates keep track of time. 彼は<mark>砂時計の中</mark>を走っていた<mark>コインの大きな袋</mark>を持っていた、これはソクラテスが時間を追跡するのに役立ちました。</span>@@
  - amount of blood (コインの大きな袋), time taken to empty bladder (砂時計の中)
- @@html:<span class="ja">Socrates came to a dam that was <mark>blocked by clots, many clots</mark>. The dam looked like it was in <mark>great pain</mark> ソクラテスは、<mark>血の塊</mark>（<mark>多くの血の塊</mark>）で塞がれたダムにやってきた。ダムは大きな<mark>痛み</mark>に苦しんでいるように見えた。</span>@@
  - clot (血の塊), frequency (多くの血の塊), pain (痛み)
- @@html:<span class="ja">After a short while, the dam started to <mark>bruise</mark> until it <mark>broke open</mark>. That <mark>dam was not in a great shape</mark>. しばらくすると、ダムは<mark>決壊する</mark>まで<mark>傷つき</mark>始めた。その<mark>ダムはあまりいい状態ではなかった</mark>。</span>@@
  - bruise (傷つき), trauma (決壊する), constitutional (ダムはあまりいい状態ではなかった)

Now, we need to ask questions about these things:
1. Good morning, my name is Dr. XYZ. Can I get your name and date of birth please? @@html:<span class="ja">おはようございます、私はドクターXYZと申します。あなたのお名前と生年月日をお聞かせください。</span>@@
2. Thank you for coming today. @@html:<span class="ja">本日はご来場いただきありがとうございました。</span>@@
3. How can I help you?
4. /Give the patient some time to explain./ @@html:<span class="ja"><i>患者さんに説明する時間を与えてください。</i></span>@@
5. Right, so you have been experiencing some issues with your waterworks (Waterworks means urinary). Would it be okay if I ask you some more questions? Everything you say will be confidential. @@html:<span class="ja">そうですか、水道（水道は泌尿器の意味）に問題があるのですね。もう少し質問してもいいですか？おっしゃることはすべて秘密厳守です。</span>@@
6. Can you describe the issue for me? @@html:<span class="ja">この問題について説明してもらえますか？</span>@@
7. /Give the patient some time to explain./ @@html:<span class="ja"><i>患者さんに説明する時間を与えてください。</i></span>@@
8. Do DOP: How long have you had this for? When did it start? How did it start? Is it getting worse? @@html:<span class="ja">DOP：いつからですか？いつからですか？どのように始まりましたか？悪化していますか？</span>@@
9. Now, I would like to ask you some specific questions if that is okay. @@html:<span class="ja">では、いくつか具体的な質問をしたいのですが、よろしいですか？</span>@@
10. Do you have any difficulty with passing urine? @@html:<span class="ja">尿が出にくいことはありますか？</span>@@
11. Do you have any blood in urine? If the patient says "yes" then ask these questions @@html:<span class="ja">尿に血液は混じっていますか？もし患者が「はい」と答えたら、次のような質問をします</span>@@:
    1. I am sorry to hear that. It must be quite distressing. (You can do ICE here!). @@html:<span class="ja">お気の毒です。とてもつらいことでしょう。(ICEはここでできます！）。</span>@@
    2. What colour is it? @@html:<span class="ja">色は？</span>@@
    3. Does the blood come at the start, middle, or the end of the stream? @@html:<span class="ja">血は流れの最初、真ん中、それとも最後？</span>@@
    4. Are there any clots? @@html:<span class="ja">血栓はありますか？</span>@@
12. How often are you going to the toilet during the day? @@html:<span class="ja">日中、どのくらいの頻度でトイレに行きますか？</span>@@
13. How often are you going to the toilet during the night? @@html:<span class="ja">夜間のトイレの回数は？</span>@@
14. Does it take a long time to empty your bladder? @@html:<span class="ja">膀胱を空にするのに時間がかかりますか？</span>@@
15. Is there any pain? If the patient says "yes" then ask these questions @@html:<span class="ja">痛みはありますか？もし患者が「はい」と答えたら、次のような質問をします</span>@@:
    1. Do SOCRATES
16. Have you noticed any bruising anywhere? @@html:<span class="ja">どこかにあざはありましたか？</span>@@
17. Have you had any physical trauma? @@html:<span class="ja">身体的なトラウマはありますか？</span>@@
18. Have you been sick recently? @@html:<span class="ja">最近体調を崩されましたか？</span>@@
19. Have you had fever? @@html:<span class="ja">熱がありましたか？</span>@@
20. Have you had night sweats? @@html:<span class="ja">寝汗をかいたことはありますか？</span>@@
21. Have you noticed any weight changes? @@html:<span class="ja">体重に変化はありましたか？</span>@@
22. Are you eating and drinking well? @@html:<span class="ja">よく食べ、よく飲んでいるか？</span>@@
23. Are you sleeping well? @@html:<span class="ja">よく眠れていますか？</span>@@
24. /Do a quick summary./ @@html:<span class="ja"><i>簡単なまとめをしてください。</i></span>@@
25. Do ICE.
26. Then, do the rest of the history (past medical, past surgical, etc.)

* Tired all the time
:PROPERTIES:
:CUSTOM_ID: org71232d0
:END:

Posted: 2023-10-08 | Updated: 2023-10-08

Many things can cause tiredness and fatigue:
- Cancer
- Depression
- Thyroid issues
- Diabetes
- Infection
- Sleep issues
- And many more!

Anyway, here is what you should ask:
1. Good morning, my name is Dr. XYZ. Can I get your name and date of birth please? @@html:<span class="ja">おはようございます、私はドクターXYZと申します。あなたのお名前と生年月日をお聞かせください。</span>@@
2. Thank you for coming today. @@html:<span class="ja">本日はご来場いただきありがとうございました。</span>@@
3. How can I help you?
4. Right, so you have been experiencing some tiredness. Can you tell me a little bit more about that?
5. /Give the patient some time to explain./ @@html:<span class="ja"><i>患者さんに説明する時間を与えてください。</i></span>@@
6. I will just do a quick summary of what you have told me so far.
7. /Do a quick summary./ @@html:<span class="ja"><i>簡単なまとめをしてください。</i></span>@@
8. So, how long have you been feeling tired for?
9. When did it start?
10. Has it become better or worse?
11. Is there a particular time of day where you feel most tired?
12. Does anything make it worse?
13. Do you have any ideas, concerns, and expectations?
14. Is it okay if I ask you few more questions?
15. How is your appetite?
16. How is your mood?
17. How is your sleep?
18. Have you had any recent infections?
19. Have you noticed weight changes?
20. Do you feel cold when others think it's warm? (you are checking for hypothyroidism).
21. How are your waterworks? (Waterworks means urinary).
22. How are your bowel habits?
23. Any bleeding from anywhere?
24. Any pain?
25. Do you feel weak?
26. How is your concentration?
27. /Do a quick summary./ @@html:<span class="ja"><i>簡単なまとめをしてください。</i></span>@@
28. Do ICE.
29. Then, do the rest of the history (past medical, past surgical, etc.)
