#+TITLE: History 003

#+BEGIN_EXPORT html
<div class="engt">History</div>
<div class="japt">病歴聴取</div>
<div class="engt">Page 003</div>
#+END_EXPORT

[[https://github.com/ahisu6/ahisu6.github.io/edit/main/src/h/003.org][Edit]]

[[file:./index.org][Home]]

[[file:./002.org][<< Previous page]] - [[file:./004.org][Next page >>]]

-----

#+TOC: headlines 2

* Neurology
:PROPERTIES:
:CUSTOM_ID: orgeeaa9d8
:END:

Posted: 2024-03-06 | Updated: 2024-03-06

Here is the [[https://drive.google.com/uc?export=view&id=1-yr808gQoPAphcVsRXU8Uv0T-jjQfBMf][picture]]:
- @@html:Do 1. DOP@@
- @@html:This is a <mark>2. cog (cognitive symptoms) 歯車</mark> wheel that is spinning and feeling <mark>3. dizzy (dizziness)</mark>.@@
- @@html:The cog wheel felt very dizzy and it has <mark>4. lost its balance (losing balance)</mark> and so it <mark>5. fell (any falls?)</mark> through a glass window and into a museum.@@
- @@html:It has fallen through museum roof. The museum had many <mark>6. sculptures that have weird body postures (abnormal muscle movements) 奇妙な姿勢の彫刻</mark>. The sculptures <mark>7. looked spiky (sensation) 彫刻がトゲトゲに見えた</mark>.@@
- @@html:The cog wheel <mark>8. tried to lift the sculpture, but it was soooo weak (weakness)</mark>. The cog wheel <mark>9. spinal disc slipped and caused a lot of pain (pain)</mark>.@@
- @@html:The cog wheel was very angry and <mark>10. tried to eat the sculptures (5 senses: taste, smell, hearing, touch, seeing)</mark>, but the sculptures was too big and spikey... so it was <mark>11. difficult to swallow (dysphagia)</mark>.@@
- @@html:Oh no! The <mark>12. cog wheel cannot talk (speech)<mark> anymore! So, it <mark>13. drank urine (urinary symptoms: incontence, difficulty passing urine)</mark> because urine helps with speech... ew...@@
- @@html:The urine drink made the cog wheel get <mark>14. diarrhoea (bowel symptoms: incontinence, numb around the anus)<mark>.@@

* Urology
:PROPERTIES:
:CUSTOM_ID: org14cc3e3
:END:

Posted: 2024-02-13 | Updated: 2024-02-13

In urology, there are a couple of possible symptoms that patients might have:
- Haematuria
- Dysuria
- Polyuria
- Urethral discharge
- Urgency

Here is a [[https://drive.google.com/uc?export=view&id=1l8-uVy31-iD7duS57OoPkA5oaxKJS1cU][picture]] to help you remember the important questions:
- @@html:<span class="ja">Once upon a time, <mark>Socrates</mark> was <mark>travelling through a stream</mark>, using a <mark>boat</mark>. 昔々、<mark>ソクラテス</mark>は<mark>小舟</mark>で<mark>小川</mark>を旅していた。</span>@@
  - SOCRATES, urinary stream (小川), blood at which point along stream (小舟)
- @@html:<span class="ja">He had a <mark>big bag of coins</mark> that were <mark>running through an hourglass</mark>, this helped Socrates keep track of time. 彼は<mark>砂時計の中</mark>を走っていた<mark>コインの大きな袋</mark>を持っていた、これはソクラテスが時間を追跡するのに役立ちました。</span>@@
  - amount of blood (コインの大きな袋), time taken to empty bladder (砂時計の中)
- @@html:<span class="ja">Socrates came to a dam that was <mark>blocked by clots, many clots</mark>. The dam looked like it was in <mark>great pain</mark> ソクラテスは、<mark>血の塊</mark>（<mark>多くの血の塊</mark>）で塞がれたダムにやってきた。ダムは大きな<mark>痛み</mark>に苦しんでいるように見えた。</span>@@
  - clot (血の塊), frequency (多くの血の塊), pain (痛み)
- @@html:<span class="ja">After a short while, the dam started to <mark>bruise</mark> until it <mark>broke open</mark>. That <mark>dam was not in a great shape</mark>. しばらくすると、ダムは<mark>決壊する</mark>まで<mark>傷つき</mark>始めた。その<mark>ダムはあまりいい状態ではなかった</mark>。</span>@@
  - bruise (傷つき), trauma (決壊する), constitutional (ダムはあまりいい状態ではなかった)

Now, we need to ask questions about these things:
1. Good morning, my name is Dr. XYZ. Can I get your name and date of birth please? @@html:<span class="ja">おはようございます、私はドクターXYZと申します。あなたのお名前と生年月日をお聞かせください。</span>@@
2. Thank you for coming today. @@html:<span class="ja">本日はご来場いただきありがとうございました。</span>@@
3. How can I help you?
4. /Give the patient some time to explain./ @@html:<span class="ja"><i>患者さんに説明する時間を与えてください。</i></span>@@
5. Right, so you have been experiencing some issues with your waterworks (Waterworks means urinary). Would it be okay if I ask you some more questions? Everything you say will be confidential. @@html:<span class="ja">そうですか、水道（水道は泌尿器の意味）に問題があるのですね。もう少し質問してもいいですか？おっしゃることはすべて秘密厳守です。</span>@@
6. Can you describe the issue for me? @@html:<span class="ja">この問題について説明してもらえますか？</span>@@
7. /Give the patient some time to explain./ @@html:<span class="ja"><i>患者さんに説明する時間を与えてください。</i></span>@@
8. Do DOP: How long have you had this for? When did it start? How did it start? Is it getting worse? @@html:<span class="ja">DOP：いつからですか？いつからですか？どのように始まりましたか？悪化していますか？</span>@@
9. Now, I would like to ask you some specific questions if that is okay. @@html:<span class="ja">では、いくつか具体的な質問をしたいのですが、よろしいですか？</span>@@
10. Do you have any difficulty with passing urine? @@html:<span class="ja">尿が出にくいことはありますか？</span>@@
11. Do you have any blood in urine? If the patient says "yes" then ask these questions @@html:<span class="ja">尿に血液は混じっていますか？もし患者が「はい」と答えたら、次のような質問をします</span>@@:
    1. I am sorry to hear that. It must be quite distressing. (You can do ICE here!). @@html:<span class="ja">お気の毒です。とてもつらいことでしょう。(ICEはここでできます！）。</span>@@
    2. What colour is it? @@html:<span class="ja">色は？</span>@@
    3. Does the blood come at the start, middle, or the end of the stream? @@html:<span class="ja">血は流れの最初、真ん中、それとも最後？</span>@@
    4. Are there any clots? @@html:<span class="ja">血栓はありますか？</span>@@
12. How often are you going to the toilet during the day? @@html:<span class="ja">日中、どのくらいの頻度でトイレに行きますか？</span>@@
13. How often are you going to the toilet during the night? @@html:<span class="ja">夜間のトイレの回数は？</span>@@
14. Does it take a long time to empty your bladder? @@html:<span class="ja">膀胱を空にするのに時間がかかりますか？</span>@@
15. Is there any pain? If the patient says "yes" then ask these questions @@html:<span class="ja">痛みはありますか？もし患者が「はい」と答えたら、次のような質問をします</span>@@:
    1. Do SOCRATES
16. Have you noticed any bruising anywhere? @@html:<span class="ja">どこかにあざはありましたか？</span>@@
17. Have you had any physical trauma? @@html:<span class="ja">身体的なトラウマはありますか？</span>@@
18. Have you been sick recently? @@html:<span class="ja">最近体調を崩されましたか？</span>@@
19. Have you had fever? @@html:<span class="ja">熱がありましたか？</span>@@
20. Have you had night sweats? @@html:<span class="ja">寝汗をかいたことはありますか？</span>@@
21. Have you noticed any weight changes? @@html:<span class="ja">体重に変化はありましたか？</span>@@
22. Are you eating and drinking well? @@html:<span class="ja">よく食べ、よく飲んでいるか？</span>@@
23. Are you sleeping well? @@html:<span class="ja">よく眠れていますか？</span>@@
24. /Do a quick summary./ @@html:<span class="ja"><i>簡単なまとめをしてください。</i></span>@@
25. Do ICE.
26. Then, do the rest of the history (past medical, past surgical, etc.)

* Tired all the time
:PROPERTIES:
:CUSTOM_ID: org71232d0
:END:

Posted: 2023-10-08 | Updated: 2023-10-08

Many things can cause tiredness and fatigue:
- Cancer
- Depression
- Thyroid issues
- Diabetes
- Infection
- Sleep issues
- And many more!

Anyway, here is what you should ask:
1. Good morning, my name is Dr. XYZ. Can I get your name and date of birth please? @@html:<span class="ja">おはようございます、私はドクターXYZと申します。あなたのお名前と生年月日をお聞かせください。</span>@@
2. Thank you for coming today. @@html:<span class="ja">本日はご来場いただきありがとうございました。</span>@@
3. How can I help you?
4. Right, so you have been experiencing some tiredness. Can you tell me a little bit more about that?
5. /Give the patient some time to explain./ @@html:<span class="ja"><i>患者さんに説明する時間を与えてください。</i></span>@@
6. I will just do a quick summary of what you have told me so far.
7. /Do a quick summary./ @@html:<span class="ja"><i>簡単なまとめをしてください。</i></span>@@
8. So, how long have you been feeling tired for?
9. When did it start?
10. Has it become better or worse?
11. Is there a particular time of day where you feel most tired?
12. Does anything make it worse?
13. Do you have any ideas, concerns, and expectations?
14. Is it okay if I ask you few more questions?
15. How is your appetite?
16. How is your mood?
17. How is your sleep?
18. Have you had any recent infections?
19. Have you noticed weight changes?
20. Do you feel cold when others think it's warm? (you are checking for hypothyroidism).
21. How are your waterworks? (Waterworks means urinary).
22. How are your bowel habits?
23. Any bleeding from anywhere?
24. Any pain?
25. Do you feel weak?
26. How is your concentration?
27. /Do a quick summary./ @@html:<span class="ja"><i>簡単なまとめをしてください。</i></span>@@
28. Do ICE.
29. Then, do the rest of the history (past medical, past surgical, etc.)
