#+TITLE: Surgery 001

#+BEGIN_EXPORT html
<div class="engt">Surgery</div>
<div class="japt">外科学</div>
<div class="engt">Page 001</div>
#+END_EXPORT

[[https://github.com/ahisu6/ahisu6.github.io/edit/main/src/s/001.org][Edit]]

[[file:./index.org][Home]]

[[file:./002.org][Next page >>]]

-----

#+TOC: headlines 2

* Small bowel obstruction
:PROPERTIES:
:CUSTOM_ID: org8d8b05d
:END:

Posted: 2023-07-25 | Updated: 2023-07-25

This is when the small intestines become blocked. @@html:<span class="ja">これは小腸が詰まった状態である。</span>@@

Usually, the most common reason for this is adhesions from a surgery. The adhesions will cause the small intestines to become blocked. @@html:<span class="ja">通常、最も一般的な原因は手術による癒着である。癒着によって小腸がふさがれてしまうのです。</span>@@

** Signs and symptoms
:PROPERTIES:
:CUSTOM_ID: orgfcc6cf6
:END:

- A lot of nausea and vomiting. This is because food cannot go past the obstruction. So, the patient will vomit all of the food. @@html:<span class="ja">吐き気や嘔吐が多い。これは、食物が閉塞部を通過できないためである。そのため、患者は食べ物をすべて吐いてしまいます。</span>@@
- Pain. Soooo much pain. @@html:<span class="ja">いたみ～</span>@@
- Constipation. The patient will not be able to fart or poop. @@html:<span class="ja">便秘。患者はおならやウンチができなくなる。</span>@@
- All the gas inside the intestine will cause the tummy to be distended. @@html:<span class="ja">腸内のガスが腹部を膨張させる。</span>@@
- The gas inside the intestines will start to play music... so, when you listen to the tummy, you will hear tinkling sounds. @@html:<span class="ja">腸内のガスが音楽を奏で始める...だから、おなかの音を聞くと、チリンチリンと音がする。</span>@@

** Investigations
:PROPERTIES:
:CUSTOM_ID: org8c3ea16
:END:

- First-line is x-ray. This will show the small bowel that looks like a spring. Look at this [[https://drive.google.com/uc?export=view&id=1bRZ25BiXQYYkf7gMLZXauq15He4G_Lnr][picture]]. It looks like a spring, right? Look at this [[https://drive.google.com/uc?export=view&id=1gWC0MG4raTlcXpJ729PPRRsttUpFnR-l][picture]] of a spring. @@html:<span class="ja">第一選択はレントゲンだ。バネのような小腸が映し出される。バネのように見えるでしょ？</span>@@
- On the x-ray, the small bowel will be in the centre of the tummy. @@html:<span class="ja">レントゲンでは、小腸はおなかの中心にあります。</span>@@
- CT will be the definitive investigation because it is very good. @@html:<span class="ja">CTは非常に優れているので、決定的な調査になるだろう。</span>@@

** Treatment
:PROPERTIES:
:CUSTOM_ID: orgf7b6727
:END:

- Stop giving the patient good. So, make the patient nil-by-mouth. This is because if you give the patient food, they will keep vomiting. So, the solution is to stop feeding the patient. @@html:<span class="ja">患者に良いものを与えるのをやめる。だから、患者に口から何も与えないようにする。患者に食べ物を与えると、嘔吐を繰り返すからだ。だから、解決策は患者に食べ物を与えるのをやめることだ。</span>@@
- Give the patient a lot of fluids. This is because the patient was vomiting a lot. @@html:<span class="ja">患者に大量の水分を与える。これは、患者が大量に嘔吐したためである。</span>@@
- Next, put a nasogastric tube into the patient. This will reduce the pressure in the intestines. @@html:<span class="ja">次に経鼻胃管を患者に入れる。これで腸内の圧力が下がる。</span>@@

* Acute pancreatitis
:PROPERTIES:
:CUSTOM_ID: org55d1751
:END:

Posted: 2023-07-25 | Updated: 2023-07-25

This is the inflammation of the pancreas. @@html:<span class="ja">これは膵臓の炎症である。</span>@@

Many things can cause this. @@html:<span class="ja">いろいろなことが原因になっている。</span>@@

But, the ones you need to pay attention to are @@html:<span class="ja">しかし、注意しなければならないのは以下の通りである</span>@@:
- Gallstones
- Alcohol
- ERCP

In pancreatitis, if the patient has low calcium level, then this is reaaaaaaaaaaaally really really bad. Remember, low calcium is bad! @@html:<span class="ja">膵炎の場合、患者がカルシウム値が低ければ、これは本当に、本当に、本当に悪いことだ。カルシウムが低いことは悪いことなのだ！</span>@@

Also, sometimes you might do ABG. If the patient has a really low level of oxygen (less than 8 kPa), then this is also really bad. @@html:<span class="ja">また、ABGを行うこともあります。患者の酸素濃度が本当に低い（8kPa以下）場合は、これも本当に悪い。</span>@@

** Signs and symptoms
:PROPERTIES:
:CUSTOM_ID: org0080c1d
:END:

- Epigastric pain that goes to the back.
- Vomit.

** Investigations
:PROPERTIES:
:CUSTOM_ID: orgc7ab5d3
:END:

- You need to do amylase test. @@html:<span class="ja">アミラーゼ検査が必要だ。</span>@@
- @@html:If the patient has presented late, then you need to do lipase. So, if the patient has presented 24 hours after the pain started, then you need to do lipase. Remember, <mark>L</mark>ipase is for <mark>L</mark>ate presentation. <span class="ja">患者の来院が遅ければ、リパーゼを行う必要がある。痛みが始まってから24時間後に来院した患者さんには、リパーゼの血液検査が必要です。</span>@@
- You can do ultrasound to see the cause of the pancreatitis. @@html:<span class="ja">超音波検査で膵炎の原因を調べることができます。</span>@@

** Treatment
:PROPERTIES:
:CUSTOM_ID: orgc49ac0c
:END:

- Give the patient a lot of fluids. @@html:<span class="ja">患者に大量の水分を与える。</span>@@
- Give the patient... more fluid. @@html:<span class="ja">患者に水分を多めに与える。</span>@@
- And... now you should give the patient even more fluid. @@html:<span class="ja">今なら、患者にさらに水分を与えるべきだ。</span>@@
- Also, give the patient some pain killers. @@html:<span class="ja">また、患者に鎮痛剤を与える。</span>@@

** Complications
:PROPERTIES:
:CUSTOM_ID: orgfd520b0
:END:

- Pseudocyst. Look at this [[https://drive.google.com/uc?export=view&id=1TLqcd5l9EAA09ITeljkQZIxBCZw_tvVV][picture]]:
  - In acute pancreatitis, fluid might start to form around the pancreas. @@html:<span class="ja">急性膵炎では、膵臓の周りに液体が形成され始めるかもしれない。</span>@@
  - This fluid might develop into something called pseudocyst. @@html:<span class="ja">この液体は仮性嚢胞と呼ばれるものに発展するかもしれない。</span>@@
  - The pseudocyst might happen 4 weeks after the acute pancreatitis. @@html:<span class="ja">仮性嚢胞は急性膵炎の4週間後に起こるかもしれない。</span>@@
  - The pseudocyst will squish the stomach, and it will cause the patient to feel full. @@html:<span class="ja">仮性嚢胞は胃を押し潰し、患者に満腹感を与える。</span>@@
  - The pseudocyst might squish the bile duct. This will make the patient get jaundice. @@html:<span class="ja">仮性嚢胞が胆管を押しつぶすかもしれない。こうなると患者は黄疸を起こす。</span>@@
  - The pseudocyst will make the amylase increase. @@html:<span class="ja">仮性嚢胞はアミラーゼを増加させる。</span>@@
  - Finally, the pseudocyst might stay there for about 12 weeks. @@html:<span class="ja">最終的には、仮性嚢胞は約12週間そこにとどまるかもしれない。</span>@@
- Bleeding:
  - The pancreas might start bleeding. @@html:<span class="ja">膵臓から出血が始まるかもしれない。</span>@@
  - This will cause the patient to have bruises. @@html:<span class="ja">そのため、患者にあざができる。</span>@@
  - There are two types of bruises that patients get in acute pancreatitis. @@html:<span class="ja">急性膵炎で生じる打撲には2種類ある。</span>@@
  - The first type is called Grey Turner's. This is bruising around the side of the tummy. Look at this [[https://drive.google.com/uc?export=view&id=1iclu12GecyqVN8W6ERFFNEDKDX_HKsRe][picture]]. @@html:<span class="ja">最初のタイプはグレー・ターナーと呼ばれるものです。これはおなかの横あたりにあざができるものです。</span>@@
  - The second type is called Cullen's. This happens in the centre of the tummy (around the belly button). Look at this [[https://drive.google.com/uc?export=view&id=1w66MnYuMuYc6ZcGOAB94QUAHu7OlABqi][picture]]. @@html:Remember, <mark>C</mark>ullen is <mark>C</mark>entral. <span class="ja">二つ目のタイプはカレン型と呼ばれるものです。これはおなかの中心（おへそのあたり）に起こります。</span>@@

* Colorectal cancer
:PROPERTIES:
:CUSTOM_ID: orgb145d38
:END:

Posted: 2023-07-23 | Updated: 2023-07-23

This is the cancer of the colon and the rectum. @@html:<span class="ja">これは結腸と直腸の癌である。</span>@@

We do screening in the UK. It is called "Faecal Immunochemical Test (FIT)" screening. This is done every 2 years. @@html:<span class="ja">英国ではスクリーニングを行っています。これは「Faecal Immunochemical Test（FIT）」スクリーニングと呼ばれています。これは2年ごとに行われます。</span>@@

There are some referral guidelines that you need to know @@html:<span class="ja">知っておくべき紹介のガイドラインがいくつかある</span>@@:
1. Patient over 40 years old and has weight loss plus tummy pain. @@html:<span class="ja">患者は40歳以上で、体重減少とおなかの痛みがある。</span>@@
2. Patient over 50 years old and has rectal bleeding. @@html:<span class="ja">50歳以上で直腸出血のある患者。</span>@@
3. Patient over 60 years old and has iron deficiency anaemia OR change in bowel habit. @@html:<span class="ja">60歳以上で鉄欠乏性貧血があるか、または腸の習慣に変化がある患者。</span>@@

There are three types of colorectal cancer @@html:<span class="ja">大腸がんには3つのタイプがある</span>@@:
- Sporadic: this is the most common. This happens randomly in people. @@html:<span class="ja">散発性がん：これが最も一般的である。これは人にランダムに起こる。</span>@@
- Hereditary non-polyposis colorectal carcinoma: this is also called Lynch syndrome. This is inherited from parents. It is autosomal dominant condition. This also increases risk of /endometrial/ cancer. @@html:<span class="ja">これはリンチ症候群とも呼ばれる。これは両親から遺伝する。常染色体優性遺伝である。これも子宮内膜がんのリスクを増加させる。</span>@@
- Familial adenomatous polyposis: this one is rare. Basically, in here, the patient will get hundreds of polyps in the colorectal area. It is caused by a mutation in a gene called APC. @@html:<span class="ja">こちらはまれです。基本的には、大腸領域に数百のポリープができます。APCと呼ばれる遺伝子の突然変異が原因です。</span>@@

** Signs and symptoms
:PROPERTIES:
:CUSTOM_ID: org3e10903
:END:

- Rectal bleeding.
- Tummy pain.
- Weight loss.
- Iron deficiency anaemia.

** Investigations
:PROPERTIES:
:CUSTOM_ID: org6db8351
:END:

- As we said before, there is FIT screening. @@html:<span class="ja">前にも言ったように、FIT検査がある。</span>@@
- We do colonoscopy to take samples and view them under the microscope. @@html:<span class="ja">私たちは大腸内視鏡検査でサンプルを採取し、顕微鏡で観察します。</span>@@
- When we diagnose the patient with colorectal cancer, we have to do CT scan of the chest, abdomen, and pelvis. This is because we need to check if the cancer has spread. @@html:<span class="ja">大腸癌と診断した場合、胸部、腹部、骨盤のCTスキャンを行わなければならない。これは、癌が広がっているかどうかをチェックする必要があるからです。</span>@@

** Treatment
:PROPERTIES:
:CUSTOM_ID: org332edc9
:END:

Before we look at the treatments, you need to understand the stomas. @@html:<span class="ja">治療法を見る前に、ストーマについて理解する必要がある。</span>@@

A stoma is a small opening made on the abdomen. This allows poop to exit the body. It is made surgically and can be either temporary or permanent. @@html:<span class="ja">ストーマは腹部に作られた小さな開口部である。これによってウンチを体外に出すことができる。ストーマは外科的に造られ、一時的なものと永続的なものがある。</span>@@

Stoma means "mouth" in Greek language. @@html:<span class="ja">ストーマとはギリシャ語で「口」を意味する。えーーーーーと...。</span>@@

There are two types of stomas. Look at this [[https://drive.google.com/uc?export=view&id=1n8BFFRLKlRLPzaYDA92d0OAY5rn5NzRD][picture]] @@html:<span class="ja">ストーマには2種類ある</span>@@:
1. Colostomy
2. Ileostomy

Let's first talk about colostomy @@html:<span class="ja">まず人工肛門について話そう</span>@@:
- In colostomy, we use the large bowel. Look at the name: it has "colo". This means we use the colon. @@html:<span class="ja">人工肛門では大腸を使います。名前を見てください。「colo」がついています。これは大腸を使うという意味です。</span>@@
- You can find this on the left side of the tummy. Look at this [[https://drive.google.com/uc?export=view&id=1n8BFFRLKlRLPzaYDA92d0OAY5rn5NzRD][picture]]. @@html:<span class="ja">おなかの左側にある。</span>@@
- This acts like the anus. @@html:<span class="ja">これは肛門のような役割を果たす。</span>@@
- The content of this is solid poop. @@html:<span class="ja">その内容はしっかりしたウンコだ。</span>@@
- There is end-colostomy. This is when the rectum and the colon are removed. If you remove the rectum, then the patient will not be able to poop. So, we should give them an end-colostomy. @@html:<span class="ja">エンドコロストミーがある。直腸と結腸を切除する場合です。直腸を切除すると、患者はウンチができなくなります。ですから、終末結腸瘻を造設します。</span>@@
- There is also loop-colostomy. Sometimes, you want to protect the rectum. For example, if you do a small surgery in the rectum, then you want to protect it from damage. So, you do something called loop-colostomy. Look at this [[https://drive.google.com/uc?export=view&id=1B7ETRjal8F2c9JFuwuE2iG5wOFhRIS26][picture]]. @@html:<span class="ja">ループコロストミーもある。直腸を保護したい場合もあります。例えば、直腸で小さな手術をする場合、直腸を損傷から守りたい。そこで、ループコロストミーと呼ばれる手術を行います。</span>@@

Now, let's talk about ileostomy @@html:<span class="ja">では、イレオストミーについて話そう</span>@@:
- In ileostomy, we use the small bowel. Look at the name: it has "ileo". This means we use the ilium (small bowel). @@html:<span class="ja">イレオストミーでは小腸を使う。名前を見てください。「ileo」がついています。これは腸骨（小腸）を使うという意味です。</span>@@
- You can find this on the right side of the tummy. Look at this [[https://drive.google.com/uc?export=view&id=1n8BFFRLKlRLPzaYDA92d0OAY5rn5NzRD][picture]]. @@html:<span class="ja">おなかの右側にある。</span>@@
- The content of the stoma is usually liquid. @@html:<span class="ja">ストーマの内容物は通常液体である。</span>@@
- The content can irritate the skin. So, we do something called a "spout". The spout will protect the skin. Look at this [[https://drive.google.com/uc?export=view&id=1niCr2a-npBEL-TGTET4unio_GxPkxOW8][picture]]. @@html:<span class="ja">中身が皮膚を刺激することもある。そこで、「スパウト」と呼ばれるものを使用する。注ぎ口は皮膚を保護する。</span>@@
- Again, there is end-ileostomy and loop-ileostomy. These have the same reasons as the colostomies. @@html:<span class="ja">ここでも、終末人工肛門とループ人工肛門がある。これらは人工肛門と同じ理由である。</span>@@

Look at this table:
| Type | Reason                                                                                                                                             |
|------+----------------------------------------------------------------------------------------------------------------------------------------------------|
| Loop | This is used to protect the rest of bowel. @@html:<span class="ja">これは腸の残りの部分を保護するために使用される。</span>@@                       |
| End  | This is used when you remove a large section of the bowel. @@html:<span class="ja">これは、腸の大部分を永久的に切除する場合に使用される。</span>@@ |

The surgery depends on the site of the cancer. There are different types of surgeries. Look at this [[https://drive.google.com/uc?export=view&id=1fBSVmHJpXQZdW0wKlNOWqY0ASC16wbpv][picture]]. @@html:<span class="ja">手術はがんの部位によって異なります。手術にはさまざまな種類があります。</span>@@

In an emergency situation, we do something called Hartmann's procedure. In this procedure, they remove the /sigmoid colon/ and they create an /end-colostomy/ (this is because we removed the rectum forever). @@html:<span class="ja">緊急時には、ハルトマン手術というものを行います。この手術ではS状結腸を切除し、終末結腸瘻を造設します（これは直腸を永遠に切除したためです）。</span>@@

Look at this table and look at this [[https://drive.google.com/uc?export=view&id=17pC_LDsnAXRTid6pq4M8YF6hbti_n-NQ][picture]]:
| Site of the cancer                           | Type of surgery                      |
|----------------------------------------------+--------------------------------------|
| Emergency surgery                            | Hartmann's procedure                 |
| Caecum, ascending, proximal transverse colon | Right hemicolectomy                  |
| Distal transverse, descending colon          | Left hemicolectomy                   |
| Sigmoid colon                                | High anterior resection              |
| Rectum                                       | Anterior resection                   |
| Anus                                         | Abdomino-perineal excision of rectum |
