#+TITLE: Surgery 002

#+BEGIN_EXPORT html
<div class="engt">Surgery</div>
<div class="japt">外科学</div>
<div class="engt">Page 002</div>
#+END_EXPORT

[[https://github.com/ahisu6/ahisu6.github.io/edit/main/src/s/002.org][Edit]]

[[file:./index.org][Home]]

[[file:./001.org][<< Previous page]] - [[file:./003.org][Next page >>]]

-----

#+TOC: headlines 2

* Gastric cancer
:PROPERTIES:
:CUSTOM_ID: org9afa15b
:END:

Posted: 2023-07-29 | Updated: 2023-07-29

This is the cancer of the stomach. @@html:<span class="ja">これは胃の癌である。</span>@@

The main risk factor for this gastric cancer is h. pylori infection. @@html:<span class="ja">この胃がんの主な危険因子はピロリ菌感染である。</span>@@

So, if you get a lot of stomach ulcers that have h. pylori, then your chance of gastric cancer increases. This is because of the inflammation. @@html:<span class="ja">つまり、ピロリ菌がいる胃潰瘍がたくさんできると、胃がんになる可能性が高くなるのです。これは炎症のためです。</span>@@

** Signs and symptoms
:PROPERTIES:
:CUSTOM_ID: orgd303460
:END:

- Epigastric pain.
- weight loss.
- Nausea and vomiting.
- Lymph node in the left supraclavicular fossa becomes big (this is called Virchow's node). @@html:<span class="ja">左鎖骨上窩のリンパ節が大きくなる（これをVirchow結節という。）</span>@@
- Lymph node next to the belly button becomes big (this is called Sister Mary Joseph's node). @@html:<span class="ja">おへその横のリンパ節が大きくなる（これはシスター・マリア・ヨーゼフ結節と呼ばれる）。</span>@@

** Investigations
:PROPERTIES:
:CUSTOM_ID: org2f1d024
:END:

- First, you need to do oesophago-gastro-duodenoscopy (OGD) with biopsy. This is a tube that goes in the mouth and to the stomach. @@html:<span class="ja">まず、生検を伴う食道-胃-十二指腸内視鏡検査（OGD）を行う必要があります。これは口から胃に管を通すものです。</span>@@
  - When you do histology, you will see something called signet ring cells. @@html:<span class="ja">組織検査をすると、シグネットリング細胞と呼ばれるものが見られる。</span>@@
- After you diagnose gastric cancer, we have to do CT scan of the chest, abdomen, and pelvis. This is because we need to check if the cancer has spread. @@html:<span class="ja">胃がんと診断されたら、胸部、腹部、骨盤のCTスキャンをしなければなりません。がんが広がっているかどうかを調べる必要があるからです。</span>@@

** Treatment
:PROPERTIES:
:CUSTOM_ID: org597b49f
:END:

- You need to do surgery to remove the cancer. @@html:<span class="ja">癌を取り除く手術が必要です。</span>@@
- Then, you need to give chemotherapy. @@html:<span class="ja">それから化学療法を行う必要がある。</span>@@

** Complications
:PROPERTIES:
:CUSTOM_ID: org866bf52
:END:

- Sometimes, the cancer can make the stomach perforate. This will make the stomach have a hole. This causes a lot of pain! @@html:<span class="ja">がんが胃に穴を開けることもある。胃に穴が開くのです。これは大きな痛みを引き起こします！</span>@@
- Sometimes, the gastric cancer can spread to the ovaries in women. This is called Krukenberg tumour. This is why we have to do the CT scan! @@html:<span class="ja">女性の場合、胃がんが卵巣に転移することがあります。これはクルーケンベルグ腫瘍と呼ばれます。だからCTスキャンをしなければならないのです！</span>@@

* Acute mesenteric ischaemia
:PROPERTIES:
:CUSTOM_ID: org04dab65
:END:

Posted: 2023-07-26 | Updated: 2023-07-26

Your intestines have a lot of arteries. These arteries give your intestines a lot of blood and oxygen. @@html:<span class="ja">腸にはたくさんの動脈がある。これらの動脈は腸に多くの血液と酸素を供給しています。</span>@@

The intestines are wrapped in something called mesentery. Look at this [[https://drive.google.com/uc?export=view&id=13yA8QIxCtbDdeC6HWo8qwwhHcNnehbaE][picture]]. @@html:<span class="ja">腸は腸間膜というものに包まれている。</span>@@

The mesentery takes the arteries from the aorta to the intestines. @@html:<span class="ja">腸間膜は大動脈から腸まで動脈を取り込んでいる。</span>@@

Sometimes, a blood clot travels and blocks an artery that is in the mesentery. This is called acute mesenteric ischaemia. @@html:<span class="ja">血栓が腸間膜の動脈を塞いでしまうことがある。これを急性腸間膜虚血という。</span>@@

So, usually, people who have atrial fibrillation will get acute mesenteric ischaemia. This is becausse atrial fibrillation increases the chance of a blood clot. @@html:<span class="ja">心房細動のある人は急性腸間膜虚血になることが多い。心房細動があると血栓ができやすくなるからである。</span>@@

Acute mesenteric ischaemia means:
- Acute: this word means that it the disease happens suddenly and very quickly. @@html:<span class="ja">この言葉は、病気が突然、非常に早く起こることを意味する。</span>@@
- Mesenteric: this is a word that we use to describe the mesentery. @@html:<span class="ja">これは腸間膜を表す言葉だ。</span>@@
- Ischaemia: this word means that there is not enough blood. @@html:<span class="ja">この言葉は血液が足りないことを意味する。</span>@@

Acute mesenteric ischaemia is similar to a heart attack... it is an instestine attack! @@html:<span class="ja">急性腸間膜虚血は心臓発作に似ている... 腸の発作である！</span>@@

** Signs and symptoms
:PROPERTIES:
:CUSTOM_ID: org240853c
:END:

- Sudden tummy pain. @@html:<span class="ja">いたみ...。</span>@@
- Very, very, very, very painful. @@html:<span class="ja">とてもいたみ～。</span>@@
- It is reaaaaaaaaaaaaaaaaaaaaaally painful. @@html:<span class="ja">本当にいたみです。</span>@@
- A looooooooooooooooooooooot of pain. @@html:<span class="ja">いたみ、いたみ、いたみ、いたみ、いたみ、いたみ。</span>@@
- Sooooooooooooooooo much paaaaaaaaaaain. @@html:<span class="ja">あ～、いたみ～～～～。</span>@@

** Investigations
:PROPERTIES:
:CUSTOM_ID: org1588d31
:END:

- You need to do urgent CT scan of the abdomen. @@html:<span class="ja">緊急の腹部CTスキャンが必要です。</span>@@
- Quick! Go and do a CT scan! @@html:<span class="ja">急げ CTスキャンを撮ってきてください！</span>@@
- There will be a very high level of lactate. This is because the intestine is not getting oxygen. The intestine is dying!!! @@html:<span class="ja">乳酸値が非常に高くなる。これは腸に酸素が供給されていないからだ。腸が死んでいるのだ！！！</span>@@

** Treatment
:PROPERTIES:
:CUSTOM_ID: orge2f3805
:END:

- Surgery. You need to do urgent laparotomy. @@html:<span class="ja">手術。緊急開腹手術が必要です。</span>@@
