#+TITLE: Clinical Pharmacology

#+BEGIN_EXPORT html
<div style="color: #8ffa89; background-color: transparent; font-weight: bolder; font-size: 2em; text-align: center;">Clinical Pharmacology</div>
<div style="color: #89b7fa; background-color: transparent; font-weight: bold; font-size: 2em; text-align: center;">臨床薬理学</div>
<div style="color: #8ffa89; background-color: transparent; font-weight: bolder; font-size: 1.5em; text-align: center;">Page 001</div>
#+END_EXPORT

[[https://github.com/ahisu6/ahisu6.github.io/edit/main/src/cp/001.org][Edit]]

[[file:./index.org][Home]]

[[file:./002.org][Next page]]

-----

#+TOC: headlines 2

* Metronidazole
:PROPERTIES:
:CUSTOM_ID: metronidazole
:END:

- Metronidazole. @@html:<span class="jp">メトロニダゾール。</span>@@
- Hmmmm. Metronidazole...
- /Metro/ nidazole...
- This sounds like a metro train!!! @@html:<span class="jp">これって、メトロの電車みたいですね！！！</span>@@
- Metro trains are soooooooo fast! @@html:<span class="jp">メトロの電車って速いんですねー！</span>@@
- Maybe this metro train was made in Japan? @@html:<span class="jp">もしかして、このメトロの車両は日本製？</span>@@
- Anyway... this metro train likes to run over different bacteria lol. @@html:<span class="jp">とにかく...このメトロの列車は、異質なバクテリアの上を走るのが好きなんです笑</span>@@
- Do /not/ give this to people who drink alcohol! It will interact with the alcohol!!!!!! @@html:<span class="jp">お酒を飲む人には与えないでください！アルコールと相互作用してしまいます！！！！！！</span>@@
  - You can't drive the metro train if you've had alcohol... Right? It's too dangerous! @@html:<span class="jp">飲んだらメトロは運転できない。。。そうだろ？危険すぎる！</span>@@

** Summary
:PROPERTIES:
:CUSTOM_ID: org2571d15
:END:

- Whenever you see metronidazole, think of a metro train! @@html:<span class="jp">メトロニダゾールを見たら、メトロの列車を思い浮かべるんだ！</span>@@
