#+TITLE: Clinical Pharmacology

#+BEGIN_EXPORT html
<div style="color: #8ffa89; background-color: transparent; font-weight: bolder; font-size: 2em; text-align: center;">Clinical Pharmacology</div>
<div style="color: #89b7fa; background-color: transparent; font-weight: bold; font-size: 2em; text-align: center;">臨床薬理学</div>
<div style="color: #8ffa89; background-color: transparent; font-weight: bolder; font-size: 1.5em; text-align: center;">Page 001</div>
#+END_EXPORT

[[https://github.com/ahisu6/ahisu6.github.io/edit/main/src/cp/001.org][Edit]]

[[file:./index.org][Home]]

[[file:./002.org][Next page]]

-----

#+TOC: headlines 2

* Mifepristone
:PROPERTIES:
:CUSTOM_ID: mifepristone
:END:

- Mifepristone. @@html:<span class="jp">ミフェプリストン。</span>@@
- @@html:<span class="jp">うーん。。。みふ？うーーーーん。。。みぷ？みっぷ？？？あ！！！！！密夫！！！</span>@@
  - This means "lover (of a married woman)", right?
  - So, basically, the married woman is cheating on her husband with an alien... @@html:<span class="jp">つまり、基本的に人妻は宇宙人と浮気をしている...ということですね。</span>@@
- This drug is used for abortion. @@html:<span class="jp">この薬は、中絶に使用されます。</span>@@
- Imagine a wife coming to her second husband @@html:<span class="jp">密夫</span>@@ (who is actually an alien) and she tells him that her baby is actually an alien, and therefore she is going to terminate the pregnancy. @@html:<span class="jp">ある妻が<mark>密夫</mark>(実は宇宙人)のところにやってきて、自分の赤ちゃんは実は宇宙人だから、妊娠を解消しようと思っている、と告げたとします。</span>@@

** Summary
:PROPERTIES:
:CUSTOM_ID: orgc223087
:END:

- Whenever you see mifepristone, remember that there is a woman who cheated on her husband with an alien. Then, she was pregnant, and her fetus was an alien. So, she wanted to have an abortion. @@html:<span class="jp">ミフェプリストンを見るたびに、宇宙人(その宇宙人は彼女の「<mark>密夫</mark>」だったのだ)と浮気をした女性がいることを思い出してください。そして、彼女は妊娠し、その胎児は宇宙人だったのです。それで、彼女は中絶を望んだ。</span>@@

* Clotrimazole
:PROPERTIES:
:CUSTOM_ID: clotrimazole
:END:

- Clotrimazole. @@html:<span class="jp">クロトリマゾール。</span>@@
- @@html:<span class="jp">うーん。。。クロ？くろ？？黒？？？</span>@@
  - This means "black", right?
- What about @@html:<span class="jp">トリ</span>@@?
- @@html:<span class="jp">うーん。。。トリ？とり？？鳥？？？</span>@@
  - This means "bird", right?
- So... let's combine "black" and "bird" to get @@html:<span class="jp">黒い鳥</span>@@...
- I know, I know... I added @@html:<span class="jp">い</span>@@ and this is cheating... but who cares!!!!

** Summary
:PROPERTIES:
:CUSTOM_ID: org53bba51
:END:

- Whenever you see clotrimazole, try to think of a black bird :) @@html:<span class="jp">黒い鳥</span>@@

* Fluconazole
:PROPERTIES:
:CUSTOM_ID: fluconazole
:END:

- Fluconazole. @@html:<span class="jp">フルコナゾール。</span>@@
- Furu... kona...... @@html:<span class="jp">フル。。。コナ。。。。。。</span>@@
- Furu? @@html:<span class="jp">フル？ふる？？古？？？</span>@@
  - This means "old", right? Hmmmm...
- What about the "kona"...? @@html:<span class="jp">「コナ」はどうでしょう。。。？</span>@@
- Wait a minute... Kona? Cona? Conan?!?! @@html:<span class="jp">ちょっと待てよ。。。コナ？コナ？コナンか？！？！</span>@@
- Okay... so now we have @@html:<span class="jp">古</span>@@ and @@html:<span class="jp">コナン</span>@@...
- Hmmmm... maybe something like @@html:<span class="jp">古いコナン</span>@@
- Poor Conan... he was always so small and young... @@html:<span class="jp">コナンくんがかわいそう。。。いつも小さくて幼かったから。。。</span>@@
- But not anymore!
- Conan is now 293 years old! @@html:<span class="jp">コナンが293歳に！</span>@@
- They grow up so fast :')
- Conan is a fun guy (haha get it? "Fun guy" sounds like the word "fungi")
  - Fluconazole kills fungus...

** Summary
:PROPERTIES:
:CUSTOM_ID: org6880fa2
:END:
- Here is a [[https://lh3.googleusercontent.com/pw/AMWts8A2KBYDuUweYUgGY-Nscj_6DWXEqUVMlLOvT7v2GduFXIrhkiwVEvsJFrjVROiQ4a6EH62TOOI2Ksp6gKKQBq23wP_rvPU5170HHS0dnV6N1wDcBTNT_CO7CUBzUwUasJ8B6nm6EvqK2kcukg0lN00_=s500-no?authuser=0][picture]]!
- Whenever you see fluconazole, think of @@html:<span class="jp">古いコナン</span>@@ doing something like arresting fungi... @@html:<span class="jp">フルコナゾールを見たら、古いコナンが真菌を捕まえるようなことをしていると思え。。。</span>@@
- Or maybe think of Conan being a fun guy... lol. @@html:<span class="jp">それとも、コナンが「fun guy」だと思えばいいのか。。。笑。</span>@@

* Metronidazole
:PROPERTIES:
:CUSTOM_ID: metronidazole
:END:

- Metronidazole. @@html:<span class="jp">メトロニダゾール。</span>@@
- Hmmmm. Metronidazole...
- /Metro/ nidazole...
- This sounds like a metro train!!! @@html:<span class="jp">これって、メトロの電車みたいですね！！！</span>@@
- Metro trains are soooooooo fast! @@html:<span class="jp">メトロの電車って速いんですねー！</span>@@
- Maybe this metro train was made in Japan? @@html:<span class="jp">もしかして、このメトロの車両は日本製？</span>@@
- Anyway... this metro train likes to run over different bacteria lol. @@html:<span class="jp">とにかく...このメトロの列車は、異質なバクテリアの上を走るのが好きなんです笑</span>@@
- Do /not/ give this to people who drink alcohol! It will interact with the alcohol!!!!!! @@html:<span class="jp">お酒を飲む人には与えないでください！アルコールと相互作用してしまいます！！！！！！</span>@@
  - You can't drive the metro train if you've had alcohol... Right? It's too dangerous! @@html:<span class="jp">飲んだらメトロは運転できない。。。そうだろ？危険すぎる！</span>@@

** Summary
:PROPERTIES:
:CUSTOM_ID: org2571d15
:END:

- Whenever you see metronidazole, think of a metro train! @@html:<span class="jp">メトロニダゾールを見たら、メトロの列車を思い浮かべるんだ！</span>@@
