#+TITLE: Clinical Pharmacology

#+BEGIN_EXPORT html
<div style="color: #8ffa89; background-color: transparent; font-weight: bolder; font-size: 2em; text-align: center;">Clinical Pharmacology</div>
<div style="color: #89b7fa; background-color: transparent; font-weight: bold; font-size: 2em; text-align: center;">臨床薬理学</div>
<div style="color: #8ffa89; background-color: transparent; font-weight: bolder; font-size: 1.5em; text-align: center;">Page 001</div>
#+END_EXPORT

[[https://github.com/ahisu6/ahisu6.github.io/edit/main/src/cp/001.org][Edit]]

[[file:./index.org][Home]]

[[file:./002.org][Next page]]

-----

#+TOC: headlines 2

* Fluconazole
:PROPERTIES:
:CUSTOM_ID: fluconazole
:END:

- Fluconazole. @@html:<span class="jp">フルコナゾール。</span>@@
- Furu... kona...... @@html:<span class="jp">フル。。。コナ。。。。。。</span>@@
- Furu? @@html:<span class="jp">フル？ふる？？古？？？</span>@@
  - This means "old", right? Hmmmm...
- What about the "kona"...? @@html:<span class="jp">「コナ」はどうでしょう。。。？</span>@@
- Wait a minute... Kona? Cona? Conan?!?! @@html:<span class="jp">ちょっと待てよ？コナ？コナ？コナンか？！？！</span>@@
- Okay... so now we have @@html:<span class="jp">古</span>@@ and @@html:<span class="jp">コナン</span>@@...
- Hmmmm... maybe something like @@html:<span class="jp">古めかしいコナン</span>@@
  - This is quite similar to @@html:<span class="jp">古コナン</span>@@...
  - Hmmmm... @@html:<span class="jp">ふるコナン</span>@@
- Poor Conan... he was always so small and young... @@html:<span class="jp">コナンくんがかわいそう。。。いつも小さくて幼かったから。。。</span>@@
- But not anymore!
- Conan is now 293 years old! @@html:<span class="jp">コナンが293歳に！</span>@@
- They grow up so fast :')
- Conan is a fun guy (haha get it? "Fun guy" sounds like the word "fungi")

** Summary
:PROPERTIES:
:CUSTOM_ID: org6880fa2
:END:

- Whenever you see fluconazole, think of @@html:<span class="jp">古めかしいコナン</span>@@ doing something like arresting fungi... @@html:<span class="jp">フルコナゾールを見たら、古のコナンが真菌を捕まえるようなことをしていると思え。。。</span>@@
- Or maybe think of Conan being a fun guy... lol. @@html:<span class="jp">それとも、コナンが「fun guy」だと思えばいいのか。。。笑。</span>@@

* Metronidazole
:PROPERTIES:
:CUSTOM_ID: metronidazole
:END:

- Metronidazole. @@html:<span class="jp">メトロニダゾール。</span>@@
- Hmmmm. Metronidazole...
- /Metro/ nidazole...
- This sounds like a metro train!!! @@html:<span class="jp">これって、メトロの電車みたいですね！！！</span>@@
- Metro trains are soooooooo fast! @@html:<span class="jp">メトロの電車って速いんですねー！</span>@@
- Maybe this metro train was made in Japan? @@html:<span class="jp">もしかして、このメトロの車両は日本製？</span>@@
- Anyway... this metro train likes to run over different bacteria lol. @@html:<span class="jp">とにかく...このメトロの列車は、異質なバクテリアの上を走るのが好きなんです笑</span>@@
- Do /not/ give this to people who drink alcohol! It will interact with the alcohol!!!!!! @@html:<span class="jp">お酒を飲む人には与えないでください！アルコールと相互作用してしまいます！！！！！！</span>@@
  - You can't drive the metro train if you've had alcohol... Right? It's too dangerous! @@html:<span class="jp">飲んだらメトロは運転できない。。。そうだろ？危険すぎる！</span>@@

** Summary
:PROPERTIES:
:CUSTOM_ID: org2571d15
:END:

- Whenever you see metronidazole, think of a metro train! @@html:<span class="jp">メトロニダゾールを見たら、メトロの列車を思い浮かべるんだ！</span>@@
