#+TITLE: Dermatology

#+BEGIN_EXPORT html
<div style="color: #8ffa89; background-color: transparent; font-weight: bolder; font-size: 2em; text-align: center;">Dermatology</div>
<div style="color: #89b7fa; background-color: transparent; font-weight: bold; font-size: 2em; text-align: center;">皮膚科学</div>
#+END_EXPORT

[[https://github.com/ahisu6/ahisu6.github.io/edit/main/src/d/001.org][Edit]]

[[file:./index.org][Home]]

[[file:./002.org][Next page]]

-----

#+TOC: headlines 1


* Basal cell carcinoma
:PROPERTIES:
:CUSTOM_ID: org0ed41ab
:END:

Posted: 2023-02-01 | Updated: 2023-02-01

This is a malignant tumour. @@html:<span class="jp">これは悪性の腫瘍です。</span>@@

It is not common for this type of cancer to spread. @@html:<span class="jp">このタイプのがんは、転移することはあまりありません。</span>@@

It grows /very slowly/. @@html:<span class="jp">成長がとても遅いのです。</span>@@

** Sign and symptoms
:PROPERTIES:
:CUSTOM_ID: org47157c6
:END:

- It does /not/ cause any pain. @@html:<span class="jp">痛みを感じることはありません。</span>@@
- You will find it on the skin which is exposed to the sunlight (so, usually the face). @@html:<span class="jp">日光にさらされる肌（つまり、通常は顔）にできます。</span>@@
- Pearly colour (like [[https://lh3.googleusercontent.com/pw/AMWts8C6lMxXfEcHHnGvH-AnCxv13iIej70xPhTUye7yKwpz0bvEGk_AnJcrWe93z_B8d90g1RkPvc3Gaai2fXPUKBO3hRbidi1gindzLZ_0o4TdO2mV_0-pkBpdk_fuWb9CxO8piNO4u8AFKlxg-CSgJDM=w640-h480-no?authuser=3][this]]).
- The border of the nodule will be rolled over and it will have an ulcer in the middle which does /not/ heal (like [[https://lh3.googleusercontent.com/pw/AMWts8Cdt6LvfmGDHbgl2Il0Ywz9lzpHtgpScvB0SX9TU9aXW1aanaOTX6LB2oJUt_pKBhUMyiV2tL2QPpU1hts-2NCC8X9VlDGcA719soxh7tFs2HsaOqpzliYTOK28kDTrn4p0FBCiFX4oh741LPewbww=w640-h480-no?authuser=3][this]]). @@html:<span class="jp">結節の境目が転がって、真ん中に潰瘍ができ、それが治らない。</span>@@

** Types
:PROPERTIES:
:CUSTOM_ID: orgb8a54e5
:END:

There are many types of basal cell carcinoma. @@html:<span class="jp">基底細胞癌には多くの種類があります。</span>@@

To be honest, you do /not/ need to know them. You can have a look at some photos [[https://dermnetnz.org/cme/lesions/basal-cell-carcinoma-cme][here]] (this is a very good website). This is just for your interest. I listed some of the unique ones below @@html:<span class="jp">正直なところ、あなたはそれらを知る必要はないでしょう。ここでいくつかの写真を見ることができます（これは非常に良いウェブサイトです）。これはあくまで興味本位です。以下にユニークなものをいくつか挙げてみました。</span>@@:
- Superficial. Look at [[https://lh3.googleusercontent.com/pw/AMWts8AuVbsaFxk4x28bZm-IYzniuxd6othiTeMabCuiWLSTr8x6LRd7F9F7q-eFElEDbiiAo4rytgV9D0Y7Tb3sMYlMURZpB_WqfG6QLiUkKizfFvsRVxab4yT3Osrj3lRKvIpeHXKX36HR36uDbEWKQ1g=w640-h480-no?authuser=3][this]].
- Nodular. Look at [[https://lh3.googleusercontent.com/pw/AMWts8C6lMxXfEcHHnGvH-AnCxv13iIej70xPhTUye7yKwpz0bvEGk_AnJcrWe93z_B8d90g1RkPvc3Gaai2fXPUKBO3hRbidi1gindzLZ_0o4TdO2mV_0-pkBpdk_fuWb9CxO8piNO4u8AFKlxg-CSgJDM=w640-h480-no?authuser=3][this]].
- Pigmented. Look at [[https://lh3.googleusercontent.com/pw/AMWts8AYM1VUemU8vgwEnOc8drDX9aMbgoKdhgb4Zjvuvg8SnSZ2rSnOBqpe6NCiE5QyXoe9nKSfD_pqIC4WXyDmEvVCoPJvbPnql-7WKXMluRHtnr2PFcCDW66uzMayxqHGL985kwCn3zc5JAFbWM690vM=w640-h480-no?authuser=3][this]].

** Risk factors
:PROPERTIES:
:CUSTOM_ID: org2275965
:END:

- Ultraviolet light exposure
- Albinism

** Treatment
:PROPERTIES:
:CUSTOM_ID: org76dc71a
:END:

- Surgical excision.
- If the cancer is low-risk, then you can use topical immunosuppressant drugs such as imiquimod and fluorouracil. @@html:<span class="jp">がんのリスクが低い場合は、イミキモドやフルオロウラシルなどの免疫抑制剤の外用薬を使用することができます。</span>@@

* Managing dermatological diseases
:PROPERTIES:
:CUSTOM_ID: orgfeecfe4
:END:

Posted: 2023-02-01 | Updated: 2023-02-01

When treating dermatological disease, it is important to consider what patients want and what they like. @@html:<span class="jp">皮膚科の病気の治療では、患者さんが何を求めているか、何が好きかを考えることが大切です。</span>@@

** Topical
:PROPERTIES:
:CUSTOM_ID: org4344e14
:END:

This is the most common type of treatment. @@html:<span class="jp">これが最も一般的な治療法です。</span>@@

There are many types of topical treatments. But, the main ones are @@html:<span class="jp">外用剤には多くの種類があります。しかし、主なものは</span>@@:
- Emollients:
  - Creams: this is can be used for dry skin conditions. But, they are usually used in /acute/ cases. You can use this to massage the place! @@html:<span class="jp">これは、乾燥肌の症状にも使用できます。しかし、通常は急性の場合に使用されます。これを使ってマッサージができるんです！</span>@@
  - Ointments: this is used for /dry/ skin conditions. It is more sticky than creams (this is why patients like to use creams instead of ointments).
- Topical glucocorticoids:
  - /Mild/ glucocorticoids are used in delicate areas. @@html:<span class="jp">デリケートな部分には軽度のグルココルチコイドを使用します。</span>@@
  - /Strong/ glucocorticoids are used when the disease is too complex/advanced. @@html:<span class="jp">強力なグルココルチコイドは、病気があまりに複雑／進行している場合に使用されます。</span>@@
  - Skin atrophy (when the skin becomes weak) is a common side effect of using topical glucocorticoids. @@html:<span class="jp">皮膚萎縮（皮膚が弱くなること）は、グルココルチコイド外用剤の使用でよく見られる副作用です。</span>@@
  - Here are some glucocorticoids @@html:<span class="jp">グルココルチコイドを紹介します</span>@@:
    - Mild: hydrocortisone 0.5%
    - Moderate: Eumovate
    - Potent: betamethasone

** Oral drugs
- Retinoids:
  - These are oral drugs. @@html:<span class="jp">これらは経口薬です。</span>@@
  - Retinoids are a type of drugs that is similar to vitamin A. @@html:<span class="jp">レチノイドは、ビタミンAに由来する点や、化学構造や機能の点で、同様の物質の種類を指す。</span>@@
  - Retinoids are used for diseases are acne and psoriasis. @@html:<span class="jp">レチノイドは、にきびや乾癬などの病気に使われます。</span>@@
  - Retinoids work by helping skin cells become specialised (this process is called "differentiation"). You can read more about "differentiation" on [[https://ja.wikipedia.org/wiki/%E5%88%86%E5%8C%96][Wikipedia]]. @@html:<span class="jp">レチノイドは、皮膚細胞が特殊化するのを助ける働きをします（このプロセスを「分化」と呼びます）。多細胞生物に於いて、個々の細胞が構造機能的に変化すること。</span>@@
  - Retinoids reduce inflammation. @@html:<span class="jp">レチノイドは炎症を抑える。</span>@@
- Immunosuppressants: these drugs make the immune system weak and they reduce inflammation. They are used in many diseases, including eczema! @@html:<span class="jp">これらの薬は免疫系を弱め、炎症を抑えます。湿疹をはじめ、多くの疾患に使用されています！</span>@@
