#+TITLE: Endocrinology 002

#+BEGIN_EXPORT html
<div class="engt">Endocrinology</div>
<div class="japt">内分泌学</div>
<div class="engt">Page 002</div>
#+END_EXPORT

[[https://github.com/ahisu6/ahisu6.github.io/edit/main/src/e/002.org][Edit]]

[[file:./index.org][Home]]

[[file:./001.org][<< Previous page]] - [[file:./003.org][Next page >>]]

-----

#+TOC: headlines 2

* Type 2 Diabetes Mellitus
:PROPERTIES:
:CUSTOM_ID: org82c832e
:END:

Posted: 2023-07-21 | Updated: 2023-07-21

This is a common condition. @@html:<span class="ja">これはよくある病気だ。</span>@@

Make sure you know the drugs used. @@html:<span class="ja">使用されている薬剤を確認してください。</span>@@

I drew some charts for you. Please have a look at them and let me know if you do not understand anything. @@html:<span class="ja">いくつかグラフを描いてみた。どうぞご覧になって、わからないことがあれば教えてください。</span>@@

** Signs and symptoms
:PROPERTIES:
:CUSTOM_ID: org07609a3
:END:

- Usually, there are no symptoms. @@html:<span class="ja">通常、症状はない。</span>@@
- Thirsty.
- Weight loss.
- Urinating a lot.

** Investigations
:PROPERTIES:
:CUSTOM_ID: org3c62abd
:END:

You can do HbA1c or you can check blood glucose. @@html:<span class="ja">あなたはHbA1cを調べることができるし、血糖値を調べることもできる。</span>@@

If the patient has symptoms and has a high blood glucose, then they are diagnosed with diabetes. @@html:<span class="ja">症状があり、血糖値が高ければ糖尿病と診断される。</span>@@

If the patient has a high blood glucose level, but they do not have symptoms, then you need to do another blood test. @@html:<span class="ja">血糖値が高くても症状がなければ、もう一度血液検査をする必要があります。</span>@@

| Blood level? | Symptoms? | Does patient have diabetes?            |
|--------------+-----------+----------------------------------------|
| High         | Yes       | Diabetes                               |
| High         | No        | Patient needs to repeat the blood test |

Let's talk about the first way. This is called blood glucose method @@html:<span class="ja">最初の方法について説明しよう。これは血糖値と呼ばれる方法である</span>@@:
- Japanese: see this [[https://drive.google.com/uc?export=view&id=1LM-obCkz42W2WasPOS_dgcIemUgd4u2t][picture]].
- English: see this [[https://drive.google.com/uc?export=view&id=1RQPlByenmhV1shOCZToHKuJTs1t35MhD][picture]].
- Fasting glucose is more than 7 mmol/l. @@html:<span class="ja">空腹時グルコースが7mmol/l以上</span>@@
  - 7 = ち = 知 = wisdom
  - @@html:It is a sign of <mark>知</mark> if someone <mark>stops eating food</mark> for a long time. <span class="ja">長期間の<mark>断食</mark>は<mark>知</mark>のしるしである。</span>@@
- Random glucose is more than 11.1 mmol/l. @@html:<span class="ja"><mark>ランダム</mark>サンプルの血糖値が11.1mmol/l以上。</span>@@
  - 1 = ひ
  - 11.1 = ひひ.ひ
  - @@html:Sometimes you and I do this <mark>ひひひ</mark> laugh <mark>randomly</mark>.@@ @@html:<span class="ja">時々、あなたと私は<mark>ランダム</mark>に「<mark>ひひひ</mark>」をするんだ。</span>@@

Now, let's talk about the second way. This is called HbA1c @@html:<span class="ja">では、2番目の方法について説明しよう。これはHbA1cと呼ばれるものです</span>@@:
- Japanese: see this [[https://drive.google.com/uc?export=view&id=1tg3wFPxyymbGdcXXioicPE16882LJG_R][picture]].
- English: see this [[https://drive.google.com/uc?export=view&id=1n1mvJzctB3OrA4Y-Kpbm9e_SH898oKJI][picture]].
- If the HbA1c level is more than 48 mmol/mol, then the patient has diabetes. @@html:<span class="ja">HbA1c値が48mmol/l以上であれば糖尿病である。</span>@@

After you start treatment, you should check the HbA1c levels every 3-6 months. Then, when the levels are stable, keep checking them every 6 months. @@html:<span class="ja">治療開始後は、3～6ヵ月ごとにHbA1c値をチェックする必要があります。その後、値が安定したら、6ヵ月ごとにチェックを続けます。</span>@@

** Treatment
:PROPERTIES:
:CUSTOM_ID: orgef8b70f
:END:

When the patient is first diagnosed with diabetes, you need to agree on a target HbA1c. This means that you should try to reduce the level of HbA1c so that it is the same as the target. @@html:<span class="ja">患者が初めて糖尿病と診断されたら、HbA1cの目標値を決めておく必要があります。つまり、HbA1cの値が目標値と同じになるように減らす努力をしなければなりません。</span>@@

There are few things that change the target HbA1c level. Here is a table @@html:<span class="ja">HbA1cの目標値を変えるものはほとんどない。ここに表がある</span>@@:

| Treatment                                                                                | Target HbA1c |
|------------------------------------------------------------------------------------------+--------------|
| Lifestyle advice and metformin                                                           | 48 mmol/mol  |
| Patient on drugs that cause hypoglycaemia                                                | 53 mmol/mol  |
| Patient already has diabetes treatment, but their HbA1c is /still more than 58 mmol/mol/ | 53 mmol/mol  |

First-line is lifestyle advice. @@html:<span class="ja">第一選択治療は生活習慣のアドバイスである。</span>@@

The first-line drug is metformin. @@html:<span class="ja">第一選択薬はメトホルミンである。</span>@@

Sometimes, metformin can cause diarrhoea and stomach pain. If the patient gets those symptoms, then you need to switch to a metformin type that is released /slowly/ (this is called "modified-release metformin"). @@html:<span class="ja">メトホルミンは時に下痢や胃痛を起こすことがある。もしそのような症状が出た場合は、メトホルミンの放出がゆっくりなタイプ（これを「徐放性メトホルミン / modified-release metformin」といいます）に変更する必要があります。</span>@@

If the patient has heart issues, then you should give SGLT-2 inhibitors with the metformin. @@html:<span class="ja">もし患者が心臓に問題を抱えているなら、メトホルミンと一緒にSGLT-2阻害薬を投与すべきである。</span>@@

In the table below, I have summarised all of the diabetes drugs. I will try to make stories for them when I have time. @@html:<span class="ja">下の表に、糖尿病治療薬をすべてまとめてみた。時間があるときに、これらの薬についての物語を作ろうと思う。</span>@@

#+BEGIN_EXPORT html
<table>
<tbody>
<tr>
<th class="org-left" scope="col">Drug group</th>
<th class="org-left" scope="col">Examples</th>
<th class="org-left" scope="col">Side effects</th>
<th class="org-left" scope="col">Special notes</th>
</tr>
<tr>
<td class="org-left">Metformin</td>
<td class="org-left">Metformin</td>
<td class="org-left">
<ul>
<li>Gastrointestinal side-effects like diarrhoea</li>
<li>Lactic acidosis</li>
</ul>
</td>
<td class="org-left">This is the first line.</td>
</tr>
<tr>
<td class="org-left">Sulfonylureas</td>
<td class="org-left">Gliclazide, glipizide</td>
<td class="org-left">
<ul>
<li>These can reduce your glucose level a loooooooot</li>
</ul>
</td>
<td class="org-left">These are used when the patient has heart issues.</td>
</tr>
<tr>
<td class="org-left">Glitazones</td>
<td class="org-left">Pioglitazone</td>
<td class="org-left">
<ul>
<li>These can cause the body to store a lot of water. So, they might give the patient pulmonary oedema (fluid in the lung).</li>
<li>Liver issues</li>
</ul>
</td>
<td class="org-left">Do not use these if the patient has heart failure. They will make the heart failure much worse.</td>
</tr>
<tr>
<td class="org-left">Gliptins</td>
<td class="org-left">Sitagliptin</td>
<td class="org-left">
<ul>
<li>UTI</li>
</ul>
</td>
<td class="org-left">These do not cause weight gain.</td>
</tr>
<tr>
<td class="org-left">Incretins</td>
<td class="org-left">Exenatide</td>
<td class="org-left">
<ul>
<li>Pancreatitis</li>
</ul>
</td>
<td class="org-left">These make you feel less hungry.</td>
</tr>
<tr>
<td class="org-left">SGLT2 inhibitors</td>
<td class="org-left">Dapagliflozin</td>
<td class="org-left">
<ul>
<li>&nbsp;These make you urinate a lot of sugar. So, you might get genital fungal infection!</li>
</ul>
</td>
<td class="org-left">These help with weight loss.</td>
</tr>
</tbody>
</table>
#+END_EXPORT

* Hypothyroidism
:PROPERTIES:
:CUSTOM_ID: orgfed91cd
:END:

Posted: 2023-07-21 | Updated: 2023-07-21

Thyroid gland makes... thyroid hormones. Wowwwwww. Really??? NO WAY!!!!!!!

Ok ok seriously. These hormones regulate body processes, like the speed of cells and organs. @@html:<span class="ja">これらのホルモンは、細胞や臓器のスピードなど、身体のプロセスを調節する。</span>@@

HYPoOooOoOOthryoidism means that we have /few/ thyroid hormones (called T4 hormones). So... everything will be /slow/. Look at that!!! @@html:<mark>hypo</mark> sounds like <mark>slow</mark>@@.

If we have no thyroid hormones, then we cannot generate heat!!!! @@html:<span class="ja">甲状腺ホルモンがなければ、熱を発生させることはできない！！！！</span>@@

You know this already.

Easy.

Here is the weird part...

Hypothyroidism has two types:
- Primary: this is when the thyroid gland is broken (remember, the thyroid gland produces T4 hormone). This is the common one. @@html:<span class="ja">これは甲状腺が壊れた場合です（甲状腺はT4ホルモンを生成することを覚えておいてください）。これが一般的なものです。</span>@@
- Secondary: this is when the hypothalamus is broken (hypothalamus produces TSH). This is quite rare. @@html:<span class="ja">これは視床下部が壊れた場合である（視床下部はTSHを産生する）。これはかなりまれなことです。</span>@@

There are many causes for HYPoOooOoOOthryoidism:
1. Hashimoto thyroiditis: this affects the thyroid gland. It is autoimmune. It releases antibody called anti-TPO (Thyroid PerOxidase). @@html:<span class="ja">これは甲状腺に影響する。自己免疫性です。抗TPO（Thyroid PerOxidase）と呼ばれる抗体を放出します。</span>@@
2. Thyroid gland surgery
3. Drugs: lithium and amiodarone! Remember those two! Important!!!
  - Lithium stops the thyroid gland from making thyroid hormone. @@html:<span class="ja">リチウムは甲状腺が甲状腺ホルモンを作るのを止める。</span>@@
  - Amiodarone sticks to thyroid hormones. @@html:<span class="ja">アミオダロンは甲状腺ホルモンにくっつく。ベタベタ、ベタベタ、ベタベタ、ベタベタ、ベタベタ、ベタベタ...。</span>@@

** Signs and symptoms
:PROPERTIES:
:CUSTOM_ID: org86f9baf
:END:

- Everything is /slow/ and /low/ in HYPOthryoidism!
- Weight gain... if you are very  @@html:<span class="ja">ぷにぷに</span>@@ then you will be slow at running!!!
- /Low/ temperature. You will feel cold /all/ the time!!!! Maybe... I have HYPOthryoidism...?
- /Low/ hair... Low hair???? @@html:<span class="ja">え？えーと。。。まって、まって、まって...。</span>@@
  - Hair loss and dry skin!!!
  - Loss of eyebrow hair!
- /Low/ heart rate (bradycardia).

** Investigations
:PROPERTIES:
:CUSTOM_ID: org8b6e9ad
:END:

- You must check the TSH level and T4 levels. @@html:<span class="ja">TSH値とT4値をチェックする必要があります。</span>@@
  - T4 will be low because the thyroid is broken. @@html:<span class="ja">甲状腺が壊れているので、T4は低くなる。</span>@@
  - TSH will be high because the hypothalamus is panicking and it is saying "Ahhhh why are the T4 levels low?! I should make more TSH!!!" @@html:<span class="ja">TSHが高くなるのは、視床下部がパニックを起こし、「あ～、なぜT4値が低いのだ？！もっとTSHを作るべきだ！！！」。</span>@@
- If you think that the patient has Hashimoto thyroiditis, then you should check if there is anti-TPO in the blood. @@html:<span class="ja">患者が橋本甲状腺炎であると思われる場合は、血液中に抗TPOがあるかどうかを調べるべきです。</span>@@

** Treatment
:PROPERTIES:
:CUSTOM_ID: org07e0ec8
:END:

- You should give levothyroxine to the patient. @@html:<span class="ja">患者にレボチロキシンを投与する必要がある。</span>@@
- Levothyroxine is basically thyroid hormones. @@html:<span class="ja">レボチロキシンは基本的に甲状腺ホルモンである。</span>@@
- If the woman is about to become pregnant, then you must increase the dose of levothyroxine. This is because pregnant women need a lot of thyroid hormones. @@html:<span class="ja">その女性が妊娠しようとしているのであれば、レボチロキシンの量を増やさなければなりません。妊婦はたくさんの甲状腺ホルモンを必要とするからです。</span>@@
- Also, calcium carbonate can interact with levothyroxine! So, be careful!!! @@html:<span class="ja">また、炭酸カルシウムはレボチロキシンと相互作用する可能性があります！だから気をつけて！！！</span>@@
  - Calcium carbonate sticks to levothyroxine and prevents the absorption of levothyroxine! @@html:<span class="ja">炭酸カルシウムはレボチロキシンとくっつき、レボチロキシンの吸収を妨げる！</span>@@
- Levothyroxine makes the bone more weak... やれやれ...

* Phaeochromocytoma
:PROPERTIES:
:CUSTOM_ID: org1ffb3ae
:END:

Posted: 2023-07-21 | Updated: 2023-07-21

This is a cancer of the adrenal gland. @@html:<span class="ja">これは副腎の癌である。</span>@@

It is associated with a group of cancers called "Multiple Endocrine Neoplasia Type 2". @@html:<span class="ja">「Multiple Endocrine Neoplasia Type 2」と呼ばれる一群のがんと関連している。</span>@@

This cancer makes a lot of adrenaline. @@html:<span class="ja">このがんはアドレナリンを大量に分泌する。</span>@@

Adrenaline belongs to a group of chemicals called "catecholamine". @@html:<span class="ja">アドレナリンは「カテコールアミン」と呼ばれる化学物質群に属する。</span>@@

The adrenaline makes your blood pressure /really/ high. @@html:<span class="ja">アドレナリンは血圧を非常に、非常に高くする。</span>@@

** Signs and symptoms
:PROPERTIES:
:CUSTOM_ID: org6d88fc6
:END:

- @@html:You can remember the symptoms of <mark>P</mark>haeochromocytoma like this <mark>PPP</mark>@@:
  - @@html:High blood <mark>P</mark>ressure: very, very, very, very, very, very, very, very, very, very, very high blood pressure.@@
  - @@html:Head <mark>P</mark>ain: there is a lot of headache.@@
  - @@html:<mark>P</mark>alpitations: the adrenaline makes your heart beat faster. <span class="ja">アドレナリンが心臓の鼓動を早める。</span>@@

** Investigations
:PROPERTIES:
:CUSTOM_ID: orgceb2971
:END:

- You should do a blood test to see if the patient has catecholamine (like we said before, catecholamine is another word for adrenaline). @@html:<span class="ja">血液検査をして、患者にカテコールアミン（前にも言ったように、カテコールアミンとはアドレナリンの別名である）があるかどうかを確認する必要がある。</span>@@

** Treatment
:PROPERTIES:
:CUSTOM_ID: org794af8f
:END:

- @@html:First, you need to give the patient alpha-blocker. You need to use <mark>p</mark>henoxybenzamine. This is easy to remember: <mark>P</mark>henoxybenzamine and <mark>P</mark>haeochromocytoma. <span class="ja">まず、患者にα遮断薬を投与する必要がある。フェノキシベンザミンを使う必要がある。これは覚えやすい：<mark>フェ</mark>ノキシベンザミンと<mark>フェ</mark>オクロモサイトーマ。</span>@@
- Then, give a beta-blocker. @@html:<span class="ja">それからβ遮断薬を投与する。</span>@@
- Then, after few weeks, you need to do surgery to remove the cancer. @@html:<span class="ja">そして数週間後、癌を取り除く手術をする必要がある。</span>@@

* Hypoglycaemia
:PROPERTIES:
:CUSTOM_ID: org5506f29
:END:

Posted: 2023-06-13 | Updated: 2023-06-13

Low blood sugar level happens in many patients. @@html:<span class="ja">低血糖は多くの患者さんに起こります。</span>@@

Sometimes, it can happen in new-born babies. When it happens in new-born babies, it is called "neonatal hypoglycaemia". @@html:<span class="ja">時には、新生児に起こることもあります。新生児に起こる場合は「新生児低血糖症」と呼ばれます。</span>@@

** Signs and symptoms
:PROPERTIES:
:CUSTOM_ID: orgff9e020
:END:

If there is hypoglycaemia in babies:
- There are more symptoms on Passmedicine. Go to the page that is called "Neonatal hypoglycaemia".
- Baby is annoyed and keeps crying
- Pale baby
- Baby does not eat or drink

If there is hypoglycaemia in adults:
- Dizzy
- Hungry
- Sweaty
- Nausea and vomiting

** Investigations
:PROPERTIES:
:CUSTOM_ID: org87d0e68
:END:

- In new-born babies, hypoglycaemia is when blood sugar is below 2.6 mmol/L @@html:<span class="ja">新生児では、血糖値が2.6mmol/L以下になると低血糖となります</span>@@:
  - 2.6
  - 2 = ふ
  - 6 = ろ
  - ふろ... 風呂
  - 風呂 = bath
  - @@html:Imagine a new-born baby having a bath (<mark>風呂</mark>) and eating a big sugar cube because the <mark>blood sugar of the baby is low</mark>. <span class="ja">生まれたばかりの赤ちゃんがお<mark>風呂</mark>に入り、血糖値が低いので大きな角砂糖を食べているところを想像してください。</span>@@
- In adults, hypoglycaemia is when blood sugar is below 4 mmol/L @@html:<span class="ja">成人の場合、血糖値が4mmol/L以下になると低血糖となる</span>@@:
  - 4 = し = 士
  - 士 = soldier
  - @@html:Imagine a soldier (<mark>士</mark>) in the war. The soldier is holding a pistol that <mark>shoots sugar cubes</mark> to give sugar to support the other soldiers. <span class="ja">戦争に参加する<mark>士</mark>を想像してください。その士はピストルを持っていて、<mark>角砂糖</mark>を撃って他の士を支援するために砂糖を与える。</span>@@
- Doctors sometimes cannot tell if low blood sugar is caused by a problem with the pancreas or if it is a result of taking drugs. So, the doctor might do a test called "C-peptide test". @@html:<span class="ja">低血糖が膵臓の問題で起こるのか、それとも薬の服用が原因なのか、医師が見分けられないこともあります。そこで、医師が「C-peptide test」という検査をすることがあります。</span>@@
  - Measuring C-peptide is a way to see how much insulin your body is making. So, if there is little C-peptide, then that means your body is not making enough insulin. @@html:<span class="ja">C-peptideを測定することで、体内でどれだけインスリンが作られているかを正確に知ることができます。つまり、C-peptideが少ないということは、体内でインスリンが十分に作られていないことを意味します。</span>@@
  - You can read more about it on this [[https://medlineplus.gov/lab-tests/c-peptide-test/][website]].

** Treatment
:PROPERTIES:
:CUSTOM_ID: org22b3a22
:END:

- So, this depends on the fact if the patient is conscious or not. @@html:<span class="ja">ですから、これは患者さんの意識があるかないかという事実に左右されます。</span>@@
- If the person is awake and not dizzy, then you can give them "fast-acting carbohydrate" in the mouth. So, things like sugar tablets or sweeeeeeeet drink... If the new-born baby has a low sugar level but does not have any symptoms, then you can just keep feeding the baby milk! @@html:<span class="ja">目が覚めていて、フラフラしていなければ、「即効性のある炭水化物」を口に含ませてあげればいいのです。つまり、砂糖の錠剤や甘い飲み物のようなものです。新生児の糖度が低くても症状がなければ、そのままミルクを与え続けても大丈夫です！</span>@@
- If the new-born baby has symptoms, then give /10%/ IV dextrose (dextrose is just another name for sugar) @@html:<span class="ja">新生児に症状がある場合は、dextrose（dextroseは砂糖の別名です）を10%点滴します。</span>@@:
  - 10 = じ = 児
  - 児 = child
  - @@html:Easy to remember! Give <mark>10</mark>% dextrose to the <mark>児</mark>！<span class="ja"><mark>児</mark>に<mark>10</mark>%デキストローズを与える。</span>@@
- If the adult is not awake, then give /20%/ IV dextrose! @@html:<span class="ja">成人が覚醒していない場合は、20％のブドウ糖を静脈内投与する！</span>@@
- So, you might be wondering, why should we not give oral food to unconscious patients? Well, this is because they might choke on the food! Pay attention to this in the exam! @@html:<span class="ja">では、なぜ意識のない患者さんに経口食を与えてはいけないのか、疑問に思われるかもしれません。それは、食べ物を喉に詰まらせてしまう可能性があるからです！試験では、この点に注意してください！</span>@@

* Anaphylaxis
:PROPERTIES:
:CUSTOM_ID: orgeec3172
:END:

Posted: 2023-06-12 | Updated: 2023-06-12

This is a life-threatening allergic reaction to something like peanuts. @@html:<span class="ja">これはピーナッツのようなものに対する生命を脅かすアレルギー反応です。</span>@@

** Signs and symptoms
:PROPERTIES:
:CUSTOM_ID: orga812fc8
:END:

- Swelling of tongue, lips, and face. @@html:<span class="ja">舌、唇、顔の腫れ。</span>@@
- Wheeze. @@html:<span class="ja">喘ぎ声。</span>@@
- Sweating and itching. Itchy, itchy, itchy... @@html:<span class="ja">汗をかき、かゆくなる。痒い、痒い、痒い...。</span>@@
- Urticaria. @@html:<span class="ja">蕁麻疹が出る。</span>@@

** Investigations
:PROPERTIES:
:CUSTOM_ID: org0f86fc8
:END:

- You can check for something called "tryptase". This is a chemical released by mast cells. This chemical causes narrow airway. @@html:<span class="ja">「Tryptase」と呼ばれるものを調べるとよいでしょう。これは、マスト細胞から放出される化学物質です。この化学物質が気道狭窄を引き起こすのです。</span>@@
- You can do skin prick and IgE tests to find out what is causing the allergy. @@html:<span class="ja">皮膚プリックテストやIgEテストを行い、アレルギーの原因となっているものを調べることができます。</span>@@

** Treatment
:PROPERTIES:
:CUSTOM_ID: org9b2352c
:END:

- These steps are very important to follow @@html:<span class="ja">これらの手順は、非常に重要なものです</span>@@:
  1. Keep the airway open. If you do not do that, then the patient will stop breathing and die! @@html:<span class="ja">気道を開いておくことです。そうしないと、患者は呼吸を止めて死んでしまいます！</span>@@
  2. Give 1:1000 adrenaline now. STOP READING THIS. GO GIVE ADRENALINE to the patient!!! @@html:<span class="ja">今すぐ1：1000のアドレナリンを投与する。これを読むのをやめなさい。患者にアドレナリンを投与してきてください！！！</span>@@
    - This will increase blood pressure. @@html:<span class="ja">これは血圧を上げることになります。</span>@@
    - 1000... せん... 戦...
    - 戦 = war...
    - Imagine people having a war (戦) with a giant peanut. Then, the peanut will throw 1000 small peanuts at the people and make them have anaphylaxis... @@html:<span class="ja">人々が巨大なピーナッツと<mark>戦</mark>ったとします。すると、ピーナッツは<mark>1000</mark>個の小さなピーナッツを人々に投げつけて、アナフィラキシーを起こさせるのです...。</span>@@
  3. Then, give antihistamines. You should use chlorphenamine. @@html:<span class="ja">次に、抗ヒスタミン剤を投与します。クロルフェナミンを使ってください。</span>@@
    - This removes histamine. @@html:<span class="ja">これにより、ヒスタミンが除去されます。</span>@@
    - Chlorphenamine. クロルフェニラミン。
    - ラミン... らみん... らみ～ん... this sounds like ラーメン... おいしいいいいいいいいです笑
    - So, after the giant peanut stops throwing peanuts, the people will sit and eat some ラーメン笑 @@html:<span class="ja">だから、巨大なピーナッツがピーナッツを投げるのを止めた後、人々は座って<mark>ラーメン</mark>を食べます笑</span>@@
  4. Thennn, give hydrocortisone. @@html:<span class="ja">そして、ヒドロコルチゾンを投与します。</span>@@
    - Hydrocortisone is a steroid. Steroids reduce inflammation and prevent future symptoms. @@html:<span class="ja">ヒドロコルチゾンはステロイドの一種です。ステロイドは、炎症を抑え、将来の症状を予防します。</span>@@
    - @@html:Hydrocortisone. <mark>Hydro</mark>cortisone!!!! Hydro... <mark>hydro</mark> means water!@@
    - @@html:So, after the people eat ラーメン, they will become thirsty. So, they will drink water. They are now <mark>hydrated</mark> (this sounds like <mark>hydro</mark>cortisone).@@
    - ラーメン is sometimes so salty... 笑. Does ラーメン make you thirsty?
