#+TITLE: Endocrinology 002

#+BEGIN_EXPORT html
<div class="engt">Endocrinology</div>
<div class="japt">内分泌学</div>
<div class="engt">Page 002</div>
#+END_EXPORT

[[https://github.com/ahisu6/ahisu6.github.io/edit/main/src/e/002.org][Edit]]

[[file:./index.org][Home]]

[[file:./001.org][<< Previous page]] - [[file:./003.org][Next page >>]]

-----

#+TOC: headlines 2

* Hypothyroidism
:PROPERTIES:
:CUSTOM_ID: orgfed91cd
:END:

Posted: 2023-07-21 | Updated: 2023-07-21

Thyroid gland makes... thyroid hormones. Wowwwwww. Really??? NO WAY!!!!!!!

Ok ok seriously. These hormones regulate body processes, like the speed of cells and organs. @@html:<span class="ja">これらのホルモンは、細胞や臓器のスピードなど、身体のプロセスを調節する。</span>@@

HYPoOooOoOOthryoidism means that we have /few/ thyroid hormones (called T4 hormones). So... everything will be /slow/. Look at that!!! @@html:<mark>hypo</mark> sounds like <mark>slow</mark>@@.

If we have no thyroid hormones, then we cannot generate heat!!!! @@html:<span class="ja">甲状腺ホルモンがなければ、熱を発生させることはできない！！！！</span>@@

You know this already.

Easy.

Here is the weird part...

Hypothyroidism has two types:
- Primary: this is when the thyroid gland is broken (remember, the thyroid gland produces T4 hormone). This is the common one. @@html:<span class="ja">これは甲状腺が壊れた場合です（甲状腺はT4ホルモンを生成することを覚えておいてください）。これが一般的なものです。</span>@@
- Secondary: this is when the hypothalamus is broken (hypothalamus produces TSH). This is quite rare. @@html:<span class="ja">これは視床下部が壊れた場合である（視床下部はTSHを産生する）。これはかなりまれなことです。</span>@@

There are many causes for HYPoOooOoOOthryoidism:
1. Hashimoto's thyroiditis: this affects the thyroid gland. It is autoimmune. It releases antibody called anti-TPO (Thyroid PerOxidase). @@html:<span class="ja">これは甲状腺に影響する。自己免疫性です。抗TPO（Thyroid PerOxidase）と呼ばれる抗体を放出します。</span>@@
2. Thyroid gland surgery
3. Drugs: lithium and amiodarone! Remember those two! Important!!!
  - Lithium stops the thyroid gland from making thyroid hormone. @@html:<span class="ja">リチウムは甲状腺が甲状腺ホルモンを作るのを止める。</span>@@
  - Amiodarone sticks to thyroid hormones. @@html:<span class="ja">アミオダロンは甲状腺ホルモンにくっつく。ベタベタ、ベタベタ、ベタベタ、ベタベタ、ベタベタ、ベタベタ...。</span>@@

** Signs and symptoms
:PROPERTIES:
:CUSTOM_ID: org86f9baf
:END:

- Everything is /slow/ and /low/ in HYPOthryoidism!
- Weight gain... if you are very  @@html:<span class="ja">ぷにぷに</span>@@ then you will be slow at running!!!
- /Low/ temperature. You will feel cold /all/ the time!!!! Maybe... I have HYPOthryoidism...?
- /Low/ hair... Low hair???? @@html:<span class="ja">え？えーと。。。まって、まって、まって...。</span>@@
  - Hair loss and dry skin!!!
  - Loss of eyebrow hair!
- /Low/ heart rate (bradycardia).

** Investigations
:PROPERTIES:
:CUSTOM_ID: org8b6e9ad
:END:

- You must check the TSH level and T4 levels. @@html:<span class="ja">TSH値とT4値をチェックする必要があります。</span>@@
  - T4 will be low because the thyroid is broken. @@html:<span class="ja">甲状腺が壊れているので、T4は低くなる。</span>@@
  - TSH will be high because the hypothalamus is panicking and it is saying "Ahhhh why are the T4 levels low?! I should make more TSH!!!" @@html:<span class="ja">TSHが高くなるのは、視床下部がパニックを起こし、「あ～、なぜT4値が低いのだ？！もっとTSHを作るべきだ！！！」。</span>@@

** Treatment
:PROPERTIES:
:CUSTOM_ID: org07e0ec8
:END:

- You should give levothyroxine to the patient. @@html:<span class="ja">患者にレボチロキシンを投与する必要がある。</span>@@
- Levothyroxine is basically thyroid hormones. @@html:<span class="ja">レボチロキシンは基本的に甲状腺ホルモンである。</span>@@
- If the woman is about to become pregnant, then you must increase the dose of levothyroxine. This is because pregnant women need a lot of thyroid hormones. @@html:<span class="ja">その女性が妊娠しようとしているのであれば、レボチロキシンの量を増やさなければなりません。妊婦はたくさんの甲状腺ホルモンを必要とするからです。</span>@@
- Also, calcium carbonate can interact with levothyroxine! So, be careful!!! @@html:<span class="ja">また、炭酸カルシウムはレボチロキシンと相互作用する可能性があります！だから気をつけて！！！</span>@@
  - Calcium carbonate sticks to levothyroxine and prevents the absorption of levothyroxine! @@html:<span class="ja">炭酸カルシウムはレボチロキシンとくっつき、レボチロキシンの吸収を妨げる！</span>@@

* Phaeochromocytoma
:PROPERTIES:
:CUSTOM_ID: org1ffb3ae
:END:

Posted: 2023-07-21 | Updated: 2023-07-21

This is a cancer of the adrenal gland. @@html:<span class="ja">これは副腎の癌である。</span>@@

It is associated with a group of cancers called "Multiple Endocrine Neoplasia Type 2". @@html:<span class="ja">「Multiple Endocrine Neoplasia Type 2」と呼ばれる一群のがんと関連している。</span>@@

This cancer makes a lot of adrenaline. @@html:<span class="ja">このがんはアドレナリンを大量に分泌する。</span>@@

Adrenaline belongs to a group of chemicals called "catecholamine". @@html:<span class="ja">アドレナリンは「カテコールアミン」と呼ばれる化学物質群に属する。</span>@@

The adrenaline makes your blood pressure /really/ high. @@html:<span class="ja">アドレナリンは血圧を非常に、非常に高くする。</span>@@

** Signs and symptoms
:PROPERTIES:
:CUSTOM_ID: org6d88fc6
:END:

- @@html:You can remember the symptoms of <mark>P</mark>haeochromocytoma like this <mark>PPP</mark>@@:
  - @@html:High blood <mark>P</mark>ressure: very, very, very, very, very, very, very, very, very, very, very high blood pressure.@@
  - @@html:Head <mark>P</mark>ain: there is a lot of headache.@@
  - @@html:<mark>P</mark>alpitations: the adrenaline makes your heart beat faster. <span class="ja">アドレナリンが心臓の鼓動を早める。</span>@@

** Investigations
:PROPERTIES:
:CUSTOM_ID: orgceb2971
:END:

- You should do a blood test to see if the patient has catecholamine (like we said before, catecholamine is another word for adrenaline). @@html:<span class="ja">血液検査をして、患者にカテコールアミン（前にも言ったように、カテコールアミンとはアドレナリンの別名である）があるかどうかを確認する必要がある。</span>@@

** Treatment
:PROPERTIES:
:CUSTOM_ID: org794af8f
:END:

- @@html:First, you need to give the patient alpha-blocker. You need to use <mark>p</mark>henoxybenzamine. This is easy to remember: <mark>P</mark>henoxybenzamine and <mark>P</mark>haeochromocytoma. <span class="ja">まず、患者にα遮断薬を投与する必要がある。フェノキシベンザミンを使う必要がある。これは覚えやすい：<mark>フェ</mark>ノキシベンザミンと<mark>フェ</mark>オクロモサイトーマ。</span>@@
- Then, give a beta-blocker. @@html:<span class="ja">それからβ遮断薬を投与する。</span>@@
- Then, after few weeks, you need to do surgery to remove the cancer. @@html:<span class="ja">そして数週間後、癌を取り除く手術をする必要がある。</span>@@

* Hypoglycaemia
:PROPERTIES:
:CUSTOM_ID: org5506f29
:END:

Posted: 2023-06-13 | Updated: 2023-06-13

Low blood sugar level happens in many patients. @@html:<span class="ja">低血糖は多くの患者さんに起こります。</span>@@

Sometimes, it can happen in new-born babies. When it happens in new-born babies, it is called "neonatal hypoglycaemia". @@html:<span class="ja">時には、新生児に起こることもあります。新生児に起こる場合は「新生児低血糖症」と呼ばれます。</span>@@

** Signs and symptoms
:PROPERTIES:
:CUSTOM_ID: orgff9e020
:END:

If there is hypoglycaemia in babies:
- There are more symptoms on Passmedicine. Go to the page that is called "Neonatal hypoglycaemia".
- Baby is annoyed and keeps crying
- Pale baby
- Baby does not eat or drink

If there is hypoglycaemia in adults:
- Dizzy
- Hungry
- Sweaty
- Nausea and vomiting

** Investigations
:PROPERTIES:
:CUSTOM_ID: org87d0e68
:END:

- In new-born babies, hypoglycaemia is when blood sugar is below 2.6 mmol/L @@html:<span class="ja">新生児では、血糖値が2.6mmol/L以下になると低血糖となります</span>@@:
  - 2.6
  - 2 = ふ
  - 6 = ろ
  - ふろ... 風呂
  - 風呂 = bath
  - @@html:Imagine a new-born baby having a bath (<mark>風呂</mark>) and eating a big sugar cube because the <mark>blood sugar of the baby is low</mark>. <span class="ja">生まれたばかりの赤ちゃんがお<mark>風呂</mark>に入り、血糖値が低いので大きな角砂糖を食べているところを想像してください。</span>@@
- In adults, hypoglycaemia is when blood sugar is below 4 mmol/L @@html:<span class="ja">成人の場合、血糖値が4mmol/L以下になると低血糖となる</span>@@:
  - 4 = し = 士
  - 士 = soldier
  - @@html:Imagine a soldier (<mark>士</mark>) in the war. The soldier is holding a pistol that <mark>shoots sugar cubes</mark> to give sugar to support the other soldiers. <span class="ja">戦争に参加する<mark>士</mark>を想像してください。その士はピストルを持っていて、<mark>角砂糖</mark>を撃って他の士を支援するために砂糖を与える。</span>@@
- Doctors sometimes cannot tell if low blood sugar is caused by a problem with the pancreas or if it is a result of taking drugs. So, the doctor might do a test called "C-peptide test". @@html:<span class="ja">低血糖が膵臓の問題で起こるのか、それとも薬の服用が原因なのか、医師が見分けられないこともあります。そこで、医師が「C-peptide test」という検査をすることがあります。</span>@@
  - Measuring C-peptide is a way to see how much insulin your body is making. So, if there is little C-peptide, then that means your body is not making enough insulin. @@html:<span class="ja">C-peptideを測定することで、体内でどれだけインスリンが作られているかを正確に知ることができます。つまり、C-peptideが少ないということは、体内でインスリンが十分に作られていないことを意味します。</span>@@
  - You can read more about it on this [[https://medlineplus.gov/lab-tests/c-peptide-test/][website]].

** Treatment
:PROPERTIES:
:CUSTOM_ID: org22b3a22
:END:

- So, this depends on the fact if the patient is conscious or not. @@html:<span class="ja">ですから、これは患者さんの意識があるかないかという事実に左右されます。</span>@@
- If the person is awake and not dizzy, then you can give them "fast-acting carbohydrate" in the mouth. So, things like sugar tablets or sweeeeeeeet drink... If the new-born baby has a low sugar level but does not have any symptoms, then you can just keep feeding the baby milk! @@html:<span class="ja">目が覚めていて、フラフラしていなければ、「即効性のある炭水化物」を口に含ませてあげればいいのです。つまり、砂糖の錠剤や甘い飲み物のようなものです。新生児の糖度が低くても症状がなければ、そのままミルクを与え続けても大丈夫です！</span>@@
- If the new-born baby has symptoms, then give /10%/ IV dextrose (dextrose is just another name for sugar) @@html:<span class="ja">新生児に症状がある場合は、dextrose（dextroseは砂糖の別名です）を10%点滴します。</span>@@:
  - 10 = じ = 児
  - 児 = child
  - @@html:Easy to remember! Give <mark>10</mark>% dextrose to the <mark>児</mark>！<span class="ja"><mark>児</mark>に<mark>10</mark>%デキストローズを与える。</span>@@
- If the adult is not awake, then give /20%/ IV dextrose! @@html:<span class="ja">成人が覚醒していない場合は、20％のブドウ糖を静脈内投与する！</span>@@
- So, you might be wondering, why should we not give oral food to unconscious patients? Well, this is because they might choke on the food! Pay attention to this in the exam! @@html:<span class="ja">では、なぜ意識のない患者さんに経口食を与えてはいけないのか、疑問に思われるかもしれません。それは、食べ物を喉に詰まらせてしまう可能性があるからです！試験では、この点に注意してください！</span>@@

* Anaphylaxis
:PROPERTIES:
:CUSTOM_ID: orgeec3172
:END:

Posted: 2023-06-12 | Updated: 2023-06-12

This is a life-threatening allergic reaction to something like peanuts. @@html:<span class="ja">これはピーナッツのようなものに対する生命を脅かすアレルギー反応です。</span>@@

** Signs and symptoms
:PROPERTIES:
:CUSTOM_ID: orga812fc8
:END:

- Swelling of tongue, lips, and face. @@html:<span class="ja">舌、唇、顔の腫れ。</span>@@
- Wheeze. @@html:<span class="ja">喘ぎ声。</span>@@
- Sweating and itching. Itchy, itchy, itchy... @@html:<span class="ja">汗をかき、かゆくなる。痒い、痒い、痒い...。</span>@@
- Urticaria. @@html:<span class="ja">蕁麻疹が出る。</span>@@

** Investigations
:PROPERTIES:
:CUSTOM_ID: org0f86fc8
:END:

- You can check for something called "tryptase". This is a chemical released by mast cells. This chemical causes narrow airway. @@html:<span class="ja">「Tryptase」と呼ばれるものを調べるとよいでしょう。これは、マスト細胞から放出される化学物質です。この化学物質が気道狭窄を引き起こすのです。</span>@@
- You can do skin prick and IgE tests to find out what is causing the allergy. @@html:<span class="ja">皮膚プリックテストやIgEテストを行い、アレルギーの原因となっているものを調べることができます。</span>@@

** Treatment
:PROPERTIES:
:CUSTOM_ID: org9b2352c
:END:

- These steps are very important to follow @@html:<span class="ja">これらの手順は、非常に重要なものです</span>@@:
  1. Keep the airway open. If you do not do that, then the patient will stop breathing and die! @@html:<span class="ja">気道を開いておくことです。そうしないと、患者は呼吸を止めて死んでしまいます！</span>@@
  2. Give 1:1000 adrenaline now. STOP READING THIS. GO GIVE ADRENALINE to the patient!!! @@html:<span class="ja">今すぐ1：1000のアドレナリンを投与する。これを読むのをやめなさい。患者にアドレナリンを投与してきてください！！！</span>@@
    - This will increase blood pressure. @@html:<span class="ja">これは血圧を上げることになります。</span>@@
    - 1000... せん... 戦...
    - 戦 = war...
    - Imagine people having a war (戦) with a giant peanut. Then, the peanut will throw 1000 small peanuts at the people and make them have anaphylaxis... @@html:<span class="ja">人々が巨大なピーナッツと<mark>戦</mark>ったとします。すると、ピーナッツは<mark>1000</mark>個の小さなピーナッツを人々に投げつけて、アナフィラキシーを起こさせるのです...。</span>@@
  3. Then, give antihistamines. You should use chlorphenamine. @@html:<span class="ja">次に、抗ヒスタミン剤を投与します。クロルフェナミンを使ってください。</span>@@
    - This removes histamine. @@html:<span class="ja">これにより、ヒスタミンが除去されます。</span>@@
    - Chlorphenamine. クロルフェニラミン。
    - ラミン... らみん... らみ～ん... this sounds like ラーメン... おいしいいいいいいいいです笑
    - So, after the giant peanut stops throwing peanuts, the people will sit and eat some ラーメン笑 @@html:<span class="ja">だから、巨大なピーナッツがピーナッツを投げるのを止めた後、人々は座って<mark>ラーメン</mark>を食べます笑</span>@@
  4. Thennn, give hydrocortisone. @@html:<span class="ja">そして、ヒドロコルチゾンを投与します。</span>@@
    - Hydrocortisone is a steroid. Steroids reduce inflammation and prevent future symptoms. @@html:<span class="ja">ヒドロコルチゾンはステロイドの一種です。ステロイドは、炎症を抑え、将来の症状を予防します。</span>@@
    - @@html:Hydrocortisone. <mark>Hydro</mark>cortisone!!!! Hydro... <mark>hydro</mark> means water!@@
    - @@html:So, after the people eat ラーメン, they will become thirsty. So, they will drink water. They are now <mark>hydrated</mark> (this sounds like <mark>hydro</mark>cortisone).@@
    - ラーメン is sometimes so salty... 笑. Does ラーメン make you thirsty?
