#+TITLE: Endocrinology 002

#+BEGIN_EXPORT html
<div class="engt">Endocrinology</div>
<div class="japt">内分泌学</div>
<div class="engt">Page 002</div>
#+END_EXPORT

[[https://github.com/ahisu6/ahisu6.github.io/edit/main/src/e/002.org][Edit]]

[[file:./index.org][Home]]

[[file:./001.org][<< Previous page]] - [[file:./003.org][Next page >>]]

-----

#+TOC: headlines 2

* Anaphylaxis
:PROPERTIES:
:CUSTOM_ID: orgeec3172
:END:

Posted: 2023-06-12 | Updated: 2023-06-12

This is a life-threatening allergic reaction to something like peanuts. @@html:<span class="ja">これはピーナッツのようなものに対する生命を脅かすアレルギー反応です。</span>@@

** Signs and symptoms
:PROPERTIES:
:CUSTOM_ID: orga812fc8
:END:

- Swelling of tongue, lips, and face. @@html:<span class="ja">舌、唇、顔の腫れ。</span>@@
- Wheeze. @@html:<span class="ja">喘ぎ声。</span>@@
- Sweating and itching. Itchy, itchy, itchy... @@html:<span class="ja">汗をかき、かゆくなる。痒い、痒い、痒い...。</span>@@
- Urticaria. @@html:<span class="ja">蕁麻疹が出る。</span>@@

** Investigations
:PROPERTIES:
:CUSTOM_ID: org0f86fc8
:END:

- You can check for something called "tryptase". This is a chemical released by mast cells. This chemical causes narrow airway. @@html:<span class="ja">「Tryptase」と呼ばれるものを調べるとよいでしょう。これは、マスト細胞から放出される化学物質です。この化学物質が気道狭窄を引き起こすのです。</span>@@
- You can do skin prick and IgE tests to find out what is causing the allergy. @@html:<span class="ja">皮膚プリックテストやIgEテストを行い、アレルギーの原因となっているものを調べることができます。</span>@@

** Treatment
:PROPERTIES:
:CUSTOM_ID: org9b2352c
:END:

- These steps are very important to follow @@html:<span class="ja">これらの手順は、非常に重要なものです</span>@@:
  1. Keep the airway open. If you do not do that, then the patient will stop breathing and die! @@html:<span class="ja">気道を開いておくことです。そうしないと、患者は呼吸を止めて死んでしまいます！</span>@@
  2. Give 1:1000 adrenaline now. STOP READING THIS. GO GIVE ADRENALINE to the patient!!! @@html:<span class="ja">今すぐ1：1000のアドレナリンを投与する。これを読むのをやめなさい。患者にアドレナリンを投与してきてください！！！</span>@@
    - This will increase blood pressure. @@html:<span class="ja">これは血圧を上げることになります。</span>@@
    - 1000... せん... 戦...
    - 戦 = war...
    - Imagine people having a war (戦) with a giant peanut. Then, the peanut will throw 1000 small peanuts at the people and make them have anaphylaxis... @@html:<span class="ja">人々が巨大なピーナッツと<mark>戦</mark>ったとします。すると、ピーナッツは<mark>1000</mark>個の小さなピーナッツを人々に投げつけて、アナフィラキシーを起こさせるのです...。</span>@@
  3. Then, give antihistamines. You should use chlorphenamine. @@html:<span class="ja">次に、抗ヒスタミン剤を投与します。クロルフェナミンを使ってください。</span>@@
    - This removes histamine. @@html:<span class="ja">これにより、ヒスタミンが除去されます。</span>@@
    - Chlorphenamine. クロルフェニラミン。
    - ラミン... らみん... This sounds like ら～めん... おいしいいいいいいいいです笑
    - So, after the giant peanut stops throwing peanuts, the people will sit and eat some らめん笑 @@html:<span class="ja">だから、巨大なピーナッツがピーナッツを投げるのを止めた後、人々は座って<mark>ラーメン</mark>を食べます笑</span>@@
  4. Thennn, give hydrocortisone. @@html:<span class="ja">そして、ヒドロコルチゾンを投与します。</span>@@
    - Hydrocortisone is a steroid. Steroids reduce inflammation and prevent future symptoms. @@html:<span class="ja">ヒドロコルチゾンはステロイドの一種です。ステロイドは、炎症を抑え、将来の症状を予防します。</span>@@
    - @@html:Hydrocortisone. <mark>Hydro</mark>cortisone!!!! Hydro... <mark>hydro</mark> means water!@@
    - @@html:So, after the people eat ら～めん, they will become thirsty. So, they will drink water (they are now <mark>hydrated</mark> (this sounds like <mark>hydro</mark>cortisone)!).@@
