#+TITLE: Rheumatology 001

#+BEGIN_EXPORT html
<div class="engt">Rheumatology</div>
<div class="japt">リウマチ学</div>
<div class="engt">Page 001</div>
#+END_EXPORT

[[https://github.com/ahisu6/ahisu6.github.io/edit/main/src/rh/001.org][Edit]]

[[file:./index.org][Home]]

[[file:./002.org][Next page >>]]

-----

#+TOC: headlines 2

* Ankylosing spondylitis
:PROPERTIES:
:CUSTOM_ID: org0d7a733
:END:

Posted: 2023-07-20 | Updated: 2023-07-20

This is a disease that causes inflammation in the spine that can lead to stiffness and fusion of the spine making it hard to move. Like a bamboo stick! @@html:<span class="ja">背骨に炎症が起こり、背骨が硬くなったり癒着したりして動きにくくなる病気です。竹の棒のように！</span>@@

This is mainly happens in young men. @@html:<span class="ja">これは主に若い男性に起こる。</span>@@

** Signs and symptoms
:PROPERTIES:
:CUSTOM_ID: org4ae4a08
:END:

- Spine pain:
  - Morning stiffness that improves with activity. @@html:<span class="ja">朝のこわばりは活動によって改善する。</span>@@
  - Pain is worse at night. @@html:<span class="ja">痛みは夜間に悪化する。</span>@@
  - Pain in the butt. @@html:<span class="ja">尻が痛い。</span>@@
  - Decreased spinal movement. @@html:<span class="ja">脊柱の動きの低下。</span>@@
- Pain outside the joints @@html:<span class="ja">関節以外の痛み</span>@@:
  - Acute anterior uveitis (inflammation of the eye). See this [[https://drive.google.com/uc?export=view&id=1bFVmGMLqmv8CHJ4xHbco-p_ow6LGDFhw][picture]]. @@html:<span class="ja">急性前部ぶどう膜炎（眼球の炎症）。</span>@@

** Investigations
:PROPERTIES:
:CUSTOM_ID: org3aa5503
:END:

- X-ray: look at this [[https://drive.google.com/uc?export=view&id=1S2-m5sGzRSQGiHVlK4K7WZFkQcQ4GWge][picture]] for the signs!
- CRP and ESR are both high... of course 笑
- HLA-B27: This is a common exam question.

** Treatment
:PROPERTIES:
:CUSTOM_ID: org35f8c09
:END:

- Keep doing exercise like swimming and do physiotherapy... @@html:<span class="ja">水泳などの運動を続け、理学療法を行う...。</span>@@
- NSAID is the first-line!
- If the patient has pain in places other than the spine, then give them disease-modifying drugs (the same ones we use for rheumatoid arthritis)! @@html:<span class="ja">脊椎以外の場所に痛みがある場合は、疾患修飾薬（関節リウマチに使うものと同じ）を投与する！</span>@@

* Reactive arthritis
:PROPERTIES:
:CUSTOM_ID: org2c0517f
:END:

Posted: 2023-03-19 | Updated: 2023-03-19

Sometimes we get an infection from a certain bacteria. For example: salmonella, campylobacter, or e. coli... @@html:<span class="ja">ある細菌に感染することがあります。例えば、サルモネラ菌、カンピロバクター、大腸菌などです。。。</span>@@

And... @@html:<span class="ja">そして。。。</span>@@

For some weird reason, the knee becomes inflamed... @@html:<span class="ja">変な理由で膝が炎症を起こしてしまう。。。</span>@@

I know... @@html:<span class="ja">分かってるんだ。。。</span>@@

This is VERY weird... lol @@html:<span class="ja">これは非常に奇妙なことだ。。。笑</span>@@

So, make sure you pay attention to the patient history. They might mention that they had an infection less 4 weeks ago!!! @@html:<span class="ja">ですから、患者さんの病歴に注意を払うようにしてください。4週間も前に感染症にかかったというようなことを言われるかもしれません！！！</span>@@

You need to remember that the joint swelling stays for LESS than 6 weeks!!!! @@html:<span class="ja">関節の腫れが6週間弱残ることを忘れてはいけない！！！！</span>@@

** Signs and symptoms
:PROPERTIES:
:CUSTOM_ID: org5607f86
:END:

These are the signs and symptoms:
- Conjunctivitis
- Urethritis
- Arthritis: this happens mainly in the knees and ankles!!!! @@html:<span class="ja">膝や足首を中心に起こる！！！！</span>@@

There is a nice way to remember these signs:
- You can't see (because your eyelids are inflamed). @@html:<span class="ja">見えないんですね(まぶたが炎症を起こしているため)。</span>@@
- You can't pee (because your urethra is inflamed). @@html:<span class="ja">おしっこが出ない(尿道が炎症を起こしているため)。</span>@@
- You can't climb a tree (because of joint pain). @@html:<span class="ja">木に登れない(関節痛のため)。</span>@@

** Investigations
:PROPERTIES:
:CUSTOM_ID: org5227087
:END:

- Usually, you can get the diagnosis from history. @@html:<span class="ja">通常、病歴から診断を得ることができます。</span>@@
- Joint aspiration. @@html:<span class="ja">患部の関節から液体を吸引する。</span>@@

** Treatment
:PROPERTIES:
:CUSTOM_ID: orgbadf955
:END:

- NSAIDs: this will usually solve the issue!!
- IF NSAIDs did not help, then give steroids.
- IF steroids did not help, then give methotrexate.

* Polymyalgia rheumatica and temporal arteritis
:PROPERTIES:
:CUSTOM_ID: org09f9cc9
:END:

Posted: 2023-02-27 | Updated: 2023-05-29

Hi again @@html:<span class="ja">笑。</span>@@

So, doctors think that these two diseases are linked together... @@html:<span class="ja">だから、この2つの病気は連動していると医師は考えているのですが。。。</span>@@

The first disease is "polymyalgia rheumatica". "Poly" means "many". This disease causes joint and muscle pain in the proximal parts of the body (such as shoulders, hips, and trunk. See this [[https://drive.google.com/uc?export=view&id=1886c9sWn4V-uFWD91Q-INZbapK39qMoc][picture]]). It also causes fever and weight loss!!! But... surprisingly, this does /not/ cause weakness! @@html:<span class="ja">1つ目の病気は、「リウマチ性多発筋痛」です。「Poly 」は 「many 」の意味です。この病気は、体の近位部（肩、腰、体幹など）の関節や筋肉の痛みを引き起こします。</span>@@

The second disease is "temporal arteritis". Sometimes, they call this "giant cell arteritis". This is inflammation of carotid artery branches. It mainly affects older people. @@html:<span class="ja">2つ目の病気は、「側頭動脈炎」です。これを「巨細胞性動脈炎」と呼ぶこともあります。頸動脈の枝の炎症です。主に高齢者に発症します。</span>@@

Temporal arteritis might be linked to polymyalgia rheumatica! What do you think? Are they linked or not?

** Signs and symptoms
:PROPERTIES:
:CUSTOM_ID: orgc411550
:END:

- Polymyalgia rheumatica:
  - Proximal pain (such as shoulders and hips). See this [[https://drive.google.com/uc?export=view&id=1886c9sWn4V-uFWD91Q-INZbapK39qMoc][picture]].
  - There is /no/ muscle weakness! The muscles are OKAY! The muscles have /no/ problems! This is very important!!! @@html:<span class="ja">筋力低下がない！筋肉は大丈夫です！筋肉に問題はない！これはとても重要なことです！！！</span>@@
  - Fever
  - Weight loss
  - Sometimes patients have temporal arteritis. @@html:<span class="ja">側頭動脈炎を併発することもある</span>@@

- Temporal arteritis:
  - Fast onset!!!
  - One-sided headache (because of temporal artery inflammation). @@html:<span class="ja">片側だけの頭痛(側頭動脈炎症のため)。</span>@@
  - Vision issues (because of eye artery inflammation). @@html:<span class="ja">視力の問題(眼動脈の炎症のため)。</span>@@
  - Jaw pain. @@html:<span class="ja">顎の痛み。</span>@@

** Investigations
:PROPERTIES:
:CUSTOM_ID: orga0fcea5
:END:

- Check inflammation tests like CRP and ESR. These will be /very/ high!
- If you think the patient has temporal arteritis, then take a biopsy from the temporal artery: if temporal arteritis is present, then you will see fibrosis! @@html:<span class="ja">側頭動脈炎と思われる場合は、側頭動脈から生検を行います: 側頭動脈炎があれば、線維化が見られるはずです！</span>@@

** Treatment
:PROPERTIES:
:CUSTOM_ID: orgff3c1c8
:END:

Just give the patient prednisolone, and you should be good to go! @@html:<span class="ja">プレドニゾロンを飲ませれば大丈夫！</span>@@

- Polymyalgia rheumatica:
  - Give the patient 15 mg of prednisolone per day. @@html:<span class="ja">プレドニゾロン1日15mgを投与してください。</span>@@
  - Just remember the prednisolone. Don't worry too much about the dose! @@html:<span class="ja">プレドニゾロンだけは覚えておいてください。投与量についてはあまり気にしないでください！</span>@@

- Temporal arteritis:
  - This is an emergency!! @@html:<span class="ja">これは緊急事態だ！！</span>@@
  - Do /not/ panic!!!!!!!!!!! @@html:<span class="ja">慌てないでください！！！！！！！！！！！</span>@@
  - Give the patient high-dose prednisolone right now! @@html:<span class="ja">今すぐ高用量のプレドニゾロンを投与してください！</span>@@
    - This is usually 60 mg... @@html:6 = む and 0 = ま... え～と... むま？<mark>夢魔</mark>！わ！！夢魔 = nightmare!!! 夢魔ですよ！そんな辛い経験をすることは、<mark>夢魔</mark>のようなことなのでしょう！この夢魔を取り除くためには、<mark>60</mark>mgの薬を投与しなければならない。@@
  - If the patient has /vision issues/, then give /IV methylprednisolone/ before you give the normal prednisolone!!! @@html:<span class="ja">もし、患者に視力の問題があるなら、通常のプレドニゾロンを投与する前に、メチルプレドニゾロンを点滴してください！！！</span>@@
