#+TITLE: Rheumatology 001

#+BEGIN_EXPORT html
<div class="engt">Rheumatology</div>
<div class="japt">リウマチ学</div>
<div class="engt">Page 001</div>
#+END_EXPORT

[[https://github.com/ahisu6/ahisu6.github.io/edit/main/src/rh/001.org][Edit]]

[[file:./index.org][Home]]

[[file:./002.org][Next page >>]]

-----

#+TOC: headlines 2

* Polymyalgia rheumatica and temporal arteritis
:PROPERTIES:
:CUSTOM_ID: org09f9cc9
:END:

Posted: 2023-02-27 | Updated: 2023-02-27

Hi again @@html:<span class="jp">笑。</span>@@

So, doctors think that these two diseases are linked together... @@html:<span class="jp">だから、この2つの病気は連動していると医師は考えているのですが。。。</span>@@

The first disease is "polymyalgia rheumatica". "Poly" means "many". This disease causes joint and muscle pain in the proximal parts of the body (such as shoulders, hips, and trunk. See this [[https://lh3.googleusercontent.com/pw/AMWts8BI-ZJxhPuQpNUOWbRBKg13W617xaIXRqwx4CxS-1f5MIzRir-qV2hksuoMiLEur-v-bzvjg_u-wxSPVywuNtxgE6Y9NkJX8zhjYtRLNHlF8y3PM5-qiAAhM-SBUK2vhW7ni39ZRlrxJ-id0LT_SSFw=w483-h914-no?authuser=1][picture]]). It also causes fever and weight loss!!! But... surprisingly, this does /not/ cause weakness! @@html:<span class="jp">1つ目の病気は、「リウマチ性多発筋痛」です。「Poly 」は 「many 」の意味です。この病気は、体の近位部（肩、腰、体幹など）の関節や筋肉の痛みを引き起こします。</span>@@

The second disease is "temporal arteritis". Sometimes, they call this "giant cell arteritis". This is inflammation of carotid artery branches. It mainly affects older people. @@html:<span class="jp">2つ目の病気は、「側頭動脈炎」です。これを「巨細胞性動脈炎」と呼ぶこともあります。頸動脈の枝の炎症です。主に高齢者に発症します。</span>@@

Temporal arteritis might be linked to polymyalgia rheumatica! What do you think? Are they linked or not?

** Signs and symptoms
:PROPERTIES:
:CUSTOM_ID: orgc411550
:END:

- Polymyalgia rheumatica:
  - Proximal pain (such as shoulders and hips). See this [[https://lh3.googleusercontent.com/pw/AMWts8BI-ZJxhPuQpNUOWbRBKg13W617xaIXRqwx4CxS-1f5MIzRir-qV2hksuoMiLEur-v-bzvjg_u-wxSPVywuNtxgE6Y9NkJX8zhjYtRLNHlF8y3PM5-qiAAhM-SBUK2vhW7ni39ZRlrxJ-id0LT_SSFw=w483-h914-no?authuser=1][picture]].
  - There is /no/ muscle weakness! The muscles are OKAY! The muscles have /no/ problems! This is very important!!! @@html:<span class="jp">筋力低下がない！筋肉は大丈夫です！筋肉に問題はない！これはとても重要なことです！！！</span>@@
  - Fever
  - Weight loss
  - Sometimes patients have temporal arteritis. @@html:<span class="jp">側頭動脈炎を併発することもある</span>@@

- Temporal arteritis:
  - Fast onset!!!
  - One-sided headache (because of temporal artery inflammation). @@html:<span class="jp">片側だけの頭痛(側頭動脈炎症のため)。</span>@@
  - Vision issues (because of eye artery inflammation). @@html:<span class="jp">視力の問題(眼動脈の炎症のため)。</span>@@
  - Jaw pain. @@html:<span class="jp">顎の痛み。</span>@@

** Investigations
:PROPERTIES:
:CUSTOM_ID: orga0fcea5
:END:

- Check inflammation tests like CRP and ESR. These will be /very/ high!
- If you think the patient has temporal arteritis, then take a biopsy from the temporal artery: if temporal arteritis is present, then you will see fibrosis! @@html:<span class="jp">側頭動脈炎と思われる場合は、側頭動脈から生検を行います: 側頭動脈炎があれば、線維化が見られるはずです！</span>@@

** Treatment
:PROPERTIES:
:CUSTOM_ID: orgff3c1c8
:END:

Just give the patient prednisolone, and you should be good to go! @@html:<span class="jp">プレドニゾロンを飲ませれば大丈夫！</span>@@

- Polymyalgia rheumatica:
  - Give the patient 15 mg of prednisolone per day. @@html:<span class="jp">プレドニゾロン1日15mgを投与してください。</span>@@
  - Just remember the prednisolone. Don't worry too much about the dose! @@html:<span class="jp">プレドニゾロンだけは覚えておいてください。投与量についてはあまり気にしないでください！</span>@@

- Temporal arteritis:
  - This is an emergency!! @@html:<span class="jp">これは緊急事態だ！！</span>@@
  - Do /not/ panic!!!!!!!!!!! @@html:<span class="jp">慌てないでください！！！！！！！！！！！</span>@@
  - Give the patient high-dose prednisolone right now! @@html:<span class="jp">今すぐ高用量のプレドニゾロンを投与してください！</span>@@
  - If the patient has /vision issues/, then give /IV methylprednisolone/ before you give the normal prednisolone!!! @@html:<span class="jp">もし、患者に視力の問題があるなら、通常のプレドニゾロンを投与する前に、メチルプレドニゾロンを点滴してください！！！</span>@@
