#+TITLE: Learn

#+BEGIN_EXPORT html
<div class="engt">Learn</div>
<div class="japt">学ぶ</div>
<div class="engt">Page 001</div>
#+END_EXPORT

[[https://github.com/ahisu6/ahisu6.github.io/edit/main/src/learn/001.org][Edit]]

[[file:../index.org][Home]]

-----

#+TOC: headlines 2

* 繰り返し、記憶する
:PROPERTIES:
:CUSTOM_ID: org4279268
:END:

If you have tried writing and drawing things, and you thought that it is not useful, then you can ignore this advice!!!! @@html:<span class="ja">もし、あなたが物を書いたり描いたりしてみて、役に立たないと思ったのであれば、このアドバイスは無視していただいて結構です！！！！</span>@@

However, repeating things must be followed. This is the most efficient way for humans to learn quickly. @@html:<span class="ja">ただし、物事を繰り返すことは、必ず守らなければならない。これは、人間が素早く学ぶための最も効率的な方法です。</span>@@

This is probably basic stuff for you. @@html:<span class="ja">これは、あなたにとって基本的なことでしょう。</span>@@

But, I do not want to assume that you know this. So, I will write it here just as a reminder. @@html:<span class="ja">しかし、私は、あなたがすでに知っていると決めつけたくはない。だから、念のためここに書いておく。</span>@@

It is so important to repeat the things over and over again. @@html:<span class="ja">何度も何度も繰り返すことがとても大切なのです。</span>@@

Not only that, but they must be repeated over a long period of time. @@html:<span class="ja">それだけでなく、長期間にわたって繰り返されなければならない。</span>@@

The stories which I create for you must be repeated frequently. Otherwise, you will forget them. @@html:<span class="ja">私があなたのために作った物語は、頻繁に繰り返されなければならない。そうでなければ、忘れてしまうでしょう。</span>@@

However, the good thing about these strange stories is that they will require less repetition. This is because they are weird. Weird things will stick in your mind better. @@html:<span class="ja">しかし、これらの奇妙な話の良いところは、あなたが頻繁に繰り返す必要がないことです。なぜなら、それらは奇妙なものだからです。変なものの方が心に残るのです。</span>@@

Believe me. @@html:<span class="ja">私を信じてください。</span>@@

Another thing is writing. For example, when I tell you about a new fact, you must write it down on a piece of paper. Write it a couple of times. @@html:<span class="ja">もうひとつは、書くことです。例えば、私が新しい事実を話したら、それを紙に書かなければなりません。2、3回書いてみてください。</span>@@

For example: levothyroxine is used to treat HYPOthryoidism. @@html:<span class="ja">例：レボチロキシンは、甲状腺機能低下症の治療に使用されます。</span>@@

You do not have to write the entire sentence. Just pick out the main idea. @@html:<span class="ja">文章を全部書く必要はありません。メインアイデアを拾い出すだけでいい。</span>@@

In the example above, you can write the following: "levothyroxine treats HYPOthryoidism". @@html:<span class="ja">上の例では、次のように書けます: 「レボサイロキシンは、甲状腺の活動低下を治療するものです。」</span>@@

Now, you need to write this one a piece of paper or on an iPad. Choose whatever you are comfortable with. @@html:<span class="ja">さて、これを紙かiPadに書いてください。自分がやりやすいものを選んでください。</span>@@

Writing things will force your brain to focus. It will make your brain learn the information better. @@html:<span class="ja">ものを書くことで、脳が強制的に集中する。それはあなたの脳が情報をよりよく学ぶようになります。</span>@@

Same thing with drawing funny and weird pictures. These will help you remember things. @@html:<span class="ja">面白い絵や変な絵を描くのも同じです。これらは物事を覚えるのに役立ちます。</span>@@

Keep writing. Keep drawing. And, more importantly, keep repeating! @@html:<span class="ja">書き続ける。描き続ける。そして、もっと大切なのは、繰り返し続けることだ！</span>@@

Keep writing. Keep drawing. And, more importantly, keep repeating! @@html:<span class="ja">書き続ける。描き続ける。そして、もっと大切なのは、繰り返し続けることだ！</span>@@

Keep writing. Keep drawing. And, more importantly, keep repeating! @@html:<span class="ja">書き続ける。描き続ける。そして、もっと大切なのは、繰り返し続けることだ！</span>@@

Keep writing. Keep drawing. And, more importantly, keep repeating! @@html:<span class="ja">書き続ける。描き続ける。そして、もっと大切なのは、繰り返し続けることだ！</span>@@

Keep writing. Keep drawing. And, more importantly, keep repeating! @@html:<span class="ja">書き続ける。描き続ける。そして、もっと大切なのは、繰り返し続けることだ！</span>@@

Keep writing. Keep drawing. And, more importantly, keep repeating! @@html:<span class="ja">書き続ける。描き続ける。そして、もっと大切なのは、繰り返し続けることだ！</span>@@

ひひひひ、ごめん...。

* 語呂合わせの表
:PROPERTIES:
:CUSTOM_ID: org7e93de5
:END:

This is a table of goroawase. I am putting this table here to make it easier for you to create your own story.  @@html:<span class="ja">これは、語呂合わせの表です。私は、あなたが自分のストーリーを作りやすいように、この表をここに置いています。</span>@@

| 命数法       | 訓読み           | 音読み           | 英語             |
|--------------+------------------+------------------+------------------|
| 0, 〇, 零    | ま, まる, わ     | れ, れい         | オ, ゼ, ゼロ     |
| 1, 一, 壹/壱 | ひ, ひと, ひとつ | い, いち         | ワン             |
| 2, 二, 貳/弐 | ふ, ふた, ふたつ | に, じ           | ツー, トゥー     |
| 3, 三, 參/参 | み, みつ         | さ, さん         | スリー           |
| 4, 四, 肆    | よ, よん, よつ   | し               | フォー           |
| 5, 五, 伍    | いつ, いつつ     | ご, こ           | ファイブ         |
| 6, 六, 陸    | む, むつ         | ろ, ろく         | シックス         |
| 7, 七, 柒    | な, なな, ななつ | ち, しち         | セ, ゼ, セブン   |
| 8, 八, 捌    | や, やつ         | は, ば, はち     | エ, エイ, エイト |
| 9, 九, 玖    | こ, ここのつ     | く, きゅ, きゅう | ナイン           |
| 10, 十, 拾   | と, とお         | じ, じゅう       | テ, テン         |
| ., 点        | テン             | (decimal point)  |                  |

** Resources
:PROPERTIES:
:CUSTOM_ID: orga66a124
:END:

Here are some useful websites for you:
- [[http://www2u.biglobe.ne.jp/~b-jack/bn/pken.html]] - you can put numbers in this website, and it will create goroawase for you. This is a really good website. I recommend that you use it. @@html:<span class="ja">このサイトに数字を入れると、あなたの語呂合わせを作ってくれるんです。これは本当に良いサイトです。私はあなたに使うように勧めています。</span>@@
- [[https://terakoya.ameba.jp/a000001596/]] - this website teaches you how to use goroawase. @@html:<span class="ja">このサイトでは、語呂合わせの使い方を紹介しています。</span>@@
- [[https://seoi.net/goro/]] - this is another website which can create goroawase for you. @@html:<span class="ja">こちらもあなたの語呂合わせを作成することができるサイトです。</span>@@

