#+TITLE: Cardiology 001

#+BEGIN_EXPORT html
<div class="engt">Cardiology</div>
<div class="japt">循環器学</div>
<div class="engt">Page 001</div>
#+END_EXPORT

[[https://github.com/ahisu6/ahisu6.github.io/edit/main/src/c/001.org][Edit]]

[[file:./index.org][Home]]

[[file:./002.org][Next page >>]]

-----

#+TOC: headlines 2

* Adults advanced life support
:PROPERTIES:
:CUSTOM_ID: orga7eff00
:END:

Posted: 2023-09-19 | Updated: 2023-09-19

Ok, so here are the steps in case someone needs CPR. @@html:<span class="ja">では、CPRが必要な人がいた場合の手順を説明しよう。</span>@@

1. Call for help!!! @@html:<span class="ja">助けを呼ぶ！！！</span>@@
2. First, we have to start with chest compressions. We need to give 30 chest compressions, and then give 2 bag ventilations. @@html:<span class="ja">まずは胸骨圧迫から。胸骨圧迫を30回行い、次にバッグベンチレーションを2回行う。</span>@@
3. Get the defibrillator. @@html:<span class="ja">除細動器を持ってきてください。</span>@@
   - If the patient has ventricular fibrillation or ventricular tachycardia, then you 1 defibrillator shock. After that, you need to do CPR for 2 minutes. @@html:<span class="ja">心室細動や心室頻拍があれば、除細動器ショックを1回行う。その後、2分間の心肺蘇生が必要です。</span>@@
   - If you saw the patient when they collapsed, then you need to give 3 defibrillator shocks. @@html:<span class="ja">患者が倒れたのを見たなら、除細動器によるショックを3回与える必要がある。</span>@@
4. Next, we need to put a cannula in the patient. @@html:<span class="ja">次に、患者にカニューレを入れる必要がある。</span>@@
   - If you can't put a cannula, then you have to put the drugs in the bone (intraosseous). @@html:<span class="ja">カニューレを入れられない場合は、骨の中に薬剤を入れなければならない（骨内注射）。</span>@@
5. If the patient does not have a pulse, then you should give 1 mg of adrenaline now. @@html:<span class="ja">脈がない場合は、アドレナリンを1mg投与する。</span>@@
6. If the patient has ventricular fibrillation or ventricular tachycardia, then you should give adrenaline after you have started chest compressions for the 4th time. So... @@html:<span class="ja">心室細動や心室頻拍がある場合は、4回目の胸骨圧迫を開始した後にアドレナリンを投与します。それで...</span>@@
   1. Compression
   2. 1st shock
   3. Compression
   4. 2nd shock
   5. Compression
   6. 3rd shock
   7. Compression plus adrenaline!
7. Keep giving adrenaline doses every 3 minutes. @@html:<span class="ja">アドレナリンを3分ごとに投与し続ける。</span>@@
8. If that still does not help, then you should givee 300 mg of amiodarone. @@html:<span class="ja">それでもだめなら、アミオダロンを300mg投与する。</span>@@
9. If you gave 5 shocks, then you should give another dose of amiodarone (150 mg). @@html:<span class="ja">もし5回のショックを行ったなら、アミオダロン（150mg）をもう1回投与すべきである。</span>@@

* Ventricular tachycardia
:PROPERTIES:
:CUSTOM_ID: org8736e77
:END:

Posted: 2023-07-29 | Updated: 2023-07-29

This is a tachycardia in the ventricles (lower part of the heart). @@html:<span class="ja">これは心室（心臓の下部）の頻脈である。</span>@@

In ventriclar tachycardia, the QRS complex looks very, very, very, very, weird. Look at this [[https://drive.google.com/uc?export=view&id=161RIsOdJa5dKYkdgFqLd6G9xQVD4e1Qi][picture]]. @@html:<span class="ja">心室性頻拍では、QRS複合体は非常に、非常に、非常に、非常に、非常に、奇妙に見える。</span>@@

This is a very serious disease. @@html:<span class="ja">これは非常に危険な病気だ。</span>@@

You need to act very fast. @@html:<span class="ja">早急に対処する必要がある。</span>@@

** Signs and symptoms
:PROPERTIES:
:CUSTOM_ID: org446a8bc
:END:

- Similar to the supraventriclar tachycardia...
- ドキドキドキドキドキドキ。
- Dizzy.
- Low blood pressure.

** Investigations
:PROPERTIES:
:CUSTOM_ID: org8964079
:END:

- ECG...

** Treatment
:PROPERTIES:
:CUSTOM_ID: org5676e96
:END:

See this [[https://drive.google.com/uc?export=view&id=1AybyhTpQQz4iWlqLvPCxyi8YYbJK3QGd][picture]] of a chart that explains the treatment in a nice way.

Sometimes, the ventriclar tachycardia can cause a lot of serious problems. If these problems happen, then you need to give an electric shock (DC cardioversion). @@html:<span class="ja">時には、心室頻拍が多くの深刻な問題を引き起こすことがあります。このような場合は、電気ショック（直流除細動）を行う必要があります。</span>@@

Here are examples of some of these serious issues @@html:<span class="ja">これらの深刻な問題の例をいくつか挙げてみよう</span>@@:
1. Systolic blood pressure less than 90 mmHg: this is because the ventricles are very fast and therefore not efficient. @@html:<span class="ja">収縮期血圧が90mmHg未満：これは心室が非常に速く、効率が悪いためである。</span>@@
2. Losing conciousness: this is because there is not enough blood going to the brain. @@html:<span class="ja">意識を失う：これは脳に行く血液が足りないからだ。</span>@@
3. Heart failure: because the ventricles are beating very fast, the heart will be tired and it will fail. @@html:<span class="ja">心不全：心室は非常に速く拍動しているため、心臓は疲れてしまい、機能しなくなる。</span>@@

If the patient has serious issues, then you need to give electric shock (DC cardioversion). @@html:<span class="ja">患者に深刻な問題がある場合は、電気ショック（直流除細動）を与える必要がある。</span>@@

But... if the patient is stable, then you should give IV amiodarone! @@html:<span class="ja">しかし... 患者が安定しているのであれば、アミオダロンを静注するべきです！</span>@@

You said you are confused about the difference between ventriclar and supraventriclar tachycardia treatment. Here is a [[https://drive.google.com/uc?export=view&id=14ZEmwRWAZaIgSnUCb2Vfc-I2SuioA1Yq][picture]] to compare ventriclar and supraventriclar tachycardia.

* Supraventricular tachycardia
:PROPERTIES:
:CUSTOM_ID: orgf0aee00
:END:

Posted: 2023-07-29 | Updated: 2023-07-29

The word "supra" means "above". So, this is tachycardia /above/ the ventricles. @@html:<span class="ja">「supra」とは「上」という意味です。つまり、これは心室の上の頻脈である。</span>@@

Supraventricular tachycardia means that the top part of the heart is beating very fast. @@html:<span class="ja">上室性頻拍とは、心臓の上部の拍動が非常に速いことを意味する。</span>@@

Usually, supraventricular tachycardia is not dangerous. @@html:<span class="ja">通常、上室性頻拍は危険ではない。</span>@@

But... sometimes, supraventricular tachycardia can be very bad. So, the patient might collapse and lose consciousness. @@html:<span class="ja">しかし... 時には上室性頻拍が非常に悪化することもあります。そのため、患者は倒れて意識を失うかもしれません。</span>@@

Supraventricular tachycardia happens because there are extra fibres that are conducting electricity in the heart. This extra electricity makes the heart beat faster. @@html:<span class="ja">上室性頻拍は、心臓に電気を通す線維が余分にあるために起こる。この余分な電気が心臓の拍動を速くします。</span>@@

** Signs and symptoms
:PROPERTIES:
:CUSTOM_ID: orgd792002
:END:

- Palpitations: ドキドキドキドキドキドキドキドキドキドキドキドキ...。
- Chest pain.
- Breathing difficulty.
- Dizzy.
- Collapse.

** Investigations
:PROPERTIES:
:CUSTOM_ID: org340ad6a
:END:

- ECG, of course!
- See if the patient is stable.

** Treatment
:PROPERTIES:
:CUSTOM_ID: orgf6e0bbe
:END:

See this [[https://drive.google.com/uc?export=view&id=1jvczzGpKX-PqTGs0SNaWEdHoi3bHGITp][picture]] of a chart that explains the treatment in a nice way.

First, you need to check if the patient is stable. @@html:<span class="ja">まず、患者が安定しているかどうかを確認する必要がある。</span>@@

If the patient is stable, then you need to do the following @@html:<span class="ja">患者が安定している場合は、次のことを行う必要がある</span>@@:
1. Vagal manoeuvres: these are things you do to stimulate the vagus nerve. the vagus nerve will reduce the heart rate. There are two examples @@html:<span class="ja">迷走神経操作：迷走神経を刺激するために行うもので、迷走神経が心拍数を低下させる。次の2つの例がある。</span>@@
  - Carotid sinus massage: in here, you will give the patient a massage on the neck. See this [[https://drive.google.com/uc?export=view&id=1bgLA4k5Gz9ApDbCAODWW9kf5HbK5elxS][picture]]. @@html:<span class="ja">頸動脈洞マッサージ：ここでは、患者に首のマッサージを行う。</span>@@
  - Valsalva manoeuvre: in here, you will ask the patient to blow air into an empty syringe. See this [[https://drive.google.com/uc?export=view&id=16V4HVQMTOcVg6atzE4LhJftcSIjwKMwj][picture]]. @@html:<span class="ja">バルサルバ法：空の注射器に空気を吹き込んでもらう。</span>@@
2. If vagal manoeuvres did not work, then you should give adenosine. @@html:<span class="ja">迷走神経操作が効かない場合は、アデノシンを投与する。</span>@@
  - Start with 6 mg of adenosine. @@html:<span class="ja">アデノシン6mgから開始する。</span>@@
  - If that did not work, then give 12 mg of adenosine. @@html:<span class="ja">それでもだめなら、アデノシンを12mg投与する。</span>@@
  - Finally, if that did not work, then give 18 mg of adenosine! @@html:<span class="ja">それでもだめなら、アデノシンを18mg投与する！</span>@@
3. Now... let's say that the adenosine did not work. What should you do? Give the patient DC cardioversion. This is an electric shock to the heart! @@html:<span class="ja">さて... アデノシンが効かなかったとしよう。どうしますか？患者に直流除細動を行います。これは心臓に電気ショックを与えます！</span>@@

If the patient is unstable (for example, if the patient loses consciousness), then you need to skip all of the steps above, and do DC cardioversion straight away. @@html:<span class="ja">患者が不安定な場合（例えば、意識を失った場合）には、上記のステップをすべて飛ばして、すぐにDC除細動を行う必要があります。</span>@@

So... let's say a patient comes to the A&E with supraventricular tachycardia. Then, few seconds later, the patient collapsed. The first line treatment in this case is... DC cardioversion!!!! @@html:<span class="ja">つまり...ある患者が上室性頻拍でA&Eに来たとする。それから数秒後、患者は倒れた。この場合の第一選択治療は... 直流除細動です！！！！</span>@@

So... we can give the patient some drugs that prevent supraventricular from coming again @@html:<span class="ja">ですから... 患者に上室性の再発を防ぐ薬を投与することができます</span>@@
- Beta-blockers: these will slow the heart rate down. @@html:<span class="ja">これらは心拍数を遅くする。</span>@@
- Radio-frequency ablation: this will burn the extra fibres in the heart. @@html:<span class="ja">これは心臓の余分な繊維を燃やすことになる。</span>@@
