#+TITLE: Paediatrics 001

#+BEGIN_EXPORT html
<div class="engt">Paediatrics</div>
<div class="japt">小児科学</div>
<div class="engt">Page 001</div>
#+END_EXPORT

[[https://github.com/ahisu6/ahisu6.github.io/edit/main/src/p/001.org][Edit]]

[[file:./index.org][Home]]

[[file:./002.org][Next page >>]]

-----

#+TOC: headlines 2

* Viral rashes in kids
:PROPERTIES:
:CUSTOM_ID: org013ca3b
:END:

Posted: 2023-04-30 | Updated: 2023-04-30

Ok.

Are you ready for the most annoying topic? No? Well, too bad...

I will talk about viral rashes in children. @@html:<span class="ja">今回は、子どものウイルス性発疹についてお話しします。</span>@@

You only need to know a few!
- Hand-foot-mouth disease
- Varicella (chickenpox)
- Measles
- Rubella
- Roseola infantum
- Erythema infectiosum

Don't worry, they're all easy.

I will add pictures for you to make it easier! @@html:<span class="ja">どれも簡単なのでご安心ください！</span>@@

** Hand-foot-mouth disease
:PROPERTIES:
:CUSTOM_ID: orgf6158ba
:END:

- Caused by coxsackie A virus. Look at this [[https://lh3.googleusercontent.com/pw/AJFCJaX8QXRdUJjWuWp1apwU7VVzigFGcb_CE6HmhB80lio_dIrLS62of62kT_yNZ_ItrtfMORkvITNh_PBcY5YIgDTpfod_ghuNS4OidzqsNiv-aH53cVESMU2Nqu4Q2vLvPiy62iFDZhVFaqgEmQGEAroK=w600-h600-s-no?authuser=1][picture]]!

- Symptoms are mild. @@html:<span class="ja">症状は軽度です。やった！</span>@@
- First, they get fever and mouth ulcers... @@html:<span class="ja">まず、子供が熱を出し、口内炎ができる。。。</span>@@
- Thennnnn, after a short period of time, spots on the hand will appear. Look at this [[https://lh3.googleusercontent.com/pw/AJFCJaW8XxUT_2NrTnVhuycLhY9zHDx73joEBNDs3jnILozl4e9ZU9T8iys9xNN5tptt514hnrchkSVqa5P9wncedfyblEmJ39Luq7XqoCyKwaBHr_N9QllFtihFeT5jRPjYs72jROoAQM_KY21PuXcf1cSn=w650-h428-s-no?authuser=1][picture]]. @@html:<span class="ja">その後、しばらくすると、手に点状の病変が現れます。</span>@@

- Supportive treatment!

** Varicella (chickenpox)
:PROPERTIES:
:CUSTOM_ID: org486ecb5
:END:

- Caused by varicella zoster virus (VZV).
- It is infectious during the first 4 days /before/ the rash. And, it will stay infectious for 5 days /after/ the rash!!! @@html:<span class="ja">発疹が出る前の4日間は感染力があります。そして、発疹が出た後5日間は感染力があります！！！</span>@@

- Fever!
- It is suuuuuuuuuuuuuper itchy. I remember when I had it as a kid. PAIN!!!! Sooooo itchy! @@html:<span class="ja">超かゆいです。子供のころにあったのを思い出しました。いたみ！というくらい痒い！</span>@@

- Supportive treatment!
- Keep the kid at home! Do not send the kid to school!!!! @@html:<span class="ja">子供を家に置いておけ！子供を学校に行かせないでください！！！！</span>@@
- Calamine lotion!
- If the patient is immunocompromised, then give them varicella zoster immunoglobulin!!!! And, when they develop chickenpox, give them IV aciclovir!!!!!!!! @@html:<span class="ja">免疫不全の場合は、水痘帯状疱疹免疫グロブリンを投与します！そして、水痘を発症したら、アシクロビルを点滴で投与する！</span>@@

- It can cause encephalitis and pneumonia!

** Measles
:PROPERTIES:
:CUSTOM_ID: org4b78e54
:END:

- Caused by... measles virus...

- This has 3 phases:
  1. Prodromal phase
  2. Rash phase
  3. Cough phase
- Prodromal phase signs:
  - /High/ fever!!!
  - @@html:<mark>Co</mark>ryza: blocked nose!@@
  - @@html:<mark>Co</mark>njuctivits: eyelid inflammation@@
  - @@html:<mark>Co</mark>ugh: cough is... cough!@@
  - @@html:<mark>Ko</mark>plik spots: these look like salt.........@@ Look at this [[https://lh3.googleusercontent.com/pw/AJFCJaWZrZ6EI9YeGyuZ261tC-K41IL4T0vS-hhIvBY7OlgyS2h9l9eWveVtXgLELwRXC8gSeZQQsvl7_iXt-iO0VpURprDiWwmiYGhiWU-EDn0f52ET5fbq4sfKkRe85Ha8xZp8xQdF5wgIWBKzH0yZiEM5=w240-h235-s-no?authuser=1][picture]].
  - @@html:Look! They all have the <span class="ja">こ</span> sound! <span class="ja">こここここここここここここ....</span> If you see a lot of <span class="ja">こ</span>, then it must be measles! Quick, run away!!!! <mark>こ</mark>わいですよ！大怖い！！！！@@
- Rash phase signs:
  - Patient will get rash all over the body. @@html:<span class="ja">全身に発疹が出る。</span>@@
  - Buuuuuuuuut, there is /no/ rash on their hands and feet!! @@html:<span class="ja">しかし、患者さんの手や足には発疹はありません！！！</span>@@

- @@html:You can test for <mark>m</mark>easles by using Ig<mark>M</mark> antibodies. Notice the M!@@

- Supportive treatment!!!
- Measles is a notifiable disease. So, report it!!!!
- If you come in contact with measles, then you should take the MMR vaccine with 72 hours!!! @@html:<span class="ja">麻疹に接触した場合は、72時間以内にMMRワクチンを摂取する必要があります！！！</span>@@

- @@html:<mark>M</mark>easles can cause: otitis <mark>m</mark>edia and pneu<mark>m</mark>onia! Notice the M! Mmmmmmmmmm 笑@@

** Rubella
:PROPERTIES:
:CUSTOM_ID: orgc6e49cc
:END:

- Caused by... rubella virus...

- Flu-like symptoms.
- Maculopapular rash.
  - Buuuuuuuuut, there is /no/ rash on their hands and feet!! @@html:<span class="ja">しかし、患者さんの手や足には発疹はありません！！！</span>@@
- Lymph node swelling behind the head and behind the ear. @@html:<span class="ja">頭の後ろ、耳の後ろのリンパ節が腫れる。</span>@@

- You can use IgM to find out if the person has rubella. @@html:<span class="ja">IgMで風疹かどうかを調べることができます。</span>@@

- Supportive treatment!

- Rubella can lead to joint issues and low platelet levels! @@html:<span class="ja">風疹は、関節の問題や血小板の低下を招くことがあります！</span>@@
- Rubella can be passed from pregnant woman to fetus. If that happens, then the baby will get something called "congenital rubella syndrome" @@html:<span class="ja">風疹は、妊婦から胎児にうつる可能性があります。そうなれば、赤ちゃんは 「先天性風疹症候群」と呼ばれるものになります。</span>@@
  - The baby will have cataracts, deafness, and heart issues!! Remember those! Ear, eyes, and heart!!!! @@html:<span class="ja">赤ちゃんは白内障、難聴、心臓に問題がある！これらを思い出してください！耳、目、心臓。</span>@@
  - You can read [[https://ja.wikipedia.org/wiki/%E5%85%88%E5%A4%A9%E6%80%A7%E9%A2%A8%E7%96%B9%E7%97%87%E5%80%99%E7%BE%A4][this]] for more information.

** Erythema infectiosum
:PROPERTIES:
:CUSTOM_ID: orgcf59002
:END:

- Caused by parvovirus B19.
- @@html:<mark>P</mark>arvovirus B19 causes sl<mark>pp</mark>ed cheeks! Look at the letter P@@
- This is the smallest human virus... smol... @@html:<span class="ja">これは、最小のヒトウイルス... スモールですね！</span>@@
- This type of virus affect the blood of the person. So, if the patient has blood problem (like anaemia, sickle-cell disease, etc.), then they will have worse symptoms!!!! @@html:<span class="ja">このタイプのウイルスは、人の血液に影響を及ぼします。そのため、患者さんが血液の問題(貧血や鎌状赤血球症など)を抱えている場合、症状が悪化します！</span>@@

- First, the child gets fever.
- After the fever the cheeks will have a red rash. Look at this [[https://lh3.googleusercontent.com/pw/AJFCJaWqIWBWKYk-BOk9OoriKwqK2xF6jJtjbNCC_iI1ajiLZ0kCX5EbKs7XOgIiYOQ4Js-iQ3LxrtjXuWBU0yaeaLG43FWrTKBPgdpP44LIjhZz0he-of_PMgOT5FIhDbS2hfqP5XuhdF_GxisdKkiwmZ9x=w320-h203-s-no?authuser=1][picture]]. @@html:<span class="ja">発熱後、頬に赤い発疹ができる... トマトですね</span>@@
- Sometimes, warm things will also make the cheeks red... so smol. @@html:<span class="ja">時には、暖かいものも頬を赤くする... 大スモールですね。</span>@@
- @@html:It looks like someone sla<mark>pp</mark>ed the baby... Remember, <mark>p</mark>arvovirus B19 causes sl<mark>pp</mark>ed cheeks! Look at the letter P! <span class="ja">誰かが赤ちゃんをひっぱたいたように見える...。</span>@@
- When the rash appears, the child will no longer be infectious!!! @@html:<span class="ja">発疹が出たら、その子はもう感染力はありません！！！伝染性紅斑の場合、発疹が出た後、他の人に感染することはありません。だから、発疹が出た時点で、その子はもう他人に感染させることができないのだと覚えておいてください。やった！！！</span>@@
- If the patient has sickle-cell disease (it is a disease which affects the blood), then they will have a crisis!!! @@html:<span class="ja">もし患者さんが鎌状赤血球症(血液に影響を与える病気です)であれば、危機を迎えます！！！</span>@@

- If a pregnant woman get this disease, then the baby will have a condition called "hydrops fetalis". @@html:<span class="ja">妊婦がこの病気にかかると、赤ちゃんは「胎児水腫 / hydrops fetalis」と呼ばれる状態になります。</span>@@
  - This is when there is swelling all over the body. @@html:<span class="ja">全身に腫れがある場合です。</span>@@
  - Look at this [[https://lh3.googleusercontent.com/pw/AJFCJaWqIWBWKYk-BOk9OoriKwqK2xF6jJtjbNCC_iI1ajiLZ0kCX5EbKs7XOgIiYOQ4Js-iQ3LxrtjXuWBU0yaeaLG43FWrTKBPgdpP44LIjhZz0he-of_PMgOT5FIhDbS2hfqP5XuhdF_GxisdKkiwmZ9x=w320-h203-s-no?authuser=1][picture]].
  - This is another [[https://lh3.googleusercontent.com/pw/AJFCJaWp2YyNDFyvi7jrIT-SuO5aaDGqzFBvqrIIEUgNpZKurZeblcdu3mGfpbMc0BOJ6IQbymhmpypWz_9AlzcwpSBAWIBQmIP-3O7FjFl4dThl-cCzqOPeXUoCgXELObPKJgrbDUS59iL1KtQQXymTHHwZ=w1270-h954-s-no?authuser=1][picture]].

** Roseola infantum
:PROPERTIES:
:CUSTOM_ID: org1d62bf4
:END:

- Caused by human herpes virus 6.

- First, the child gets fever for few days. Sometimes the baby might get febrile convulsions! So, pay attention! @@html:<span class="ja">まず、数日間熱が出ます。時には、熱性けいれんを起こすこともあります！だから、注意してください！</span>@@
- After the fever goes away, the child gets rose-coloured maculopapular rash! @@html:<span class="ja">熱が下がった後、バラ色の斑点状皮疹が現れます！</span>@@
- Here is a fun way to remember it: poor baby... first the baby got fever, and then later someone brought some roses for the baby... @@html:<span class="ja">かわいそうな赤ちゃん...まず赤ちゃんが熱を出し、その後誰かが赤ちゃんにバラの花を持ってきた...という楽しい覚え方です。</span>@@

- Supportive treatment: so, reduce the temperature!
