#+TITLE: Paediatrics 001

#+BEGIN_EXPORT html
<div class="engt">Paediatrics</div>
<div class="japt">小児科学</div>
<div class="engt">Page 001</div>
#+END_EXPORT

[[https://github.com/ahisu6/ahisu6.github.io/edit/main/src/p/001.org][Edit]]

[[file:./index.org][Home]]

[[file:./002.org][Next page >>]]

-----

#+TOC: headlines 2

* Dehydration
:PROPERTIES:
:CUSTOM_ID: org3fe0ed9
:END:

Posted: 2023-05-21 | Updated: 2023-05-21

I need a loooooooooooooooooooooooooooooot of water...

I am too thirsty...

Many things can make the baby dehydrated, such as vomiting and diarrhoea. @@html:<span class="ja">嘔吐や下痢など、さまざまなことが原因で赤ちゃんは脱水状態になります。</span>@@

In children, the best way to assess dehydration is to measure the weight of the baby. @@html:<span class="ja">小児の場合、脱水を評価する最も良い方法は、赤ちゃんの体重を測定することです。</span>@@

Babies lose weight when they are dehydrated. Just like raisins... @@html:<span class="ja">赤ちゃんは脱水すると痩せる。レーズンのように...。</span>@@

There are three groups:
1. If the baby loses less than 5% weight, then that is okay. @@html:<span class="ja">赤ちゃんの体重減少が5％以下であれば、問題ありません。</span>@@
2. If the baby loses between 5-10% weight, then that means the baby is dehydrated. @@html:<span class="ja">赤ちゃんの体重が5～10％減ったら、それは脱水症状ということです。</span>@@
3. Finally, if the baby loses /more/ than 10% weight, then that means the baby is in /shock/! @@html:<span class="ja">最後に、赤ちゃんの体重が10％以上減少したら、それは赤ちゃんがショックを受けていることを意味します！</span>@@

** Signs and symptoms
:PROPERTIES:
:CUSTOM_ID: org1d1cb0e
:END:

I have put a table in this [[https://drive.google.com/uc?export=view&id=1g5v1jEjhqGaZ-SXvEEq0PMQO-MqJCp3U][picture]].

Here is a nice [[https://drive.google.com/uc?export=view&id=15OpYap4OfXQyRAQRF4c5OGTXqOWNrtOh][picture]] of dehydrated baby.

They are basic and general things:
- The baby will be annoyed and crying
- Reduced skin turgor (the skin will look like a raisin...)
- The eyes will look sunken deep down @@html:<span class="ja">目が深く沈んでいるように見えるでしょう。</span>@@
- Dry mouth
- The heart rate will be high
- The baby will not pass urine

** Investigations
:PROPERTIES:
:CUSTOM_ID: orgbdfbd55
:END:

- Sometimes you might need to do investigation to find out the cause of dehydration. @@html:<span class="ja">時には、脱水症状の原因を探るために調査が必要な場合もあります。</span>@@
- Do culture of the baby poop to see if there are any strange bacteria. @@html:<span class="ja">赤ちゃんのウンチを培養して、変な菌がいないかどうか確認する。</span>@@
- Make sure you do U+E before you give IV fluids. @@html:<span class="ja">点滴をする前に必ずU+Eをしてください。</span>@@

** Treatment
:PROPERTIES:
:CUSTOM_ID: orgf2adeec
:END:

- This depends on the group of dehydration! @@html:<span class="ja">これは、脱水のグループによって異なります！</span>@@
- See this [[https://drive.google.com/uc?export=view&id=1BGyGWNEmLK1YqrzpCBdcPVOODL774Sby][picture]] to learn about the treatment of /basic/ dehydration.
- There is a special management of dehydration during shock @@html:<span class="ja">ショック時の脱水には、特別な管理が必要です</span>@@:
  - English version: See this [[https://drive.google.com/uc?export=view&id=1S1pUQtbXlXcwVE7rdZokl1DzwuSHjswb][picture]] to learn in English.
  - Japanese version: See this [[https://drive.google.com/uc?export=view&id=1Fp0l18pkQA6MHnnJejnGaa-WxZyAjFSF][picture]] to learn in Japanese.
  - In shock, there are 3 main steps to manage dehydration @@html:<span class="ja">ショックでは、脱水の治療には主に3つのステップがあります</span>@@:
    1. Resuscitation: Give 10 ml of fluid for every kilogram of weight. So, if the baby weighs 22 kg, then you should give 220 ml of fluid (10 × 22 = 220). After you give the baby the 10ml bolus, you will have 自由 to give more fluids! @@html:<span class="ja">体重1kgにつき10mlの輸液をします。つまり、赤ちゃんの体重が22kgなら、220mlの輸液をする必要があります。赤ちゃんに<mark>10</mark>mlボーラスを投与した後、さらに輸液をする<mark>自由</mark>があります！</span>@@
    2. Replacement: We need to use this formula to calculate something called "fluid deficit" (this means "how much fluid did the baby lose?"): Fluid deficit = % dehydration × weight (kg) × 10. @@html:<span class="ja">この式を使って「体液不足」というものを計算する必要があります（これは「赤ちゃんがどれだけ体液を失ったか」という意味です）: 体液不足＝脱水率×体重 (kg) × 10</span>@@
    3. Maintenance: There is a table which you need to know. I have put it below. @@html:<span class="ja">知っておいていただきたい表があります。以下に載せておきます。</span>@@
       | 100 ml for the first 10 kg          | @@html:<span class="ja">最初の10kgには100mlを投与する必要があります</span>@@     |
       | 50 ml for the second 10 kg          | @@html:<span class="ja">その後、2回目の10kgには50mlを与えるようにします</span>@@ |
       | 20 ml for the rest of the kilograms | @@html:<span class="ja">最後に、残りの1キログラムに対して20mlを与える</span>@@   |

* Bronchiolitis
:PROPERTIES:
:CUSTOM_ID: org402db5e
:END:

Posted: 2023-05-11 | Updated: 2023-05-11

I saw this in the winter. I saw it sooooo much!!! @@html:<span class="ja">私は冬にこれを見た。すごーく見ました！！！</span>@@

It is very common in children that are under the age of 12 months! @@html:<span class="ja">生後12ヶ月未満のお子様によく見られる症状です！</span>@@

It is a viral infection. It is caused by respiratory syncytial virus (RSV). You must know this. This is very important. @@html:<span class="ja">ウイルス感染症である。呼吸器合胞体ウイルス(RSV)が原因です。これを知っておく必要があります。これはとても重要なことです。</span>@@

Usually, the baby is fine. But, it can be severe if the baby was born prematurely or if the baby has other diseases. @@html:<span class="ja">通常、赤ちゃんは元気です。しかし、早産で生まれたり、赤ちゃんが他の病気を持っていたりすると、重症化することがあります。</span>@@

The virus affects the bronchioles of the baby. See this [[https://drive.google.com/uc?export=view&id=1lj6NciEPTCXnFTKVJbiHUZFZB8m9wllZ][picture]]. @@html:<span class="ja">このウイルスは、赤ちゃんの気管支に感染します。</span>@@

** Signs and symptoms
:PROPERTIES:
:CUSTOM_ID: org51c3523
:END:

- Flu symptoms!
  - Fever
  - Blocked nose. Sooooooooooooooo much mucus!
  - Breathless. Again, this is because there is sooooooooooooooooo much mucus. SOOOOOOOOOOOOOOOOOO MUCH!
  - Dry cough
- Wheezing!!
- When you listen with the stethoscope, you will hear crackles! @@html:<span class="ja">聴診器で聴くと、パチパチと音がします！</span>@@

Look at this [[https://drive.google.com/uc?export=view&id=1ale8Lv3LNwPDywdMBcPMtvf1JUn-YDWw][picture]]. These following symptoms are very, very, very important to remember. This is because if the baby has one of them, you must send the baby to the /hospital right now/ @@html:<span class="ja">これらの以下の症状は、とても、とても、とても大切なことなので、覚えておいてください。というのも、もし赤ちゃんがこのうちのひとつでも持っていたら、今すぐ病院へ行かせなければならないからです</span>@@:
- Apnoea: This is when the baby stops breathing for few seconds. @@html:<span class="ja">無呼吸です： 赤ちゃんが数秒間呼吸を止めることです。</span>@@
- Respiratory distress: So, things like stridor or chest recession! @@html:<span class="ja">呼吸困難です： つまり、喘鳴や胸部後退のようなものです！</span>@@
- Blue baby... @@html:<span class="ja">青色系の赤ちゃん...。</span>@@
- Oxygen saturation less than 92%. @@html:<span class="ja">酸素飽和度が92％未満。</span>@@

** Investigations
:PROPERTIES:
:CUSTOM_ID: org983ae2f
:END:

- Do oxygen saturations to see if the baby is okay! @@html:<span class="ja">酸素飽和度測定をして、赤ちゃんが大丈夫かどうか確認する！</span>@@
- To fully and accurately check if the baby has bronchiolitis, we can do tests of nasopharyngeal mucus to see if there is a virus. @@html:<span class="ja">赤ちゃんが気管支炎かどうかを完全かつ正確に確認するために、鼻咽頭粘液の検査をして、ウイルスがあるかどうかを確認します。</span>@@

** Treatment
:PROPERTIES:
:CUSTOM_ID: org3a764a9
:END:

- Give oxygen if the baby has less than 92% saturations. @@html:<span class="ja">赤ちゃんの酸素飽和度が92％以下なら酸素を投与する。</span>@@
- Because there is so much mucus in the nose, it is hard for the baby to eat food. So, sometimes they put NG tube. @@html:<span class="ja">鼻の中に粘液が多いので、赤ちゃんは食べ物を食べるのが大変です。そこで、NGチューブを入れることもあります。</span>@@

* Transient tachypnoea of the newborn
:PROPERTIES:
:CUSTOM_ID: org33cd0f9
:END:

Posted: 2023-05-08 | Updated: 2023-05-08

Newborn children can sometimes have a difficulty with breathing. @@html:<span class="ja">生まれたばかりの子どもは、時に呼吸が苦しくなることがあります。</span>@@

There are many causes for this. I will cover the most common ones. Let's start with transient tachypnoea of the newborn! @@html:<span class="ja">その原因は様々です。その中でも代表的なものを取り上げていきます。まずは、新生児の一過性頻呼吸から！</span>@@

This is the most common one! @@html:<span class="ja">これが最も一般的なものです！</span>@@

Basically, when the baby is in the uterus, it has fluid in its lungs. @@html:<span class="ja">基本的に、赤ちゃんが子宮の中にいるときは、肺に液体が溜まっている状態です。</span>@@

Before the baby is born, the fluid becomes reabsorbed. So, normally, when the baby is born there is no fluid in the lungs! @@html:<span class="ja">赤ちゃんが生まれる前に、液体は再吸収されるようになります。ですから、通常、赤ちゃんが生まれたときには、肺に液体はありません！</span>@@

But sometimes, the lungs fail at reabsorbing the fluid. So, because there is fluid in the lungs, the baby will struggle to breathe! @@html:<span class="ja">しかし、肺が液体を再吸収できないことがあるのです。そのため、肺に水分があるため、赤ちゃんは息苦しくなります！</span>@@

This is more common if the baby is born via a c-section. @@html:<span class="ja">帝王切開で生まれた場合は、この傾向が強いです。</span>@@

Do not panic! This is okay! The baby will breathe again soon! I promise! @@html:<span class="ja">慌てないでください！これは大丈夫です！赤ちゃんはすぐに呼吸を再開します！やくそく！</span>@@

** Signs and symptoms
:PROPERTIES:
:CUSTOM_ID: org3ce2314
:END:

- High respiratory rate! @@html:<span class="ja">呼吸数が多い！</span>@@
- X-ray signs:
  - Fluid in the lung fissures!! @@html:<span class="ja">肺の裂け目には液体が溜まっている！！</span>@@
  - The lungs will look very inflated! @@html:<span class="ja">肺がとても膨らんでいるように見えるでしょう！</span>@@

** Investigations
:PROPERTIES:
:CUSTOM_ID: orgc1acd89
:END:

- You should do chest x-ray to see if there is fluid in the lungs! @@html:<span class="ja">胸部X線検査をして、肺に水が溜まっているかどうかを確認する必要があります！</span>@@

** Treatment
:PROPERTIES:
:CUSTOM_ID: org186e67e
:END:

- Give oxygen to the baby. @@html:<span class="ja">赤ちゃんに酸素を供給する。</span>@@
- If the baby is struggling to drink milk, then put a nasogastric tube and cannula! @@html:<span class="ja">赤ちゃんがミルクを飲むのに苦労しているようなら、経鼻胃管とカニューレを入れる！</span>@@

* Jaundice
:PROPERTIES:
:CUSTOM_ID: org2e444db
:END:

Posted: 2023-05-02 | Updated: 2023-05-02

You can look in PassMedicine for more information.

The Illustrated Textbook of Paediatrics has a lot of good stuff. You can check Chapter 11, Jaundice.

I will try to explain these diseases as best I can. I apologize for the delay due to lack of time. However, if you need an explanation of a particular disease, please let me know and I will do it instantly! @@html:<span class="ja">これらの病気について、できる限り解説していこうと思います。時間がなく、遅れていることをお詫びします。しかし、特定の病気の説明が必要な場合は、私に言ってください、私は即座にそれを行います！</span>@@

I love this topic. It's so すごい！

I translated this [[https://drive.google.com/uc?export=view&id=1FlEFod0-rdVQU_QapEoGJsGteXPNi6Ed][picture]] for you. Please take a look.

Ok. So, babies get jaundice a /lot/. Sooooo much jaundice. This is because of many reasons @@html:<span class="ja">赤ちゃんは黄疸がよく出る。こんなに黄疸が出るんですね。これは様々な理由によるものです</span>@@:
- Blood cells of the baby have a shorter life. It is only 70 days (adults have 120 days)! @@html:<span class="ja">赤ちゃんの血球は寿命が短いのです。わずか70日です(大人は120日)！</span>@@
- Babies are not good at bilirubin metabolism... @@html:<span class="ja">赤ちゃんはビリルビンの代謝が苦手...。</span>@@

Why should you care? Well, many reasons @@html:<span class="ja">なぜ気にする必要があるのでしょうか？まあ、いろいろな理由があります</span>@@:
1. Jaundice at birth is a really bad sign!!! I will explain it below! @@html:<span class="ja">出生時の黄疸は本当に悪い兆候です!!! 以下、説明します！</span>@@
2. Because babies are not good at bilirubin metabolism, there are many complications! @@html:<span class="ja">赤ちゃんはビリルビン代謝が苦手なため、合併症が多いのです！</span>@@
  - One of these complications is kernicterus. This is when bilirubin enters the brain! @@html:<span class="ja">その合併症のひとつが「ケルニクテラス」です。これは、ビリルビンが脳に入り込むことです！</span>@@

It is extremely important that you see and learn this cycle. I have translated it for you in Japanese. Please see this [[https://drive.google.com/uc?export=view&id=1FlEFod0-rdVQU_QapEoGJsGteXPNi6Ed][picture]]. Please let me know if there is anything which is not clear. I have taken this diagram from a textbook called: Illustrated Textbook of Paediatrics (I have sent you a message about this!). @@html:<span class="ja">このサイクルを見て、学ぶことは非常に重要です。日本語に訳してみました。何か不明な点があれば教えてください。この図は、Illustrated Textbook of Paediatricsという教科書から引用しました（これについては、メッセージでお知らせしました！）。</span>@@

Jaundice appears when there is more than 80 μmol/l of bilirubin in the blood. @@html:<span class="ja">黄疸は、血液中のビリルビンが80μmol/l以上ある場合に現れます。</span>@@

There are 3 categories of jaundice in children @@html:<span class="ja">小児の黄疸は3つに分類されます</span>@@:
1. Jaundice in the first 24 hours of life. This is bad. This is /really/ bad! @@html:<span class="ja">生後24時間以内の黄疸。これはヤバいです。これは本当に悪いことです！</span>@@
2. Jaundice shorter than 2 weeks. @@html:<span class="ja">黄疸が2週間より短い。</span>@@
3. Jaundice longer than 2 weeks. @@html:<span class="ja">黄疸が2週間以上続いている。</span>@@

The following is list of few important causes. There is a longer list on PassMedicine. Look for a page called "Jaundice in the newborn period":

| Jaundice type                 | Cause                                      |
|-------------------------------+--------------------------------------------|
| First 24 hours of life        | Blood of baby is breaking. This is urgent! |
| Jaundice shorter than 2 weeks | Physiological jaundice (this is okay!)     |
| Jaundice longer than 2 weeks  | See the table below!                       |
 
@@html:<span class="ja">以下は、いくつかの重要な原因のリストです。PassMedicineには、もっと長いリストがあります。「Jaundice in the newborn period」というページを探してみてください</span>@@:

| 黄疸の種類          | 想定される原因                                     |
|---------------------+----------------------------------------------------|
| 生後24時間の間に    | 赤ちゃんの血液が壊れそうです。これは緊急事態です！ |
| 黄疸が2週間より短い | 生理的黄疸（これは大丈夫です！）                   |
| 黄疸が2週間以上続く | 下表をご参照ください！                             |

Causes of jaundice longer than 2 weeks depend on whether the bilirubin is conjugated or not conjugated (there are more causes, but these are the important ones. There is a longer list on PassMedicine. Look for a page called "Jaundice in the newborn period"):

| Conjugated       | Unconjugated        |
|------------------+---------------------|
| Bile duct issues | Physiological       |
| Liver issues     | High GI obstruction |

@@html:<span class="ja">2週間以上の黄疸の原因は、ビリルビンが抱合しているか抱合していないかによって異なります(もっと原因があるのですが、重要なのはこれです。詳しくは教科書で調べてみてください！)。PassMedicineには、もっと長いリストがあります。「Jaundice in the newborn period」というページを探してみてください</span>@@:

| 共役ビリルビン | 非共役ビリルビン   |
|----------------+--------------------|
| 胆管の問題     | 生理的黄疸         |
| 肝臓の問題     | 消化管上部の閉塞感 |

The /most/ important thing to remember is that if jaundice happens before 24 hours after birth, you need to act urgently!!! @@html:<span class="ja">最も重要なことは、黄疸が生後24時間以前に起こった場合、緊急に対応する必要があることです！！！</span>@@

Another interesting thing to remember is that jaundice that is shorter than 2 weeks can happen in babies that are being breastfed! @@html:<span class="ja">また、母乳で育てている赤ちゃんには、2週間より短い黄疸が起こることがあるのも興味深い点です！すごいね？</span>@@

** Signs and symptoms
:PROPERTIES:
:CUSTOM_ID: org40fc620
:END:

- Jaundice usually starts at the top of the head, and then it moves downwards! @@html:<span class="ja">黄疸は通常、頭のてっぺんから始まり、下へ下へと移動していきます！</span>@@
- It causes the white part of the eye to become yellow! @@html:<span class="ja">白目の部分が黄色くなる！</span>@@

** Investigations
:PROPERTIES:
:CUSTOM_ID: org0d6882f
:END:

- Jaundice can be checked using a machine that measures the amount of bilirubin on the skin! @@html:<span class="ja">黄疸は、皮膚に付着したビリルビンの量を測定する機械で調べることができます！すごいね？</span>@@
- You can also do a bilirubin blood test... @@html:<span class="ja">ビリルビンの血液検査もできます`...。</span>@@
- If there is jaundice longer than 2 weeks, you should do these tests. There is a longer list on PassMedicine. Look for a page called "Jaundice in the newborn period" @@html:<span class="ja">黄疸が2週間以上ある場合は、これらの検査を行う必要があります。PassMedicineには、もっと長いリストがあります。「Jaundice in the newborn period」というページを探してみてください</span>@@:
  - A test to tell you the amount of conjugated and unconjugated bilirubin. This is the most important one. You must remember this!!! @@html:<span class="ja">共役ビリルビンと非共役ビリルビンの量を知るための検査です。これが一番大事なんです。これは必ず覚えておいてください！！！</span>@@
  - Coombs' test (this tests for blood breakdow) @@html:<span class="ja">クームス試験(血液の分解を調べる試験です)</span>@@
  - Thyroid tests @@html:<span class="ja">甲状腺検査</span>@@

** Treatment
:PROPERTIES:
:CUSTOM_ID: org314f04b
:END:

There are 2 types of treatments @@html:<span class="ja">トリートメントの種類は2種類</span>@@:
1. Blood transfusion. Use this if @@html:<span class="ja">輸血をする。以下のいずれかに該当する場合に使用します</span>@@:
  - If the baby's blood is being broken down (jaundice in the first 24 hours of life)!!! @@html:<span class="ja">赤ちゃんの血液が分解されている場合(生後24時間以内の黄疸)！！！</span>@@
  - If the bilirubin is suuuuuuuuuuuper high! @@html:<span class="ja">ビリルビンが極端に高い場合</span>@@
2. Phototherapy
  - This turns unconjugated bilirubin into safe chemical that is removed in urine! @@html:<span class="ja">これにより、非共役ビリルビンは安全な化学物質に変わり、尿中に排出されます！</span>@@

** Complications
:PROPERTIES:
:CUSTOM_ID: org495a3d8
:END:

- Like we said earlier, bilirubin can enter the brain and cause kernicterus. See this [[https://drive.google.com/uc?export=view&id=1FlEFod0-rdVQU_QapEoGJsGteXPNi6Ed][picture]]. @@html:<span class="ja">先ほども言ったように、ビリルビンが脳に入り込んで、ケルニクテラスを引き起こすことがあります。</span>@@
- The signs of kernicterus are @@html:<span class="ja">ケルニクテラスの兆候は</span>@@:
  - Fatigue @@html:<span class="ja">疲労度</span>@@
  - Poor feeding @@html:<span class="ja">食事の摂取量を減らす</span>@@
  - Arched back @@html:<span class="ja">アーチ型の背中</span>@@
  - Seizures @@html:<span class="ja">発作</span>@@
  - Coma!!! @@html:<span class="ja">昏睡状態！！！</span>@@

* Viral rashes in kids
:PROPERTIES:
:CUSTOM_ID: org013ca3b
:END:

Posted: 2023-04-30 | Updated: 2023-04-30

Ok.

Are you ready for the most annoying topic? No? Well, too bad...

I will talk about viral rashes in children. @@html:<span class="ja">今回は、子どものウイルス性発疹についてお話しします。</span>@@

You only need to know a few!
- Hand-foot-mouth disease
- Varicella (chickenpox)
- Measles
- Rubella
- Roseola infantum
- Erythema infectiosum

Don't worry, they're all easy.

I will add pictures for you to make it easier! @@html:<span class="ja">どれも簡単なのでご安心ください！</span>@@

** Hand-foot-mouth disease
:PROPERTIES:
:CUSTOM_ID: orgf6158ba
:END:

- Caused by coxsackie A virus. Look at this [[https://drive.google.com/uc?export=view&id=1AzMp-qU3dV6IAdfmgY8zWBNUhIHXiPBk][picture]]!

- Symptoms are mild. @@html:<span class="ja">症状は軽度です。やった！</span>@@
- First, they get fever and mouth ulcers... @@html:<span class="ja">まず、子供が熱を出し、口内炎ができる。。。</span>@@
- Thennnnn, after a short period of time, spots on the hand will appear. Look at this [[https://drive.google.com/uc?export=view&id=1mhd4kh8l38hBJZFtiGGlHTYW18MXRB9K][picture]]. @@html:<span class="ja">その後、しばらくすると、手に点状の病変が現れます。</span>@@

- Supportive treatment!

** Varicella (chickenpox)
:PROPERTIES:
:CUSTOM_ID: org486ecb5
:END:

- Caused by varicella zoster virus (VZV).
- It is no longer infectious after /all/ of the rash has become crusty!!! @@html:<span class="ja">発疹がすべてカサカサになった後は、もう感染しません！！！</span>@@

- Fever!
- It is suuuuuuuuuuuuuper itchy. I remember when I had it as a kid. PAIN!!!! Sooooo itchy! @@html:<span class="ja">超かゆいです。子供のころにあったのを思い出しました。いたみ！というくらい痒い！</span>@@

- Supportive treatment!
- Keep the kid at home! Do not send the kid to school!!!! @@html:<span class="ja">子供を家に置いておけ！子供を学校に行かせないでください！！！！</span>@@
- Calamine lotion!
- If the patient is immunocompromised, then give them varicella zoster immunoglobulin!!!! And, when they develop chickenpox, give them IV aciclovir!!!!!!!! @@html:<span class="ja">免疫不全の場合は、水痘帯状疱疹免疫グロブリンを投与します！そして、水痘を発症したら、アシクロビルを点滴で投与する！</span>@@

- It can cause encephalitis and pneumonia!

** Measles
:PROPERTIES:
:CUSTOM_ID: org4b78e54
:END:

- Caused by... measles virus...

- This has 3 phases:
  1. Prodromal phase
  2. Rash phase
  3. Cough phase
- Prodromal phase signs:
  - /High/ fever!!!
  - @@html:<mark>Co</mark>ryza: blocked nose!@@
  - @@html:<mark>Co</mark>njuctivits: eyelid inflammation@@
  - @@html:<mark>Co</mark>ugh: cough is... cough!@@
  - @@html:<mark>Ko</mark>plik spots: these look like salt.........@@ Look at this [[https://drive.google.com/uc?export=view&id=1x5WvELdrk5ArDRiOQBzHxGydgpPy6h05][picture]].
  - @@html:Look! They all have the <span class="ja">こ</span> sound! <span class="ja">こここここここここここここ....</span> If you see a lot of <span class="ja">こ</span>, then it must be measles! Quick, run away!!!! <mark>こここここここ</mark>わいですよ！大怖い！！！！@@
- Rash phase signs:
  - Patient will get rash all over the body. @@html:<span class="ja">全身に発疹が出る。</span>@@
  - Buuuuuuuuut, there is /no/ rash on their hands and feet!! @@html:<span class="ja">しかし、患者さんの手や足には発疹はありません！！！</span>@@

- @@html:You can test for <mark>m</mark>easles by using Ig<mark>M</mark> antibodies. Notice the M!@@

- Supportive treatment!!!
- Measles is a notifiable disease. So, report it!!!!
- If you come in contact with measles, then you should take the MMR vaccine with 72 hours!!! @@html:<span class="ja">麻疹に接触した場合は、72時間以内にMMRワクチンを摂取する必要があります！！！</span>@@

- @@html:<mark>M</mark>easles can cause: otitis <mark>m</mark>edia and pneu<mark>m</mark>onia! Notice the M! Mmmmmmmmmm 笑@@

** Rubella
:PROPERTIES:
:CUSTOM_ID: orgc6e49cc
:END:

- Caused by... rubella virus...

- Flu-like symptoms.
- Maculopapular rash.
  - Buuuuuuuuut, there is /no/ rash on their hands and feet!! @@html:<span class="ja">しかし、患者さんの手や足には発疹はありません！！！</span>@@
- Lymph node swelling behind the head and behind the ear. @@html:<span class="ja">頭の後ろ、耳の後ろのリンパ節が腫れる。</span>@@

- You can use IgM to find out if the person has rubella. @@html:<span class="ja">IgMで風疹かどうかを調べることができます。</span>@@

- Supportive treatment!

- Rubella can lead to joint issues and low platelet levels! @@html:<span class="ja">風疹は、関節の問題や血小板の低下を招くことがあります！</span>@@
- Rubella can be passed from pregnant woman to fetus. If that happens, then the baby will get something called "congenital rubella syndrome" @@html:<span class="ja">風疹は、妊婦から胎児にうつる可能性があります。そうなれば、赤ちゃんは 「先天性風疹症候群」と呼ばれるものになります。</span>@@
  - The baby will have cataracts, deafness, and heart issues!! Remember those! Ear, eyes, and heart!!!! @@html:<span class="ja">赤ちゃんは白内障、難聴、心臓に問題がある！これらを思い出してください！耳、目、心臓。</span>@@
  - You can read [[https://ja.wikipedia.org/wiki/%E5%85%88%E5%A4%A9%E6%80%A7%E9%A2%A8%E7%96%B9%E7%97%87%E5%80%99%E7%BE%A4][this]] for more information.

** Erythema infectiosum
:PROPERTIES:
:CUSTOM_ID: orgcf59002
:END:

- Caused by parvovirus B19.
- @@html:<mark>P</mark>arvovirus B19 causes sl<mark>pp</mark>ed cheeks! Look at the letter P!@@
- This is the smallest human virus... smol... @@html:<span class="ja">これは、最小のヒトウイルス... スモールですね！</span>@@
- This type of virus affect the blood of the person. So, if the patient has blood problem (like anaemia, sickle-cell disease, etc.), then they will have worse symptoms!!!! @@html:<span class="ja">このタイプのウイルスは、人の血液に影響を及ぼします。そのため、患者さんが血液の問題(貧血や鎌状赤血球症など)を抱えている場合、症状が悪化します！</span>@@

- First, the child gets fever.
- After the fever the cheeks will have a red rash. Look at this [[https://drive.google.com/uc?export=view&id=1-5skl8X9mkWSd8CHRYhF7nZKddsNabU2][picture]]. @@html:<span class="ja">発熱後、頬に赤い発疹ができる... トマトですね</span>@@
- Sometimes, warm things will also make the cheeks red... so smol. @@html:<span class="ja">時には、暖かいものも頬を赤くする... 大スモールですね。</span>@@
- @@html:It looks like someone sla<mark>pp</mark>ed the baby... Remember, <mark>p</mark>arvovirus B19 causes sl<mark>pp</mark>ed cheeks! Look at the letter P! <span class="ja">誰かが赤ちゃんをひっぱたいたように見える...。</span>@@
- When the rash appears, the child will no longer be infectious!!! @@html:<span class="ja">発疹が出たら、その子はもう感染力はありません！！！伝染性紅斑の場合、発疹が出た後、他の人に感染することはありません。だから、発疹が出た時点で、その子はもう他人に感染させることができないのだと覚えておいてください。やった！！！</span>@@
- If the patient has sickle-cell disease (it is a disease which affects the blood), then they will have a crisis!!! @@html:<span class="ja">もし患者さんが鎌状赤血球症(血液に影響を与える病気です)であれば、危機を迎えます！！！</span>@@

- If a pregnant woman get this disease, then the baby will have a condition called "hydrops fetalis". @@html:<span class="ja">妊婦がこの病気にかかると、赤ちゃんは「胎児水腫 / hydrops fetalis」と呼ばれる状態になります。</span>@@
  - This is when there is swelling all over the body. @@html:<span class="ja">全身に腫れがある場合です。</span>@@
  - Look at this [[https://drive.google.com/uc?export=view&id=1RPdDrvGUTCZ_tHvVZ7rC9-mubP5bNrgJ][picture]].
  - This is another [[https://drive.google.com/uc?export=view&id=1yA0JKR31R-9TD2oDn3P0Lnw3dYDBVUS_][picture]].

** Roseola infantum
:PROPERTIES:
:CUSTOM_ID: org1d62bf4
:END:

- Caused by human herpes virus 6.

- First, the child gets fever for few days. Sometimes the baby might get febrile convulsions! So, pay attention! @@html:<span class="ja">まず、数日間熱が出ます。時には、熱性けいれんを起こすこともあります！だから、注意してください！</span>@@
- After the fever goes away, the child gets rose-coloured maculopapular rash! @@html:<span class="ja">熱が下がった後、バラ色の斑点状皮疹が現れます！</span>@@
- Here is a fun way to remember it: poor baby... first the baby got fever, and then later someone brought some roses for the baby... @@html:<span class="ja">かわいそうな赤ちゃん...まず赤ちゃんが熱を出し、その後誰かが赤ちゃんにバラの花を持ってきた...という楽しい覚え方です。</span>@@

- Supportive treatment: so, reduce the temperature!
