#+TITLE: Paediatrics 002

#+BEGIN_EXPORT html
<div class="engt">Paediatrics</div>
<div class="japt">小児科学</div>
<div class="engt">Page 002</div>
#+END_EXPORT

[[https://github.com/ahisu6/ahisu6.github.io/edit/main/src/p/002.org][Edit]]

[[file:./index.org][Home]]

[[file:./001.org][<< Previous page]] - [[file:./003.org][Next page >>]]

-----

#+TOC: headlines 2

* Diabetic ketoacidosis
:PROPERTIES:
:CUSTOM_ID: org70566ac
:END:

Posted: 2023-05-25 | Updated: 2023-05-25

Diabetic ketoacidosis (DKA) is a dangerous and potentially deadly complication of type 1 diabetes. @@html:<span class="ja">Diabetic ketoacidosis (DKA)は1型糖尿病の危険な合併症であり、死に至る可能性もあります。</span>@@

It happens when the body's cells are not able to use sugar for energy. This is because there is no insulin. @@html:<span class="ja">体の細胞が糖をエネルギーとして使えなくなることで起こります。インスリンがないためです。</span>@@

This situation makes the body break down fat. When fat is broken down, ketones are produced. When there are a lot of ketones in the blood, the body becomes acidic. @@html:<span class="ja">このような状態になると、体は脂肪を分解するようになります。脂肪が分解されると、ケトン体が生成されます。血液中にケトン体が多くなると、体が酸性になります。</span>@@

You need to act NOW! @@html:<span class="ja">今すぐ行動する必要があります！</span>@@

** Signs and symptoms
:PROPERTIES:
:CUSTOM_ID: orgec9e178
:END:

- Exam signs
  - It usually starts with increased thirst and drinking a lot of water. @@html:<span class="ja">通常、喉の渇きが増し、水をたくさん飲むことから始まります。</span>@@
  - Then it becomes worse. The child will start to smell of acetone. @@html:<span class="ja">すると、もっとひどくなります。子どもはアセトンの臭いがするようになります。</span>@@
  - The child will vomit. A looooooooooooooooooooooooooot of vomiting. When we vomit, we lose a lot of potassium (the symbol for potassium is K+). Remember this. @@html:<span class="ja">吐くと、カリウム（カリウムの記号はK+）が大量に失われます。これを覚えておいてください。吐<mark>く</mark> (はく) = <mark>K</mark>+... KKKKKKKKKKKKKKKKKKKKKKK = くくくくくくくくくくくくくくくくくくくくくくく...。</span>@@
  - Tummy pain. @@html:<span class="ja">お腹の痛み。</span>@@
  - There is fast breathing because of acidosis (this is called Kussmaul breathing). @@html:<span class="ja">アシドーシスのために速い呼吸がある（これをクスマウル呼吸という）。</span>@@
  - Shock because of dehydration!!!!! @@html:<span class="ja">脱水症状によるショック！！！！！</span>@@

- Lab signs:
  - The blood glucose will be more than 11 mmol/L! @@html:<span class="ja"><mark>11</mark>... いちいち... ひとひと... ひとびと... <mark>人々</mark>！DKAになると、血液中の糖分濃度が高いので、<mark>人々</mark>はパニックになります。あなたは砂糖が嫌いですね！</span>@@ 
  - The blood ketone level will be more than 3 mmol/L! @@html:<span class="ja">血中ケトン濃度が3mmol/L以上となる！</span>@@
  - Arterial blood gas (ABG) will show acidosis. @@html:<span class="ja">動脈血ガス（ABG）はアシドーシスを示すだろう。</span>@@

** Investigations
:PROPERTIES:
:CUSTOM_ID: orgfe95b33
:END:

- Check the blood glucose and blood ketones! @@html:<span class="ja">血糖値や血中ケトン体を確認する！</span>@@
- Do ABG to check acidosis. @@html:<span class="ja">ABGを行い、アシドーシスを確認する。</span>@@
- You can do U+E to check for dehydration and low potassium. @@html:<span class="ja">U+Eをして脱水や低カリウムのチェックをすることができます。</span>@@
- Do ECG. This is because when the patient has low potassium, the heart will be crazy!!! @@html:<span class="ja">心電図をする。というのも、患者が低カリウムになると、心臓がおかしくなってしまうからです！！！</span>@@

** Treatment
:PROPERTIES:
:CUSTOM_ID: org04ddcc6
:END:

- Here is a [[https://drive.google.com/uc?export=view&id=1EIwIbT7l9Bi-cOAWqCP-Igw3vnFRO7gx][picture]] which summarises everything you need to know. Focus on the green boxes.
- This is ABCDE approach.
- Do /not/ give inslin before fluids. @@html:<span class="ja">輸液の前にインスリンを与えないでください。</span>@@
- Do /not/ give inslin before fluids. @@html:<span class="ja">輸液の前にインスリンを与えないでください。</span>@@
- Do /not/ give inslin before fluids. @@html:<span class="ja">輸液の前にインスリンを与えないでください。</span>@@
- Do /not/ give inslin before fluids. @@html:<span class="ja">輸液の前にインスリンを与えないでください。</span>@@
- Do /not/ give inslin before fluids. @@html:<span class="ja">輸液の前にインスリンを与えないでください。</span>@@
- Do /not/ give inslin before fluids. @@html:<span class="ja">輸液の前にインスリンを与えないでください。</span>@@
- Do /not/ give inslin before fluids. @@html:<span class="ja">輸液の前にインスリンを与えないでください。</span>@@
- Do /not/ give inslin before fluids. @@html:<span class="ja">輸液の前にインスリンを与えないでください。</span>@@
- Do not worry about the glucose. Make sure you give water to the child before anything else! @@html:<span class="ja">ブドウ糖のことは気にしないでください。何よりも先に水を飲ませるようにしましょう！</span>@@
- Check if the patient is in shock! @@html:<span class="ja">患者がショック状態にあるかどうかを確認する！</span>@@
- Resuscitation: Give 10 ml of fluid for every kilogram of weight. So, if the baby weighs 22 kg, then you should give 220 ml of fluid (10 × 22 = 220). After you give the baby the 10 ml bolus, you will have 自由 to give more fluids! @@html:<span class="ja">体重1kgにつき10mlの輸液をします。つまり、赤ちゃんの体重が22kgなら、220mlの輸液をする必要があります。赤ちゃんに10mlボーラスを投与した後、さらに輸液をする自由があります！</span>@@
- After that, calculate how much dehydration does the child have. @@html:<span class="ja">その後、その子の脱水症状がどの程度なのかを調べます。</span>@@
  - If the pH of the child is less than 7.1, then that means they have 10% dehydration. @@html:<span class="ja">もし子供のpHが7.1以下であれば、10％の脱水が起きているということです。</span>@@
  - If the pH of the child is more than 7.2, then that means they have 5% dehydration. @@html:<span class="ja">もし子供のpHが7.2以上なら、5％の脱水症状を起こしていることになります。</span>@@
  - pH 7.1 = 10% dehydration
  - pH 7.2 = 5% dehydration
  - After you calculate the dehydration percentage, you can calculate fluid deficit (fluid deficit = % dehydration × weight × 10). See this [[file:./001.org::#orgf2adeec][link]]. @@html:<span class="ja">脱水率を計算した後、体液不足を計算することができます (体液不足＝脱水率×体重× 10)。このリンクを参照してください。</span>@@
- After that, give maintenance fluids. This is a 500 ml fluid bag which has 0.% saline with 20 mmol KCl. @@html:<span class="ja">その後、維持輸液を行う。これは500mlの輸液バッグで、20mmol KCl入りの0.5%生理食塩水が入っています。</span>@@
- Finally, after 1 hour of fluid infusions, give insulin to the patient! You should use 0.05 units for every kilogram, for every hour (0.05 units/kg/hour). @@html:<span class="ja">最後に、1時間の輸液の後、インスリンを投与します！1時間ごとに1kilogramあたり0.05単位使用する必要があります（0.05単位/kg/時間）。</span>@@

** Complications
:PROPERTIES:
:CUSTOM_ID: org7ec67f4
:END:

- Do you know why we should NOT give insulin before fluids? @@html:<span class="ja">輸液の前にインスリンを投与してはいけない理由をご存知でしょうか？</span>@@
- If you give insulin before fluids, then the patient's brain will become swollen (cerebral oedema)! @@html:<span class="ja">輸液の前にインスリンを投与すると、患者さんの脳が腫れてしまう（脳浮腫）！</span>@@
