#+TITLE: Home Page
#+OPTIONS: toc:nil

#+BEGIN_EXPORT html
<div style="font-family: monospace; background-color: #082694; font-weight: bolder; font-size: 60px; text-align: center;">
<span style="color: #8ffa89;">A</span><span style="color: #89b7fa;">hi</span>su6
</div>
<div style="color: #8ffa89; background-color: transparent; font-weight: bolder; font-size: 60px; text-align: center;">Learn Medicine... but in the Japanese language!</div>
<div style="color: #89b7fa; background-color: transparent; font-weight: bold; font-size: 60px; text-align: center;">医学を学ぶ... ただし、日本語で！</div>
#+END_EXPORT

[[https://github.com/ahisu6/ahisu6.github.io/edit/main/src/index.org][Edit]]

-----

* え？
:PROPERTIES:
:CUSTOM_ID: eh
:END:
This website is a gift for a friend! @@html:<span class="jp">このサイトは、友人へのプレゼントです！</span>@@

Please note that the translation may not be correct. However, I will try my absolute best to make sure that the translation is as accurate as possible. @@html:<span class="jp">翻訳が正確でない可能性があることをご了承ください。しかし、可能な限り正確な翻訳をするよう、絶対的な努力をします。</span>@@

The pink highlighting means that it is a link. For example, [[https://www.youtube.com/watch?v=eY2Aw-cWRAA][this is a link]]! @@html:<span class="jp">ピンクのハイライトは、リンクであることを意味します。例えば、[[https://www.youtube.com/watch?v=eY2Aw-cWRAA][これはリンクです]]です！</span>@@

* Chapters
:PROPERTIES:
:CUSTOM_ID: toc
:END:
- [[file:./og/index.org][Obstetrics and Gynaecology - 産科・婦人科領域 (OG)]]
- Paediatrics - 小児科 (P)
- Cardiology - 循環器内科学 (C)
- Respiratory - 呼吸器内科 (R)
- Surgery - 外科 (S)
- Neurology - 神経学 (N)
- Dermatology - 皮膚科学 (D)
- Endocrinology - 内分泌学 (E)
- Gastroenterology - 消化器病学 (G)

* Note
The content of this site is not intended as medical advice. If you have a medical problem, you should seek medical advice. @@html:<span class="jp">本サイトのコンテンツは、医学的なアドバイスを目的としたものではありません。医療上の問題がある場合は、医師の診断を受ける必要があります。</span>@@
