#+TITLE: Home Page
#+OPTIONS: toc:nil

#+BEGIN_EXPORT html
<div style="font-family: monospace; background-color: #FDFDFB; font-weight: bolder; font-size: 2em; text-align: center;">
<span style="color: #152515;">Ahi</span><span style="color: #FF9600;">su</span><span style="color: #6c9cf6;">6</span>
</div>
<div style="color: #8ffa89; background-color: transparent; font-weight: bolder; font-size: 2em; text-align: center;">Learn Medicine... but in the Japanese language!</div>
<div style="color: #89b7fa; background-color: transparent; font-weight: bold; font-size: 2em; text-align: center;">医学を学ぶ... ただし、日本語で！</div>
#+END_EXPORT

[[https://github.com/ahisu6/ahisu6.github.io/edit/main/src/index.org][Edit]]

-----

* え？
:PROPERTIES:
:CUSTOM_ID: eh
:END:
This website is a gift for my best friend! @@html:<span class="jp">このサイトは、友人へのプレゼントです！</span>@@

The pink highlighting means that it is a link. For example, [[https://www.youtube.com/embed/aRCVKqBPsFU][this is a link]]! @@html:<span class="jp">ピンクのハイライトは、リンクであることを意味します。例えば、<a href="https://www.youtube.com/embed/aRCVKqBPsFU">これはリンクです</a>！</span>@@

* Chapters
:PROPERTIES:
:CUSTOM_ID: toc
:END:

Click the chapter which you want to study! @@html:<span class="jp">勉強したい章をクリックしてください！</span>@@

- [[file:./og/index.org][Obstetrics and Gynaecology - 産婦人科学 (og)]]
- Paediatrics - 小児科学 (p)
- Cardiology - 循環器学 (c)
- Respiratory - 呼吸器学 (r)
- Surgery - 外科学 (s)
- Neurology - 神経学 (n)
- [[file:./d/index.org][Dermatology - 皮膚科学 (d)]]
- [[file:./e/index.org][Endocrinology - 内分泌学 (e)]]
- Gastroenterology - 消化器学 (g)

* Sorting tables
:PROPERTIES:
:CUSTOM_ID: orgdcbac4b
:END:

In each chapter, you will find a table of topics. @@html:<span class="jp">各章には、トピックの表が掲載されています。</span>@@

Click on the header of the column to sort it! Cool, right?! @@html:<span class="jp">列のヘッダーをクリックするとソートされます！すごいね！</span>@@

Click on the "DATE POSTED" header, then the table will be sorted by date... @@html:<span class="jp">「DATE POSTED」ヘッダをクリックすると、日付順にソートされます。</span>@@

Click on the "TITLE" header, then the table will be sorted by alphabetical order... @@html:<span class="jp">「TITLE」のヘッダーをクリックすると、テーブルがアルファベット順にソートされます。。。</span>@@

* Disclaimer
Disclaimer. @@html:<span class="jp">免責事項。</span>@@

Please note that the translation may not be correct. However, I will try my absolute best to make sure that the translation is as accurate as possible. @@html:<span class="jp">翻訳が正確でない可能性があることをご了承ください。しかし、可能な限り正確な翻訳をするよう、絶対的な努力をします。</span>@@

The content of this site is not intended as medical advice or as a diagnostic tool. If you have a medical problem, you should seek medical advice. @@html:<span class="jp">本サイトのコンテンツは、医学的なアドバイスや診断のためのものではありません。医療上の問題がある場合は、医師の診断を受ける必要があります。</span>@@
