#+TITLE: Ahisu6
#+OPTIONS: toc:nil

#+BEGIN_EXPORT html
<div style="font-family: monospace; background-color: #FDFDFB; font-weight: bolder; font-size: 2em; text-align: center;">
<span style="font-size: 2em; color: #412bff;">大</span><span style="color: #152515;">Ahi</span><span style="color: #FF9600;">su</span><span style="color: #6c9cf6;">6</span><span style="font-size: 2em; color: #412bff;">大</span></div>
#+END_EXPORT

[[https://github.com/ahisu6/ahisu6.github.io/edit/main/src/index.org][Edit]]

-----

* え？
:PROPERTIES:
:CUSTOM_ID: ehh
:END:

Welcome to あひす六...。

This website is a gift for my /best/ friend! @@html:<span class="ja">このウェブサイトは、私の大親友への贈り物です！</span>@@

Pink colour means that it is a link. For example, [[https://www.youtube.com/embed/aRCVKqBPsFU][this is a link]]! @@html:<span class="ja">ピンクのハイライトは、リンクであることを意味します。例えば、<a href="https://www.youtube.com/embed/aRCVKqBPsFU">これはリンクです</a>！</span>@@

* Chapters
:PROPERTIES:
:CUSTOM_ID: toc
:END:

Click the chapter which you want to study! @@html:<span class="ja">勉強したい章をクリックしてください！</span>@@
- [[file:./iroha.org][Iroha code - いろは符号]]
- [[file:./morse.org][Morse code - モールス符号]]
- [[file:./pgp.org][Pretty Good Privacy - プリティ・グッド・プライバシー]]
- [[file:./learn/index.org][Learn - 学ぶ]]
- [[file:./h/index.org][History - 病歴聴取 (h)]]
- [[file:./cp/index.org][Clinical Pharmacology - 臨床薬理学 (cp)]]
- [[file:./og/index.org][Obstetrics and Gynaecology - 産婦人科学 (og)]]
- [[file:./p/index.org][Paediatrics - 小児科学 (p)]]
- [[file:./c/index.org][Cardiology - 循環器学 (c)]]
- [[file:./r/index.org][Respiratory - 呼吸器学 (r)]]
- [[file:./s/index.org][Surgery - 外科学 (s)]]
- [[file:./n/index.org][Neurology - 神経学 (n)]]
- [[file:./d/index.org][Dermatology - 皮膚科学 (d)]]
- [[file:./e/index.org][Endocrinology - 内分泌学 (e)]]
- [[file:./g/index.org][Gastroenterology - 消化器学 (g)]]
- [[file:./rh/index.org][Rheumatology - リウマチ学 (rh)]]
- [[file:./o/index.org][Oncology - 腫瘍学 (o)]]


* 花
:PROPERTIES:
:CUSTOM_ID: flower
:END:

#+BEGIN_EXPORT html
<div style="text-align: center; font-size: 2em;">
<a style="text-decoration: none;" href="https://drive.google.com/uc?export=view&amp;id=18Wk2AzGZsZXmVQ8IWdbY7-vkiYR5ae5o">花。<br>この絵は、花であるあなたを描いています。</a>
</div>
<div class="japt">私の目には、あなたはいつもこの花を思い出させてくれるでしょう。素敵な友人でいてくれてありがとう。</div>
<!-- * Winner! -->
<!-- :PROPERTIES: -->
<!-- :CUSTOM_ID: winner -->
<!-- :END: -->

<!-- [[file:./congratulations.org][You have always been a winner!]] -->


<!-- * Sorting tables -->
<!-- :PROPERTIES: -->
<!-- :CUSTOM_ID: sorting -->
<!-- :END: -->

<!-- In each chapter, you will find a table of topics. @@html:<span class="ja">各章には、トピックの表が掲載されています。</span>@@ -->

<!-- Click on the header of the column to sort it! Cool, right?! @@html:<span class="ja">列のヘッダーをクリックするとソートされます！すごいね！</span>@@ -->

<!-- Click on the "DATE POSTED" header, then the table will be sorted by date... @@html:<span class="ja">「DATE POSTED」ヘッダをクリックすると、日付順にソートされます。</span>@@ -->

<!-- Click on the "TITLE" header, then the table will be sorted by alphabetical order... @@html:<span class="ja">「TITLE」のヘッダーをクリックすると、テーブルがアルファベット順にソートされます。。。</span>@@ -->
#+END_EXPORT

* Disclaimer
:PROPERTIES:
:CUSTOM_ID: org1b89221
:END:

Disclaimer! @@html:<span class="ja">免責事項！</span>@@

Please note that the translation may not be correct. However, I will try my absolute best to make sure that the translation is as accurate as possible. @@html:<span class="ja">翻訳が正確でない可能性があることをご了承ください。しかし、可能な限り正確な翻訳をするよう、絶対的な努力をします。</span>@@

The content of this site is not intended as medical advice or as a diagnostic tool. If you have a medical problem, you should seek medical advice. @@html:<span class="ja">本サイトのコンテンツは、医学的なアドバイスや診断のためのものではありません。医療上の問題がある場合は、医師の診断を受ける必要があります。</span>@@

Unless otherwise noted, original content on this site is licensed under [[https://raw.githubusercontent.com/ahisu6/ahisu6.github.io/main/LICENSE][GNU GENERAL PUBLIC LICENSE]]. @@html:<span class="ja">特に断りのない限り、このサイトのオリジナルコンテンツは<a href="https://raw.githubusercontent.com/ahisu6/ahisu6.github.io/main/LICENSE">GNU GENERAL PUBLIC LICENSE</a>の下でライセンスされています。</span>@@

