#+TITLE: Obstetrics and Gynaecology

#+BEGIN_EXPORT html
<div style="color: #8ffa89; background-color: transparent; font-weight: bolder; font-size: 60px; text-align: center;">Obstetrics and Gynaecology</div>
<div style="color: #89b7fa; background-color: transparent; font-weight: bold; font-size: 60px; text-align: center;">産科・婦人科領域</div>
#+END_EXPORT

[[https://github.com/ahisu6/ahisu6.github.io/edit/main/src/og/001.org][Edit]]

[[file:./index.org][Home]]

-----

#+TOC: headlines 2

* Introduction
:PROPERTIES:
:CUSTOM_ID: org3c1ff02
:END:

おはようともだち！

Anything that has ~(G)~ means that it is a Gynaecology topic. @@html:<span class="jp">(G)が付いているものは、ジャイネコロジーに関するトピックであることを意味します。</span>@@

And anything that has ~(O)~ means that it is an Obstetrics topic. @@html:<span class="jp">また、(O)が付いているものは産科の話題であることを意味します。</span>@@

Sounds good? Cool.

* Antenatal care (O)
:PROPERTIES:
:CUSTOM_ID: orgb494d28
:END:

Posted: 2023-01-30 | Updated: 2023-01-30

This is when the pregnant woman gets seen by a midwife or a consultant. @@html:<span class="jp">このとき、妊婦は助産師やコンサルタントの診察を受けることになる。</span>@@

Usually, if the pregnancy is uncomplicated, the pregnant woman is seen by midwife. @@html:<span class="jp">通常、合併症のない妊娠であれば、妊婦は助産婦に診てもらう。</span>@@

** Weeks and days
:PROPERTIES:
:CUSTOM_ID: orgfa0e52b
:END:

In Obstetrics, you will see things like 11 - 13+6 weeks. @@html:<span class="jp">産科では「11～13+6週」といった表記を見かけます。</span>@@

Let me explain to you what that means:
- Normally, we calculate pregnancies based on weeks. @@html:<span class="jp">通常、妊娠は週数で計算します。</span>@@
- A pregnancy is expected to last 40 weeks. @@html:<span class="jp">妊娠は40週間続くと言われています。</span>@@
- This weird number (13+6 weeks) is saying @@html:<span class="jp">この奇妙な数字（13+6週）が言っているのは</span>@@:
  - 13 weeks, and 6 days. @@html:<span class="jp">13週と6日。</span>@@
  - So, "11 - 13+6 weeks" means: between 11 weeks AND 13 weeks, 6 days. @@html:<span class="jp">つまり、「11-13+6」は、「11週と13週の間の6日間」という意味です。「11週-13週+6日」</span>@@
- Can you figure out what the following means? See the answers below! @@html:<span class="jp">以下の意味がわかりますか？答えは以下をご覧ください</span>@@
  1. 20 - 25+4 weeks
  2. 21+5 - 28+2 weeks
  3. 19+2 - 12+3 weeks

@@html:<div onclick="document.getElementById ('view').style.display=document.getElementById('view').style.display=='none' ? 'block':'none';"><p>Click this sentence to see the answers! <span class="jp">この文章をクリックすると、答えが表示されます！</span></p><div id="view" style="display: none;">@@
1. between 20 weeks AND 25 weeks, 4 days
2. between 21 weeks, 5 days AND 28 weeks, 2 days
3. between 19 weeks, 2 days AND 12 weeks, 3 days
@@html:</div></div>@@


** The booking visit
:PROPERTIES:
:CUSTOM_ID: org535415a
:END:
- This is done during 8 - 12 weeks of pregnancy @@html:<span class="jp">妊娠8～12週目に行われます。</span>@@
- The woman is given advice on diet, smoking, alcohol, vitamin D, folic acid, etc. @@html:<span class="jp">食事、喫煙、アルコール、ビタミンD、葉酸などに関するアドバイスを受けることができます。</span>@@
- The midwife takes a detailed medical history from the patient. @@html:<span class="jp">助産師は患者さんから詳しい病歴を聞き取ります。</span>@@
- The midwife looks for any potential health risks. @@html:<span class="jp">助産師は、健康被害の可能性がないかを調べます。</span>@@
- The midwife examines the patient: BMI, blood pressure, urine dipstick. @@html:<span class="jp">助産師が患者を診察する。BMI、血圧、尿検査。</span>@@
- The midwife then takes bloods from the patient:
  - FBC: to look for anaemia
  - Blood tests for 3 infections: syphilis, HIV, and hepatitis B!
  - Haemoglobin electrophoresis: this is when they look at the haemoglobin to look for things like Sickle cell disease. @@html:<span class="jp">これは、ヘモグロビンを調べて、鎌状赤血球症などを調べるものです。</span>@@
  - Urine culture: sometimes women can get bacteria in the urine which do NOT cause any symptoms... so, this urine culture looks for this bacteria! The bacteria is soooooo annoying, right? @@html:<span class="jp">女性の場合、尿に細菌が混じっていても、症状が出ないことがあります。ということで、この尿培養はこの菌を探すのだそうです！菌がうっとうしいんですよね。</span>@@

** Other days
:PROPERTIES:
:CUSTOM_ID: org74d047b
:END:

Here are some other important dates that you should know. @@html:<span class="jp">その他、知っておくべき重要な日程をご紹介します。</span>@@

You can find more details using resources like PassMedicine!

On PassMedicine, it is called "Antenatal care: timetable"!

- An ultrasound scan is done at 10 - 13+6 weeks of pregnancy... this looks for:
  - The expected delivery date. @@html:<span class="jp">納品予定日です。</span>@@
  - Look to see if there is more than 1 baby inside the mother. @@html:<span class="jp">お母さんの中に赤ちゃんが1人以上いるかどうか見てください。</span>@@
- Another ultrasound is done at 11 - 13+6 weeks... this one looks for: *Down's syndrome*! @@html:<span class="jp">11週から13週＋6日でもう一回超音波検査が行われます...この検査で調べるのは ダウン症！</span>@@
- At 18 - 20+6 weeks something called "Anomaly scan" is done. This is an ultrasound scan which looks for various heart and MSK diseases. @@html:<span class="jp">18週から20週＋6日の間に、「異常スキャン」と呼ばれるものが行われます。これは超音波検査で、心臓やMSKの様々な病気を調べるものです。</span>@@

* Heavy menstrual bleeding (G)
:PROPERTIES:
:CUSTOM_ID: orgfeaf8e2
:END:

Posted: 2023-01-30 | Last updated: 2023-01-30

As the name says... this is when the period is too heavy! @@html:<span class="jp">その名の通り...月経が重すぎる場合です！</span>@@

But, you might ask... how heavy is it?

Well, it is when the woman bleeds 80 mL or MORE!!!! So much blood :( @@html:<span class="jp">まあ、80mL以上の出血があった場合です。そんなに血が出るんだ :(</span>@@

** Causes
There are many causes for this. @@html:<span class="jp">その原因はさまざまです。</span>@@

The most common cause for heavy bleeding is... FIBROIDS!!!! @@html:<span class="jp">大量出血の一番の原因は... FIBROIDS！！！！</span>@@

Have a look at [[https://lh3.googleusercontent.com/pw/AMWts8CTxTmEQiuDh5edQYjcTso7MlxfWySmGRsrvTliRZoI0ntUfW8ioP8Lc4BANoCulalzP_KCLWwIv7-MBa6LCPSLwkhLuw6AlAnkSW7IErAW-ISTVfywyihN8qKQjabh0cGuzOnmLW9Wk_FwH3RoWhg=w766-h732-no][this picture]] to see the other causes (this is taken from Obstetrics and Gynaecology by Lawrence Impey).

** Investigations
:PROPERTIES:
:CUSTOM_ID: org5552907
:END:

- FBC: you need to do this because we have to look at the haemoglobin level to check if the patient has anaemia because of the heavy bleeding! @@html:<span class="jp">ヘモグロビン値を見て、大量出血のために貧血になっていないかどうかをチェックする必要があるからです！</span>@@
- Coagulation screen: if the woman is bleeding too much, then maybe she has an issue with the way her blood forms the clots! @@html:<span class="jp">出血が多いということは、血液の固まり方に問題があるのかもしれませんね！</span>@@
- Transvaginal ultrasound: you sometimes need to do this so that you look for things like fibroids or polyps. @@html:<span class="jp">子宮筋腫やポリープのようなものを探すために、時々これを行う必要があります。</span>@@
- Swabs: do this if there is a history which shows that maybe this is a sexually transmitted disease. @@html:<span class="jp">性感染症である可能性を示す既往歴がある場合は、これを行う。</span>@@

** Management
:PROPERTIES:
:CUSTOM_ID: orgbac268e
:END:

The management of heavy bleeding is interesting...

Okay. So, to fully understand the treatment options, you first need to understand the following:
1. Intra-uterine System:
  There is something called "intrauterine system". @@html:<span class="jp">「子宮内システム」というものがあります。</span>@@

  Basically, this is a coil that goes inside the uterus. See [[https://lh3.googleusercontent.com/pw/AMWts8B_pbHAIQev2ZxXf_FupbTT_MIUMGV2FTFAesrkvEQPvxc0Gw5KR832AeoUtjGQcV--YcTfVXdYX7wsl5VcA1qfChDn55bEVmLEnl7AeUYhHMbyhEIOnftV3crBvVqi4xiJJXnpI2K4aVwfNAzXg-Q=w712-h637-no?authuser=0][this picture]]. @@html:<span class="jp">基本的には、子宮の中にコイルを入れるものです。</span>@@

  It releases a hormone called "progestogen". This hormone reduces the bleeding by a lot! @@html:<span class="jp">黄体「ホルモン」というホルモンを分泌させます。このホルモンの働きで、出血がかなり抑えられます！</span>@@

  Finally, these intrauterine systems have a contraceptive effect. This means that when the woman uses them, she *CANNOT* become pregnant!!!! @@html:<span class="jp">最後に、これらの子宮内システムは、避妊効果があります。つまり、女性が使用すると、妊娠することはできません！！！！</span>@@

2. Tranexamic acid: this breaks down the blood clots. Women should take this when they are bleeding! The woman can still get pregnant! @@html:<span class="jp">これは、血栓を分解するものです。女性は出血しているときにこれを飲むとよいでしょう！女性はまだ妊娠できる！</span>@@

3. Hysteroscopic: in this, they remove things like polyps!


It all depends on whether the woman wants to have children or not! Remember this!! Very important!!! @@html:<span class="jp">すべては女性が子供を持ちたいかどうかにかかっている！これを覚えておいてください！！とても重要なことです！！！</span>@@

See [[https://lh3.googleusercontent.com/pw/AMWts8DTpmhgFm0VEO9Mu0UbYLQsLEtd5_BStzi7IeNbfW7H2D8-neCf7PqUTtDqqYb6VzF3GtlwJhqc44su7fza5L5wZnAaDiHASGhAEYnn96l_48pk5rLpm1fO0EvRnlq_XbGdy1p5UDtKI07yHO-4wnY=w885-h623-no?authuser=0][this picture]] to see the guideline.

* Abnormal uterine bleeding (G)
:PROPERTIES:
:CUSTOM_ID: org89fa98b
:END:

Posted: 2023-01-29 | Last updated: 2023-01-29

This is when the woman has problems with the menstrual cycle. @@html:<span class="jp">これは、女性の月経周期に問題がある場合です。</span>@@

So, it include things like:
- changes in frequency of the bleeding @@html:<span class="jp">出血の頻度の変化</span>@@
- duration of the bleed @@html:<span class="jp">出血の持続時間</span>@@
- amount of bleeding @@html:<span class="jp">出血量</span>@@

There is a mnemonic to help you remember the differetial diagnoses for abnormal uterine bleeding: PALM-COEIN! COEIN looks like coin... @@html:<span class="jp">笑。</span>@@

The PALM part is a mnemonic for the *structural causes* of abnormal uterine bleeding @@html:<span class="jp">PALMの部分は、子宮異常出血の構造的な原因を表すニーモニックです。</span>@@:
- Polyps
- Adenomyosis (this is when there is cells from the endometrium start growing in the myometrium [the smooth muscle layer of the uterus]) @@html:<span class="jp">(子宮内膜の細胞が子宮筋層（子宮の平滑筋層）で増殖し始めることです。）</span>@@
- Leiomyomas (this is another name for fibroids)
- Malignancy

The COEIN part is a mnemonic for the *NON-structural causes* of abnormal uterine bleeding @@html:<span class="jp">子宮異常出血の非構造的な原因を表すニーモニックのCOEINの部分です。</span>@@:
- Coagulopathy (bleeding issues)
- Ovulatory issues
- Endometrial (problems with the endometrium of the uterus)
- Iatrogenic (this is when the doctors cause the damage) @@html:<span class="jp">医原病</span>@@

Most common type of abnormal uterine bleeding is [[#orgfeaf8e2][Heavy Menstrual Bleeding]]! @@html:<span class="jp">子宮の異常出血で最も多いのは「重い月経血」！</span>@@ This is also called menorrhagia! @@html:<span class="jp">これは「menorrhagia」とも呼ばれます！</span>@@
