#+TITLE: Obstetrics and Gynaecology

#+BEGIN_EXPORT html
<div style="color: #8ffa89; background-color: transparent; font-weight: bolder; font-size: 2em; text-align: center;">Obstetrics and Gynaecology</div>
<div style="color: #89b7fa; background-color: transparent; font-weight: bold; font-size: 2em; text-align: center;">産婦人科学</div>
<div style="color: #8ffa89; background-color: transparent; font-weight: bolder; font-size: 1.5em; text-align: center;">Page 003</div>
#+END_EXPORT

[[https://github.com/ahisu6/ahisu6.github.io/edit/main/src/og/003.org][Edit]]

[[file:./index.org][Home]]

[[file:./002.org][Previous page]] - [[file:./004.org][Next page]]

-----

#+TOC: headlines 2

* Hyponatraemia in pregnancy (O)
:PROPERTIES:
:CUSTOM_ID: org9f8fd5a
:END:

Posted: 2023-02-21 | Updated: 2023-02-21

You asked me this question on 2023-02-21:
- Why is there hyponatraemia during labour?

Here is the answer...

When the woman is pregnant, the kidneys change in structure and function. @@html:<span class="jp">妊娠すると、腎臓の構造と機能が変化します。</span>@@

The kidneys increase in size. And, the kidney's ability of filter sodium and water also changes @@html:<span class="jp">腎臓は大きくなる。そして、腎臓のナトリウムや水をろ過する能力も変化します</span>@@:
1. Kidneys will filter more sodium @@html:<span class="jp">腎臓はより多くのナトリウムをろ過する</span>@@
2. Kidneys will absorb MORE wate @@html:<span class="jp"> 腎臓はより多くの水分を吸収する</span>@@
3. More creatinine will be removed from body @@html:<span class="jp">より多くのクレアチニンが体外に排出される</span>@@

Generally speaking, during pregnancy, the woman will have MORE water in her body! @@html:<span class="jp"> 一般的に妊娠中は、女性の体は水分を多く蓄えるようになると言われています！</span>@@

So, when you have too much water, then your blood will be less salty (which means, you will have LOW sodium level)! @@html:<span class="jp"> つまり、水分が多すぎると、血液の塩分濃度が低くなる（つまり、ナトリウム濃度が低くなる）のです！！</span>@@

In labour, the body releases oxytocin... correct? @@html:<span class="jp">陣痛になると、体内でオキシトシンが分泌される。。。ということですね？</span>@@

Oxytocin STOPS the woman from urinating. Oxytocin keeps water inside the woman! @@html:<span class="jp">オキシトシンは女性の排尿を止める。オキシトシンは女性の体内に水分を留めておくのです！</span>@@

So, this means that there will be more water in the woman, and therefore more hyponatraemia!!!! @@html:<span class="jp">ということは、女性の水分が多くなるので、低ナトリウム血症が多くなる！！！！</span>@@

Another thing is... during labour, some women vomit a lot. Sooooo, doctors will tell the woman to keep drinking water... @@html:<span class="jp"> もうひとつは、陣痛中にたくさん吐く女性がいることです。だから、医師は女性に水を飲み続けるように言うのですが。。。</span>@@

If the woman keeps drinking water, then... her blood will be less salty. @@html:<span class="jp">もし、女性が水を飲み続ければ。。。血液の塩分が少なくなる。</span>@@

* Ectopic pregnancy (G)
:PROPERTIES:
:CUSTOM_ID: org9e4c165
:END:

Posted: 2023-02-20 | Updated: 2023-02-20

This is when the embryo implants outside of the uterine cavity. @@html:<span class="jp">これは、胚が子宮腔の外に着床することである。</span>@@

Most common wrong site of implant is fallopian tube. See this [[https://lh3.googleusercontent.com/pw/AMWts8BnRnJxyu2729QDCZn4J0S36p4aHnzZtD7Qm37oIvhFDY3kWCIkd_sI3HpHi82uEoFYnV9nQOhcqokJ-bu6iwyNwNHD8AskClJbWMMS7kg1gTBAIsM9gG954U1hJ-lQgCVPXNNw4zu4moiX1TFlkTWD=w732-h529-s-no?authuser=3][picture]] for the other possible places! @@html:<span class="jp">最も一般的な着床部位の間違いは卵管です。</span>@@

Risk factors, go to "Ectopic pregnancy: epidemiology and risk factors" page on PassMedicine to learn more! @@html:<span class="jp">PassMedicineの「Ectopic pregnancy: epidemiology and risk factors」のページに移動して、もっと詳しく見る</span>@@:
- Damage to tubes (for example, damage done after pelvic inflammatory disease) @@html:<span class="jp">管の損傷（骨盤内炎症性疾患の後遺症など）</span>@@
- Endometriosis

When the embryo implants in the fallopian tubes, it causes a /lot/ of lower abdomen pain!!! @@html:<span class="jp">胚が卵管に着床する際、下腹部に大きな痛みがある！！！</span>@@

** Signs and symptoms
:PROPERTIES:
:CUSTOM_ID: org7764045
:END:

- Tummy pain!!!!!! Tummy hurts when you touch it!!
- No period (this is called amenorrhoea) for 6-8 weeks! @@html:<span class="jp">6～8週間、生理が来ない（これを無月経といいます）！</span>@@
- Vaginal bleeding: the colour of the blood will be /dark brown/. Maybe the embryo is drinking some dark chocolate................. Ehhhhhhhhhhhh @@html:<span class="jp">血液の色は暗褐色になります。もしかしたら胚はダークチョコレートを飲んでいるのかもしれない。。。。。。。。。。。。。。。。。え～～～～～～～～～～～</span>@@
- Collapse: the woman might pass out!!! This is a massive red flag because it shows that the tube ruptured!!!! @@html:<span class="jp">女性は気絶するかもしれない！！！ これは、チューブが破裂したことを示すので、大赤信号です！！！！</span>@@

** Investigations
:PROPERTIES:
:CUSTOM_ID: orgc33f60d
:END:

- Positive pregnancy test: let's start with the basic stuff!
- Transvaginal ultrasound
- Blood hCG: you need to monitor this. In normal pregnancy, hCG will keep going up. In ectopic pregnancy, hCG will stop going up. @@html:<span class="jp">これを監視する必要があります。正常な妊娠では、hCGは上昇し続けます。子宮外妊娠の場合、hCGは上がらなくなります。</span>@@

** Treatment
:PROPERTIES:
:CUSTOM_ID: orgb050af5
:END:

Right, so, there 3 different ways to treat ectopic pregnancy.
1. Expectant management: this means you just monitor the woman for 48 hours. @@html:<span class="jp">ということは、48時間監視すればいいということです。</span>@@
2. Medical management: in this one, you should give methotrexate to the woman. @@html:<span class="jp">この中で、メトトレキサートは投与したほうがいい。</span>@@
3. Surgical management: here you remove the fallopian tube (salpingECTOmy) OR you open the fallopian tube and remove the embryo (salpingOTOmy). @@html:<span class="jp">ここでは、卵管を摘出する方法（salpingECTOmy）と、卵管を開いて胚を取り出す方法（salpingOTOmy）のいずれかを選択します。</span>@@


There are criteria which will tell you what kind of treatment you should give... @@html:<span class="jp">どのような治療を施すべきか、基準があるのです。。。</span>@@

| Criteria                                                                                                   | Expectant       | Medical                                                                  | Surgical          |
|------------------------------------------------------------------------------------------------------------+-----------------+--------------------------------------------------------------------------+-------------------|
| Size of the pregnancy inside the fallopian tube                                                            | less than 35 mm | less than 35 mm                                                          | MORE than 35 mm   |
| Is it ruptured or not ruptured?                                                                            | NOT ruptured    | NOT ruptured                                                             | Ruptured          |
| Any pain?                                                                                                  | No              | No                                                                       | Yes               |
| Any fetal heartbeat?                                                                                       | No heartbeat    | No heartbeat                                                             | Visible heartbeat |
| hCG level                                                                                                  | less than 1000  | less than 1500                                                           | MORE than 5000    |
| Can you use this type of management of there is intrauterine pregnancy that is happening at the same time? | Yes             | No (because we use methotrexate, and methotrexate is bad for babies!!!!) | Yes               |



| @@html:<span class="jp">基準</span>@@                                                                 | Expectant      | Medical                                               | Surgical   |
|----------------------------------------------------------------------+----------------+-------------------------------------------------------+------------|
| @@html:<span class="jp">卵管内の妊娠の大きさ</span>@@                                                 | @@html:<span class="jp">35mm以下</span>@@       | @@html:<span class="jp">35mm以下</span>@@                                              | @@html:<span class="jp">35mm以上</span>@@   |
| @@html:<span class="jp">破裂しているのか、していないのか？</span>@@                                   | @@html:<span class="jp">破裂していない</span>@@ | @@html:<span class="jp">破裂していない</span>@@                                        | @@html:<span class="jp">破裂した</span>@@   |
| @@html:<span class="jp">痛みはありますか？</span>@@                                                   | @@html:<span class="jp">いいえ</span>@@         | @@html:<span class="jp">いいえ</span>@@                                                | @@html:<span class="jp">はい</span>@@       |
| @@html:<span class="jp">胎児の心拍はあるか？</span>@@                                                 | @@html:<span class="jp">心拍がない</span>@@     | @@html:<span class="jp">心拍がない</span>@@                                            | @@html:<span class="jp">心拍数発見</span>@@ |
| hCG level                                                            | @@html:<span class="jp">1000以下</span>@@       | @@html:<span class="jp">1500以下</span>@@                                              | @@html:<span class="jp">5000以上</span>@@   |
| @@html:<span class="jp">同時期に別の子宮内妊娠があった場合、このような管理は可能でしょうか？</span>@@ | @@html:<span class="jp">はい</span>@@           | @@html:<span class="jp">いいえ (メトトレキサートは胎児に悪いからです！！！！)</span>@@ | @@html:<span class="jp">はい</span>@@       |

