#+TITLE: Obstetrics and Gynaecology 004

#+BEGIN_EXPORT html
<div class="engt">Obstetrics and Gynaecology</div>
<div class="japt">産婦人科学</div>
<div class="engt">Page 004</div>
#+END_EXPORT

[[https://github.com/ahisu6/ahisu6.github.io/edit/main/src/og/004.org][Edit]]

[[file:./index.org][Home]]

[[file:./003.org][<< Previous page]] - [[file:./005.org][Next page >>]]

-----

#+TOC: headlines 2

* Endometriosis (G)
:PROPERTIES:
:CUSTOM_ID: orgd94e0f1
:END:

Posted: 2023-07-31 | Updated: 2023-07-31

So, like we said before, the uterus has 3 layers. One of these layers is called "endometrium". See this [[https://drive.google.com/uc?export=view&id=1aYNat8-vHpTCXPte8JrsCXIZkAd2jF0c][picture]]. @@html:<span class="ja">先にも述べたように、子宮には3つの層がある。そのうちのひとつが「子宮内膜」と呼ばれる層です。</span>@@

The endometrium reacts when the woman has the monthly period. Periods can cause a lot of pain, right? @@html:<span class="ja">子宮内膜は毎月の生理の時に反応する。生理痛はつらいものでしょう？</span>@@

In endometriosis, the endometrium starts to grow in other parts of the body. This can cause a lot of pain to the woman, especially during the menstrual cycle. @@html:<span class="ja">子宮内膜症では、子宮内膜が体の他の部分で増殖し始めます。これは、特に月経周期の間、女性に多くの痛みを引き起こす可能性があります。</span>@@

So, in endometriosis, you might find endometrial tissue in other places. For example (don't worry, you don't need to learn these. I am just giving you examples.) @@html:<span class="ja">ですから、子宮内膜症では、他の場所に子宮内膜組織が見つかるかもしれません。例えば（心配しないで、これらを学ぶ必要はない。私はただ例を挙げているだけです。）</span>@@:
- Colon
- Ovaries
- Ligaments
- Bladder
- Appendix
- and many, many, other places.

** Signs and symptoms
:PROPERTIES:
:CUSTOM_ID: org1de0b2c
:END:

- The woman will have pelvic pain for a long time. This is because the endometrial tissue is causing pain in the ligaments and in the colon. @@html:<span class="ja">女性は骨盤痛が長く続く。これは、子宮内膜組織が靭帯や結腸に痛みを引き起こしているためです。</span>@@
- The woman will not be able to have children. This is called "infertility". @@html:<span class="ja">女性は子供を持つことができなくなる。これを「不妊症」と呼ぶ。</span>@@
- Pain during periods. This pain usually starts before the woman has the bleeding. This is called "secondary dysmenorrhoea". @@html:<span class="ja">生理中の痛み。この痛みは通常、出血が起こる前に始まります。これは「続発性月経困難症」と呼ばれます。</span>@@
- Pain during sex. This is because endometrial tissue can go to the cervix. @@html:<span class="ja">セックス中の痛み。これは、子宮内膜組織が子宮頸部にまで達することがあるためである。</span>@@
- Urinary symptoms. This is because endometrial tissues can go to the bladder. @@html:<span class="ja">排尿症状。子宮内膜の組織が膀胱に行くことがあるからです。</span>@@

** Investigations
:PROPERTIES:
:CUSTOM_ID: orgf1b0e32
:END:

- The best way to investigate endometriosis is by doing laparoscopy. This is the gold standard. You will make a small hole in the tummy, and then you will use a small camera to see the endometrial tissue. Watch this [[https://drive.google.com/uc?export=view&id=1JOVOdQFGr7z3AaysSqyNyn-3WesV24Jz][video]] (I got it from [[https://vimeo.com/149998622][here]])! @@html:<span class="ja">子宮内膜症を調べる最善の方法は腹腔鏡検査です。これはゴールドスタンダードである。おなかに小さな穴を開け、小さなカメラで子宮内膜組織を観察します。</span>@@
- The ultrasound might be normal. So, there is no point in doing it. @@html:<span class="ja">超音波検査は正常かもしれない。だから、検査をしても意味がない。</span>@@

** Treatment
:PROPERTIES:
:CUSTOM_ID: orga9f142f
:END:

Please see this [[https://drive.google.com/uc?export=view&id=1N6xyCHsd2u0q2AeFj-0C_fA6uzzL05CG][picture]] of the treatment chart.

- First-line treatment is to give some painkillers to the patient. For example, paracetamol and NSAIDs. @@html:<span class="ja">第一選択治療は、患者に鎮痛剤を投与することである。例えば、パラセタモールやNSAIDsなどである。</span>@@
- If painkillers do not work, then you need to give [[file:../../h/002.org::#org7d34bc2][combined oral contraceptive pill]] or [[file:../../h/002.org::#org2f0fc2e][progestogen pill]]. @@html:<span class="ja">鎮痛剤が効かない場合は、経口避妊薬配合ピルか黄体ホルモンピルを投与する必要があります。</span>@@
- If hormonal treatment does not work, then you need to send the patient to the hospital. In the hospital, the patient will receive drugs called "GnRH analogues". @@html:<span class="ja">ホルモン治療が効かない場合は、患者を病院に送る必要がある。病院では「GnRHアナログ製剤」と呼ばれる薬を投与します。</span>@@
  - These will reduce the level of oestrogen. @@html:<span class="ja">これらはエストロゲンのレベルを下げる。</span>@@
- If the woman wants to have a baby, then she should do laparoscopic surgery to remove the endometrial tissue. Watch this [[https://drive.google.com/uc?export=view&id=1JOVOdQFGr7z3AaysSqyNyn-3WesV24Jz][video]] (I got it from [[https://vimeo.com/149998622][here]])! @@html:<span class="ja">出産を望むのであれば、腹腔鏡手術で子宮内膜組織を取り除く必要がある。</span>@@

* Shoulder dystocia (O)
:PROPERTIES:
:CUSTOM_ID: org89380a1
:END:

Posted: 2023-07-30 | Updated: 2023-07-30

This is when the baby's shoulder is stuck behind the pubic symphysis of the mother. @@html:<span class="ja">これは、赤ちゃんの肩が母親の恥骨結合の後ろにはまり込んでいる状態である。</span>@@

This happens after the baby's comes out of the vagina. See this [[https://drive.google.com/uc?export=view&id=1M0g3VwDmGzOioqrlwSEg66hP-W_EnOdq][picture]]. @@html:<span class="ja">これは赤ちゃんが膣から出てきた後に起こる。</span>@@

Shoulder dystocia happens if the baby is too big. So, a ぷにぷに baby might get shoulder dystocia during delivery. @@html:<span class="ja">肩甲難産は、赤ちゃんが大きすぎる場合に起こります。ですから、ぷにぷにの赤ちゃんは分娩中に肩甲難産になるかもしれません。</span>@@

This can cause the brachial plexus of the baby to become damaged. See this [[https://youtu.be/v9pXVQGb0XQ][video]] to show you how the damage happens. @@html:<span class="ja">そのため、赤ちゃんの腕神経叢が損傷する可能性がある。</span>@@

** Signs and symptoms
:PROPERTIES:
:CUSTOM_ID: org7997743
:END:

- You will see that the baby's head is visible, but the baby is struggling to get the shoulder out. @@html:<span class="ja">赤ちゃんの頭は見えているが、赤ちゃんは肩を出そうともがいているのがわかるだろう。</span>@@

** Investigations
:PROPERTIES:
:CUSTOM_ID: org85a64ce
:END:

- You can see this with your eyes. You don't need an investigation. @@html:<span class="ja">目で見ればわかる。調査は必要ない。</span>@@

** Treatment
:PROPERTIES:
:CUSTOM_ID: orgc93d0b6
:END:

- Call the consultant! Quick!!!
- Now, you need to do something called McRoberts' manoeuvre. @@html:<span class="ja">さて、マクローバートの作戦と呼ばれるものを実行する必要がある。</span>@@
- McRoberts' manoeuvre is when the mother puts her thighs on her abdomen. See this [[https://youtu.be/eq9n1WJPhF4][video]]. I don't know why they have chosen this kind of music. Anywayyyy... @@html:<span class="ja">マックロバーツの操作とは、母親が太ももを腹部に向けて動かすことである。添付のビデオをご覧ください。私には、なぜ彼らがこのような音楽を選んだのかわからない笑。とにかく～～～...。</span>@@
- McRoberts' manoeuvre will move the pubic symphysis. This will create more space for the baby. @@html:<span class="ja">マックロバーツの操作で恥骨結合を動かす。そうすることで、赤ちゃんのためのスペースが生まれます。</span>@@

** Complications
:PROPERTIES:
:CUSTOM_ID: org018bb27
:END:

- Postpartum haemorrhage in mother: this is bleeding after the delivery. @@html:<span class="ja">産後出血：出産後の出血。</span>@@
- Brachial plexus injury in baby: this is damage to the baby's brachial plexus. See this [[https://youtu.be/v9pXVQGb0XQ][video]] to show you how the damage happens. @@html:<span class="ja">赤ちゃんの腕神経叢損傷：赤ちゃんの腕神経叢の損傷。</span>@@

* Ovarian tumours (G)
:PROPERTIES:
:CUSTOM_ID: org3450aaa
:END:

Posted: 2023-03-04 | Updated: 2023-03-08

Read this section a few times to understand it properly. @@html:<span class="ja">この項を何度か読んで、正しく理解してください。</span>@@

The ovary is made up of 3 types of cells (see this [[https://drive.google.com/uc?export=view&id=1-O6ij6x1SspauSQI-ZCzRTgvFGluWzzA][picture]]) @@html:<span class="ja">卵巣は3種類の細胞で構成されている</span>@@:
1. Epithelial cells
2. Germ cells
3. Sex cord and stromal cells

There are many risk factors for ovarian tumours @@html:<span class="ja">卵巣腫瘍の危険因子はたくさんある</span>@@:
- Genetics: similar to the breast cancer genes (BRCA genes). @@html:<span class="ja">遺伝: 乳がん遺伝子（BRCA遺伝子）と類似している。</span>@@
- A lot of ovulation: for example in early menarche. @@html:<span class="ja">排卵が多い:初潮が早い場合など。</span>@@
- Nulliparity: so, if the woman never had children, she is at risk!! @@html:<span class="ja">ヌリパリティ: では、子供を産んだことのない女性は危険なのか！！</span>@@

First, let's start with the main types of ovarian tumours @@html:<span class="ja">まず、卵巣腫瘍の主な種類から説明します</span>@@:
1. Epithelial tumours: these are the most common in older women!!! @@html:<span class="ja">こうは、高齢女性に多い！！！</span>@@
2. Germ cell tumours: these are common in /younger/ women!!!!! @@html:<span class="ja">これは若い女性に多いですね！！！！！</span>@@
3. Sex cord-stromal tumours

Have a look at this [[https://drive.google.com/uc?export=view&id=1-O6ij6x1SspauSQI-ZCzRTgvFGluWzzA][picture]]. I drew this so that you can understand it better. If you still don't understand it, let me know!!! @@html:<span class="ja">もっと理解してもらえるように描きました。それでもわからなかったら、教えてください！！！</span>@@

** Types
:PROPERTIES:
:CUSTOM_ID: org236739e
:END:

Don't worry too much about these facts! @@html:<span class="ja">これらの事実をあまり気にしないでください！</span>@@

There is more information on the "Ovarian tumours" page on PassMedicine. @@html:<span class="ja">PassMedicineの「Ovarian tumours」ページに詳しい情報がありますよ。</span>@@

There is a lot of information here. I summarised it for you in this [[https://drive.google.com/uc?export=view&id=1E6WljYpA3urDsRdCE52w_88DX7AhUGjY][picture]]!

1. Epithelial tumours
  - These are separated into two types: serous (filled with water) and mucinous (filled with mucus... Ehhhhh!!). @@html:<span class="ja">これらは、「serous」（水で満たされている）と「mucinous」(粘液で満たされている・・・えーっ！！)。</span>@@
  - There is a benign type (cystadenoma) and a malignant type (cystadenocarcinoma). @@html:<span class="ja">良性タイプ(cystadenoma)と悪性タイプ(cystadenocarcinoma)がある。</span>@@
2. Germ cell tumours
  - This is common in younger women. @@html:<span class="ja">これは若い女性に多いですね。</span>@@
  - It has 4 types: teratoma, yolk sac, dysgerminoma, and placental.
  - Teratoma
    - This one is my favourite!! @@html:<span class="ja">この1枚がお気に入りです！！</span>@@
    - You might see it in theatre! @@html:<span class="ja">手術室でも見かけることがあるかもしれませんね！</span>@@
    - It is made from embryo cells! @@html:<span class="ja">胚細胞から作られている！</span>@@
    - This is why you might see nails, hair, bone, guts, skin and other body parts during the surgery... because it is made from embryo cells!!!! @@html:<span class="ja">手術中に爪や髪の毛、骨、内臓、皮膚など体の一部が見えることがあるのはこのためです。。。胚の細胞から作られているからです！！！！</span>@@
  - Yolk sac tumours
    - Under the microscope, you will see Schiller-Duval bodies (which are basically glomeruli). @@html:<span class="ja">顕微鏡で見ると、シラー・デュバル小体（これは基本的に糸球体である）が見えます。</span>@@
    - It secretes alpha fetoprotein. @@html:<span class="ja">αフェトプロテインを分泌する。</span>@@
    - It affects children!!! Yolk is a baby!!!! @@html:<span class="ja">子供に影響する！！！卵の黄身は赤ちゃん！！！！</span>@@
    - @@html:Yolk <mark>sac</mark>: <mark>S</mark>chiller-Duval bodies, <mark>A</mark>lpha fetoprotein, <mark>C</mark>hildren!!!@@
  - Dysgerminoma
    - This secretes hCG and lactate dehydrogenase (LDH).
3. Sex cord-stromal
  - It has 3 types: fibroma, Granulosa cell tumour, Sertoli-Leydig cell tumour.
    - Fibroma
      - Exams love asking question about this one! @@html:<span class="ja">試験官も大好きな質問です！</span>@@
      - It causes something called Meigs syndrome. This is a triad of fibroma, ascites, and pleural effusion!!!! You must know this!!!!! Very important!!!!!!!!!!!! @@html:<span class="ja">Meigs症候群と呼ばれるものを引き起こします。これは線維腫、腹水、胸水の三徴候です！！！！ これは知っておかなければなりません！！！！！ とても重要です！！！！！！！！！！！！</span>@@
    - Granulosa cell tumour
      - This produces oestrogen and causes early puberty in children!! @@html:<span class="ja">これがエストロゲンを産生し、子どもの思春期を早める原因になるのです！！</span>@@
    - Sertoli-Leydig cell tumour
      - This produces androgens and makes the woman have male features!! @@html:<span class="ja">これがアンドロゲンを生成し、女性に男性機能を持たせるのです！！</span>@@
      - It is associated with Peutz-Jegher syndrome (this is a condition which causes many polyps in the bowels, and it increases risk of bowel cancer). @@html:<span class="ja">ポイツ・イェーガー症候群(腸にポリープが多くできる病気で、腸がんのリスクが高くなります)と関連します。</span>@@

** Signs and symptoms
:PROPERTIES:
:CUSTOM_ID: orge0b80fb
:END:

These are very vague. See this [[https://drive.google.com/uc?export=view&id=1b5TUNQn8EIWPX-tBqNtsKeSBeNnOwTAx][picture]] to remember the signs and symptoms:
- Abdominal bloating and pain!!! @@html:<span class="ja">腹部の膨満感や痛み！！！</span>@@
- Feeling full (so, the woman doesn't finish eating her food)! @@html:<span class="ja">満腹感(だから、女性は食べ物を食べ終わらない)！</span>@@
- Peeing a lot!! @@html:<span class="ja">排尿回数が多い！！</span>@@

** Investigations
:PROPERTIES:
:CUSTOM_ID: orge4eb705
:END:

- CA125: this is the first test you should do in every patient with suspected ovarian cancer!!! @@html:<span class="ja">卵巣がんが疑われるすべての患者さんに最初に行うべき検査です！！！</span>@@
- Pelvic ultrasound

** Treatment
:PROPERTIES:
:CUSTOM_ID: org5495856
:END:

- Surgery
- Platinum-based chemotherapy

** Questions
:PROPERTIES:
:CUSTOM_ID: org32ce543
:END:

1. If the patient comes in with suspected ovarian tumour, what test should you do?
2. Which ovarian tumour type causes Meigs syndrome?
3. Which ovarian tumour type has hair, skin, and other body parts?
4. Which ovarian tumour type mostly affects children?
5. Which ovarian tumour type secretes lactate dehydrogenase?
6. Which ovarian tumour type has Schiller-Duval bodies under a microscope?

@@html:<div onclick="reveal()">Click this sentence to see the answers! <span class="ja">この文章をクリックすると、答えが表示されます！</span></div><div style="display: none;">@@
1. CA125
2. Fibroma tumour
3. Teratoma
4. Yolk sac tumour
5. Dysgerminoma
6. Yolk sac tumour
@@html:</div>@@

#+BEGIN_EXPORT html
<script src="https://ahisu6.github.io/assets/js/revealAnswer.js"></script>
#+END_EXPORT
