#+TITLE: Obstetrics and Gynaecology

#+BEGIN_EXPORT html
<div style="color: #8ffa89; background-color: transparent; font-weight: bolder; font-size: 60px; text-align: center;">Obstetrics and Gynaecology</div>
<div style="color: #89b7fa; background-color: transparent; font-weight: bold; font-size: 60px; text-align: center;">産科・婦人科領域</div>
#+END_EXPORT

[[https://github.com/ahisu6/ahisu6.github.io/edit/main/src/og.org][Edit]]

[[file:./index.org][Home]]

-----

#+TOC: headlines 2

* Introduction
:PROPERTIES:
:CUSTOM_ID: org3c1ff02
:END:

おはようともだち！

Anything that has ~(G)~ means that it is a Gynaecology topic. @@html:<span class="jp">(G)が付いているものは、ジャイネコロジーに関するトピックであることを意味します。</span>@@

And anything that has ~(O)~ means that it is an Obstetrics topic. @@html:<span class="jp">また、(O)が付いているものは産科の話題であることを意味します。</span>@@

Sounds good? Cool.

* Heavy menstrual bleeding (G)
:PROPERTIES:
:CUSTOM_ID: orgfeaf8e2
:END:


* Abnormal uterine bleeding (G)
:PROPERTIES:
:CUSTOM_ID: org89fa98b
:END:

Posted: 29/01/2023 | Last updated: 29/01/2023

This is when the woman has problems with the menstrual cycle. @@html:<span class="jp">これは、女性の月経周期に問題がある場合です。</span>@@

So, it include things like:
- changes in frequency of the bleeding @@html:<span class="jp">出血の頻度の変化</span>@@
- duration of the bleed @@html:<span class="jp">出血の持続時間</span>@@
- amount of bleeding @@html:<span class="jp">出血量</span>@@

There is a mnemonic to help you remember the differetial diagnoses for abnormal uterine bleeding: PALM-COEIN! COEIN looks like coin... @@html:<span class="jp">笑</span>@@:

The PALM part is a mnemonic for the *structural causes* of abnormal uterine bleeding @@html:<span class="jp">PALMの部分は、子宮異常出血の*構造的な原因*を表すニーモニックです。</span>@@:
- Polyps
- Adenomyosis (this is when there is cells from the endometrium start growing in the myometrium [the smooth muscle layer of the uterus]) @@html:<span class="jp">(子宮内膜の細胞が子宮筋層（子宮の平滑筋層）で増殖し始めることです。）</span>@@
- Leiomyomas (this is another name for fibroids)
- Malignancy

The COEIN part is a mnemonic for the *NON-structural causes* of abnormal uterine bleeding @@html:<span class="jp">COEINパートは、子宮内出血の非構造的な原因を表すニーモニックです。</span>@@:
- Coagulopathy (bleeding issues)
- Ovulatory issues
- Endometrial (problems with the endometrium of the uterus)
- Iatrogenic (this is when the doctors cause the damage) @@html:<span class="jp">医原病</span>@@

Most common type of abnormal uterine bleeding is Heavy Menstrual Bleeding! @@html:<span class="jp">子宮の異常出血で最も多いのは「重い月経血」!</span>@@ This is also called menorrhagia! @@html:<span class="jp">これは「menorrhagia」とも呼ばれます。</span>@@
