#+TITLE: Neurology 001

#+BEGIN_EXPORT html
<div class="engt">Neurology</div>
<div class="japt">神経学</div>
<div class="engt">Page 001</div>
#+END_EXPORT

[[https://github.com/ahisu6/ahisu6.github.io/edit/main/src/n/001.org][Edit]]

[[file:./index.org][Home]]

-----

#+TOC: headlines 2

* Epilepsy
:PROPERTIES:
:CUSTOM_ID: org70426c1
:END:

Posted: 2023-04-20 | Updated: 2023-04-20

First, let's define the word "seizure". Seizure is high-frequency activation of neurons. @@html:<span class="ja">まず、「発作」という言葉の定義を説明します。発作とは、神経細胞が高周波で活性化することです。</span>@@

There are two types of seizures:
1. Focal: this affects a single part of the brain. It /focuses/ on a single part!!! @@html:<span class="ja">これは脳の一部分に作用します。一つの部分に集中するのです！！！</span>@@
2. Generalised: this affects /all/ of the braiiiiiiiiiiiiiiiiin! Have a look at this [[https://lh3.googleusercontent.com/pw/AJFCJaWRZW2vCdLmJtJwG79hOuxD_ykqcgcEwuvtRFSaKY8dBUgWh08rtlMrvvOdo06bIa59bjmIrQmk06BLGcB_NytyirApmzrvOMiTPu2JZAfLIS2X_w8MuJOd6vYq4ccon7ZmVfAWu7RQenyPCHNIOKza=w1278-h954-s-no?authuser=1][picture]] to see the types of seizures and their classifications! @@html:<span class="ja">これは脳の全てに影響します！</span>@@

Epilepsy is having many /unprovoked/ seizures. @@html:<span class="ja">てんかんは、誘発されない発作が何度も起こることです。</span>@@

** Signs and symptoms
:PROPERTIES:
:CUSTOM_ID: orgab07f76
:END:

See this [[https://lh3.googleusercontent.com/pw/AJFCJaWRZW2vCdLmJtJwG79hOuxD_ykqcgcEwuvtRFSaKY8dBUgWh08rtlMrvvOdo06bIa59bjmIrQmk06BLGcB_NytyirApmzrvOMiTPu2JZAfLIS2X_w8MuJOd6vYq4ccon7ZmVfAWu7RQenyPCHNIOKza=w1278-h954-s-no?authuser=1][picture]].

If you want to have a look at a /tonic/ seizure, see this [[https://lh3.googleusercontent.com/pw/AJFCJaVsQlPEOo8frCDPCuRsFsOZDvpKWWSWFekNwz2aJYc_JHWsEthBngZnKotUQrSsIHe_dsVSwR7HDdewQKH1aFGFFeU8iznuLVh5tp53RAsykf7cp9GVmNcR9LjdtNTeVY8eHHMNKc2sNWnh24pK_vdx=w500-h500-s-no?authuser=1][picture]].

If you want to have a look at a /clonic/ seizure, see this [[https://lh3.googleusercontent.com/pw/AJFCJaXIFWdpWuJcx6zFzvHewfgpuFWHRiNpWGqXdr4DDabXoXvqDwpSGpm4Yr8rR2rDdyNWRomZV4m8SsN_GK0_JAIELsJGsgoZ48vfOhWq3eoV94Vg8iEEE9e6zyNZD8KJJh-W6wBhA932Rphizrc3BPD2=w500-h500-s-no?authuser=1][picture]].

- There is a cool video of a guy putting salt frog legs. Here is the video [[https://www.youtube.com/watch?v=2YZJt_Bw3eo][link]]. Do you see how the legs keep shaking? It looks like they are having a /myoclonic seizure/. @@html:<span class="ja">カエルの足を塩漬けにするかっこいい動画があります。脚がずっと震えているのがわかりますか？まるで「ミオクロニー発作」を起こしているように見えます。</span>@@
  - This guy put /sodium/ on the legs first, and then he /leaves/ them. Keep repeating this sentence: "This guy put /sodium/ on the legs first, and then he /leaves/ them"!!

** Investigations
:PROPERTIES:
:CUSTOM_ID: org4f97aec
:END:

- Do EEG and MRI for anyone who presents with a seizure.

** Treatment
:PROPERTIES:
:CUSTOM_ID: org5c8ada3
:END:

- Absence seizure:
  1. Ethosuximide. @@html:<span class="ja"><mark>エト</mark>スクシミド。 わ！！！！見てください！これは「エト」です？私はこの薬を「え～と」ヒーラーと呼びたいのです。え～～と～～～～～～～～～...。誰かが「え～と」と言うたびに その人が欠神発作を起こしているのではないかと考えるようになる。そこにいるように見えて、実はいないのです。</span>@@
  2. Sodium valproate. @@html:<span class="ja">あなたは「え～と 」が好きでよく言っています。まず、エトスキシミドを投与してみます。しかし、それが失敗したら...だから、今度あなたがそれを言ったら、私はあなたに塩をあげます(言い換えれば、私はあなたにナトリウム(sodium)をあげます)。そうすれば、あなたは「え～と」を言わなくなります。ごめん笑。問題は解決しました... ククククク。</span>@@

- Generalised tonic-clonic seizure. See this [[https://lh3.googleusercontent.com/pw/AJFCJaUtyexG3EH2ee5f0pecyCR4yp65qGZuM74gDbhc4sCRycGPuVjEiyAHt_bg_AHWunqJKizMjZy8KmTd_eYTPqI-68x7zitrqGHncMoGQCXhRjuccKgf0QAV2InNWN83wHNRLmwifKKeqNoIVUL9CHA8=w500-h500-s-no?authuser=1][picture]]:
  1. Sodium valproate. @@html:Sodium is salty... so, imagine that one day there was someone having tonic-clonic seizure on the ground. Then, some genie (<mark>genie</mark> sounds like <mark>gene</mark>ralised seizure) came and put salt on that person... <span class="ja">ナトリウムは塩辛い...だから、ある日、地面で強直間代発作を起こしている人がいたとする。すると、ある<mark>魔神</mark>(これを「ま<mark>じん</mark>」、「<mark>gene</mark>ralised」という言葉とよく似ていますね。)がやってきて、その人に塩を塗った...。</span>@@
  2. Lamotrigine. @@html:<span class="ja"><mark>ラモ</mark>トリギン。ラモ... リム... お！<mark>リム</mark>ジンですね！！！そこで今度は、悪人が塩を撒いた後、<mark>リム</mark>ジンを使って現場から逃走したとする。</span>@@

- Myoclonic seizure:
  1. Sodium valproate. There is a cool video of a guy putting salt frog legs. Here is the [[https://www.youtube.com/watch?v=2YZJt_Bw3eo][link]]. Do you see how the legs keep shaking? It looks like they are having a /myoclonic seizure/. This guy put /sodium/ on the legs first, and then he /leaves/ them.
  2. @@html:<mark>Leve</mark>tiracetam. This sounds like <mark>leave</mark>@@. So, after the guy puts salt on the frog legs, he /leaves/ them to keep shaking and dancing...

- Focal seizures. See this [[https://lh3.googleusercontent.com/pw/AJFCJaUOu2V078ghiJDB4CpWoSi4vlQDx3k70ePmenNbCacv9idVP3w8oNxYEaM3I2WkIOQRiPmsyMY0BtfwKI1PlkDcE0q1jXT3jW4JRuOE7FFIuu4x-6a224NVqW22saoFl9qZFOB9ur6okR6iD2pYtf2m=w500-h500-s-no?authuser=1][picture]]:
  1. Lamotrigine. @@html:One day, there was a guy focusing (<mark>focus</mark> sounds like "<mark>focal</mark> seizure") soooooooooo much on driving a limousine. <span class="ja">ある日、<mark>リム</mark>ジンの運転に集中（「<mark>集中</mark>」は「<mark>焦点</mark>発作」のような響き）している男がいた。</span>@@
  2. Carbamazepine. @@html:<span class="ja">カルバマゼピン。カル... カー！</span> <mark>Car</mark>bamazepine sounds like a <mark>car</mark>! So, the guy who was driving the limousine accidentally hit another car on the road! <span class="ja">リムジンを運転していた人が、誤って道路で他の<mark>カー</mark>にぶつかってしまったんですね！やれやれ...。</span>@@

** Questions
:PROPERTIES:
:CUSTOM_ID: org068fd27
:END:

Sorry, I will add this soon...
