#+TITLE: Neurology 001

#+BEGIN_EXPORT html
<div class="engt">Neurology</div>
<div class="japt">神経学</div>
<div class="engt">Page 001</div>
#+END_EXPORT

[[https://github.com/ahisu6/ahisu6.github.io/edit/main/src/n/001.org][Edit]]

[[file:./index.org][Home]]

-----

#+TOC: headlines 2

* Parkinson disease
:PROPERTIES:
:CUSTOM_ID: org87512dc
:END:

Posted: 2023-06-22 | Updated: 2023-06-22

This is a disease which causes a problem in a part of the brain called substantia nigra. This causes less dopamine to be released. @@html:<span class="ja">これは、脳の黒質と呼ばれる部分に問題が生じる病気である。そのため、ドーパミンの放出が少なくなる。</span>@@

Sometimes, during treatment, the patient might still get some symptoms. This is called "on-off" effect. @@html:<span class="ja">治療中、患者に何らかの症状が残ることがある。これは「on-off」効果と呼ばれる。</span>@@

** Signs and symptoms
:PROPERTIES:
:CUSTOM_ID: orgb838b6a
:END:

@@html:The symptoms are easy to remember. Parkinson <mark>TRAPS</mark> the body@@:
1. @@html:<mark>T</mark>remor: this tremor happens when the patient is resting.  <span class="ja">この振戦は患者が安静にしているときに起こる。</span>@@
2. @@html:<mark>R</mark>@@igidity.
3. @@html:<mark>A</mark>kinesia: this means that the body is slow at moving. <span class="ja">つまり、体の動きが鈍いということだ</span>@@
4. @@html:<mark>P</mark>ostural instability: this means that the patient might be wobbly. <span class="ja">これは、患者がふらつく可能性があることを意味する。</span>@@
5. @@html:<mark>S</mark>@@huffling gait: watch this [[https://www.youtube.com/watch?v=yhj1PktNA1c][video]]!

** Investigations
:PROPERTIES:
:CUSTOM_ID: orga95ae0a
:END:

- This is a clinical diagnosis. So, you have to look at the symptoms of the patient. @@html:<span class="ja">これは臨床診断です。ですから、患者の症状を見なければなりません。</span>@@
- You can also do CT scan if you are not sure. @@html:<span class="ja">確信が持てない場合は、CTスキャンをすることもできます。</span>@@

** Treatment
:PROPERTIES:
:CUSTOM_ID: orgd06d41c
:END:

Because the patient does not have a lot of dopamine, we need to give them drugs that increase the dopamine level. There are many drugs that can do this. @@html:<span class="ja">患者にはドーパミンがあまりないので、ドーパミンを増やす薬を投与する必要がある。これを可能にする薬はたくさんある。</span>@@

Here are the main types (there are more on PassMedicine):
| Drug group                                                                           | Examples                                                   | How does it improve Parkinson                                                             | Side effects                                                                                                                                                                                                                                   |
|--------------------------------------------------------------------------------------+------------------------------------------------------------+-------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| DOPA drugs                                                                           | @@html:Levo<mark>dopa</mark>/carbi<mark>dopa</mark>@@      | These cause more dopamine to be in the body.                                              | "On-off" effect. If the patient gets these effects, then you should give them drugs that prevent the breakdown of dopamine. They can also cause involuntary movements!                                                                         |
| @@html:<mark>C</mark>OMT inhibitors@@                                                | @@html:Enta<mark>capone</mark>, tol<mark>capone</mark>@@   | These prevent dopamine breakdown. Give these to the patient if they have "on-off" effect. | Nothing important!                                                                                                                                                                                                                             |
| MAO-B                                                                                | @@html:Sele<mark>giline</mark>, rasa<mark>giline</mark>@@  | These prevent dopamine breakdown.                                                         | Nothing important!                                                                                                                                                                                                                             |
| @@html:<mark>Do</mark>pamine agonists (not used anymore because of bad side effects)@@ | @@html:Pramipex<mark>ole</mark>, ropinir<mark>ole</mark>@@ | This affect the dopamine receptors in the brain.                                          | @@html:Because they affect the receptors at the brain, they will cause impulsive behaviour and addiction to things like gambling and spending a lot of money. Remember, <mark>do</mark>pamine makes you spend a lot of <mark>do</mark>llars!@@ |

Here is a Japanese table:
| 薬剤群                                                                                | 例えば                                                     | パーキンソン病はどのように改善されるのですか？                                       | 薬の副作用                                                                                                                                                                                |
|----------------------------------------------------------------------------------------+------------------------------------------------------------+--------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| DOPA drugs                                                                             | @@html:Levo<mark>dopa</mark>/carbi<mark>dopa</mark>@@      | これらは、体内のドーパミンを増加させる。                                             | 「On-off」効果。もし患者にこのような作用が現れたら、ドーパミンの分解を防ぐ薬を与えるべきです。また、不随意運動を引き起こすこともある！                                                    |
| @@html:<mark>C</mark>OMT inhibitors@@                                                                        | @@html:Enta<mark>capone</mark>, tol<mark>capone</mark>@@   | これらはドーパミンの分解を防ぐ。「on-off」の効果がある場合は、患者にこれらを与える。 | 重要なことは何もない！                                                                                                                                                                    |
| MAO-B                                                                                  | @@html:Sele<mark>giline</mark>, rasa<mark>giline</mark>@@  | これらはドーパミンの分解を防ぐ。                                                     | 重要なことは何もない！                                                                                                                                                                    |
| @@html:<mark>Do</mark>pamine agonists (これらの薬は副作用がひどいため、今では使われていない)@@ | @@html:Pramipex<mark>ole</mark>, ropinir<mark>ole</mark>@@ | これは脳のドーパミン受容体に影響を与える。                                           | @@html:脳の受容体に作用するため、衝動的な行動を引き起こし、ギャンブルや散財などの中毒を引き起こす。<mark>ド</mark>ーパミンは<mark>ド</mark>ルラルをたくさん使わせることを覚えておこう！@@ |

- If the patient is having symptoms which is affecting their daily life, you should give levodopa and carbidopa (use both of these!). This is the first line treatment. @@html:<span class="ja">日常生活に影響を及ぼすような症状がある場合は、レボドパとカルビドパを投与する。これは第一選択の治療法である。</span>@@
- If the patient is getting weird movements in the arms or legs, then it is probably because of levodopa! @@html:<span class="ja">もし患者が手足に奇妙な動きをするなら、それはおそらくレボドパのせいだろう！</span>@@
- If the patient is spending a lot of money, then it is probably dopamine agonists! @@html:<span class="ja">もし患者が多額のお金を費やしているのであれば、それはおそらくドーパミン作動薬だろう！</span>@@

* Epilepsy
:PROPERTIES:
:CUSTOM_ID: org70426c1
:END:

Posted: 2023-04-20 | Updated: 2023-05-09

First, let's define the word "seizure". Seizure is high-frequency activation of neurons. @@html:<span class="ja">まず、「発作」という言葉の定義を説明します。発作とは、神経細胞が高周波で活性化することです。</span>@@

There are two types of seizures:
1. Focal: this affects a single part of the brain. It /focuses/ on a single part!!! @@html:<span class="ja">これは脳の一部分に作用します。一つの部分に集中するのです！！！</span>@@
2. Generalised: this affects /all/ of the braiiiiiiiiiiiiiiiiin! Have a look at this [[https://drive.google.com/uc?export=view&id=1NvB6YoGGyj85FEzOGqbHul4mM9ls7y2W][picture]] to see the types of seizures and their classifications! @@html:<span class="ja">これは脳の全てに影響します！</span>@@

Epilepsy is having many /unprovoked/ seizures. @@html:<span class="ja">てんかんは、誘発されない発作が何度も起こることです。</span>@@

** Signs and symptoms
:PROPERTIES:
:CUSTOM_ID: orgab07f76
:END:

See this [[https://drive.google.com/uc?export=view&id=1NvB6YoGGyj85FEzOGqbHul4mM9ls7y2W][picture]].

If you want to have a look at a /tonic/ seizure, see this [[https://drive.google.com/uc?export=view&id=1aMHxSS02PY5Heja5-XtQRTNVnJaCntCa][picture]].

If you want to have a look at a /clonic/ seizure, see this [[https://drive.google.com/uc?export=view&id=1Ld8tfdzcIdSrcAhcCrLBYelKBRWampa1][picture]].

- There is a cool video of a guy putting salt frog legs. Here is the video [[https://www.youtube.com/watch?v=2YZJt_Bw3eo][link]]. Do you see how the legs keep shaking? It looks like they are having a /myoclonic seizure/. @@html:<span class="ja">カエルの足を塩漬けにするかっこいい動画があります。脚がずっと震えているのがわかりますか？まるで「ミオクロニー発作」を起こしているように見えます。</span>@@
  - This guy put /sodium/ on the legs first, and then he /leaves/ them. Keep repeating this sentence: "This guy put /sodium/ on the legs first, and then he /leaves/ them"!!

** Investigations
:PROPERTIES:
:CUSTOM_ID: org4f97aec
:END:

- Do EEG and MRI for anyone who presents with a seizure.

** Treatment
:PROPERTIES:
:CUSTOM_ID: org5c8ada3
:END:

Here is a summary. Click on this link to [[file:../cp/001.org::#epilepsy][see the story of these epilepsy drugs]]:
| Seizure type             | First line       | Second line      | Story                                                                                |
|--------------------------+------------------+------------------+--------------------------------------------------------------------------------------|
| Absence                  | Ethosuximide     | Sodium valproate | @@html:<mark>え～と</mark> and I give you <mark>salt</mark>@@                        |
| Generalised tonic-clonic | Sodium valproate | Lamotrigine      | @@html:魔神 putting <mark>salt</mark> on person and driving <mark>リムジン</mark>@@  |
| Myoclonic                | Sodium valproate | Levetiracetam    | @@html:Put <mark>salt</mark> on frog legs then <mark>leave</mark> them@@             |
| Focal                    | Lamotrigine      | Carbamazepine    | @@html:Guy focusing on driving <mark>リムジン</mark> then he hits <mark>car</mark>@@ |

- Absence seizure:
  1. Ethosuximide. @@html:<span class="ja"><mark>エト</mark>スクシミド。 わ！！！！見てください！これは「エト」です？私はこの薬を「え～と」ヒーラーと呼びたいのです。え～～と～～～～～～～～～...。誰かが「え～と」と言うたびに その人が欠神発作を起こしているのではないかと考えるようになる。そこにいるように見えて、実はいないのです。</span>@@
  2. Sodium valproate. @@html:<span class="ja">あなたは「え～と 」が好きでよく言っています。まず、エトスキシミドを投与してみます。しかし、それが失敗したら...だから、今度あなたがそれを言ったら、私はあなたに塩をあげます(言い換えれば、私はあなたにナトリウム(sodium)をあげます)。そうすれば、あなたは「え～と」を言わなくなります。ごめん笑。問題は解決しました... ククククク。</span>@@

- Generalised tonic-clonic seizure. See this [[https://drive.google.com/uc?export=view&id=11KZITEZnwseCgMCFYzeGpMX2N8EpB4FE][picture]]:
  1. Sodium valproate. @@html:Sodium is salty... so, imagine that one day there was someone having tonic-clonic seizure on the ground. Then, some genie (<mark>genie</mark> sounds like <mark>gene</mark>ralised seizure) came and put salt on that person... <span class="ja">ナトリウムは塩辛い...だから、ある日、地面で強直間代発作を起こしている人がいたとする。すると、ある<mark>魔神</mark>(これを「ま<mark>じん</mark>」、「<mark>gene</mark>ralised」という言葉とよく似ていますね。)がやってきて、その人に塩を塗った...。</span>@@
  2. Lamotrigine. @@html:<span class="ja"><mark>ラモ</mark>トリギン。ラモ... リム... お！<mark>リム</mark>ジンですね！！！そこで今度は、悪人が塩を撒いた後、<mark>リム</mark>ジンを使って現場から逃走したとする。</span>@@

- Myoclonic seizure:
  1. Sodium valproate. There is a cool video of a guy putting salt frog legs. Here is the [[https://www.youtube.com/watch?v=2YZJt_Bw3eo][link]]. Do you see how the legs keep shaking? It looks like they are having a /myoclonic seizure/. This guy put /sodium/ on the legs first, and then he /leaves/ them.
  2. @@html:<mark>Leve</mark>tiracetam. This sounds like <mark>leave</mark>@@. So, after the guy puts salt on the frog legs, he /leaves/ them to keep shaking and dancing...

- Focal seizure. See this [[https://drive.google.com/uc?export=view&id=1osIOa0XvD2tvfmBusNsyRQryFVBpHgja][picture]]:
  1. Lamotrigine. @@html:One day, there was a guy focusing (<mark>focus</mark> sounds like "<mark>focal</mark> seizure") soooooooooo much on driving a limousine. <span class="ja">ある日、<mark>リム</mark>ジンの運転に集中（「<mark>集中</mark>」は「<mark>焦点</mark>発作」のような響き）している男がいた。</span>@@
  2. Carbamazepine. @@html:<span class="ja">カルバマゼピン。カル... カー！</span> <mark>Car</mark>bamazepine sounds like a <mark>car</mark>! So, the guy who was driving the limousine accidentally hit another car on the road! <span class="ja">リムジンを運転していた人が、誤って道路で他の<mark>カー</mark>にぶつかってしまったんですね！やれやれ...。</span>@@

- Epilepsy in pregnancy:
  - These drugs can affect the development of the baby. So, we only give one drug to the pregnant woman because we want to keep the baby safe. @@html:<span class="ja">これらの薬は、赤ちゃんの発育に影響を与える可能性があります。ですから、赤ちゃんの安全を考え、妊婦さんには1種類の薬しか投与しません。</span>@@
  - If the woman is pregnant, then you should give her /only 1/ antiepileptic drug! Just 1!!!@@html:<span class="ja">妊娠している場合は、てんかん治療薬を1種類だけ投与する！ひとつだけ！！！</span>@@
  - Only choose one drug! You can choose any one of those @@html:<span class="ja">薬剤は1つだけ選んでください！どれか1つを選ぶことができます</span>@@:
    - Carbamazepine /OR/ lamotrigine
  - @@html:Because the woman is pregnant, it means that she cannot walk a lot. So we should give her a <mark>car</mark> or you can give her a <mark>リムジン</mark><span class="ja">この女性は妊娠しているので、たくさん歩くことはできないということです。ですから、彼女に車を贈るべきですし、リムジンを贈ることもできます。</span>@@

** Questions
:PROPERTIES:
:CUSTOM_ID: org068fd27
:END:

1. What is the first line treatment of myoclonic seizure?
2. What is the first line treatment of absence seizure?
3. What is the second line treatment of myoclonic seizure?
4. What is the second line treatment of generalised tonic-clonic seizure?
5. What is the second line treatment of focal seizure?
6. What is the first line treatment of generalised tonic-clonic seizure?
7. What is the first line treatment of focal seizure?
8. What is the second line treatment of absence seizure?

@@html:<div onclick="reveal()">Click this sentence to see the answers! <span class="ja">この文章をクリックすると、答えが表示されます！</span></div><div style="display: none;">@@
1. @@html:Sodium valproate. Frog legs! Remember the <mark>salt</mark> on the dancing frog legs!!!@@
2. @@html:Ethosuximide. Remember the <mark>え～と</mark>?@@
3. @@html:Levetiracetam. After the man put salt on the dancing frog legs, he <mark>leaves</mark> the kitchen!@@
4. @@html:Lamotrigine. After the genie puts salt on people, he escaped using his <mark>limousine</mark>!@@
5. @@html:Carbamazepine. The guy who was driving the limousine hit another <mark>car</mark>! <span class="ja">やれやれ...。</span>@@
6. @@html:Sodium valproate. Remember the genie that is putting <mark>salt</mark> on the people?@@
7. @@html:Lamotrigine. Remember the guy focusing on driving his <mark>limousine</mark>? He's so すごい...。@@
8. @@html:Sodium valproate. When you keep saying え～と, I give you <mark>salt</mark>!@@
@@html:</div>@@

#+BEGIN_EXPORT html
<script src="https://ahisu6.github.io/assets/js/revealAnswer.js"></script>
#+END_EXPORT
