#+TITLE: Neurology 001

#+BEGIN_EXPORT html
<div class="engt">Neurology</div>
<div class="japt">神経学</div>
<div class="engt">Page 001</div>
#+END_EXPORT

[[https://github.com/ahisu6/ahisu6.github.io/edit/main/src/n/001.org][Edit]]

[[file:./index.org][Home]]

-----

#+TOC: headlines 2

* Schizophrenia
:PROPERTIES:
:CUSTOM_ID: orgdd7f1a5
:END:

Posted: 2023-07-24 | Updated: 2023-07-24

This is a chronic disease. @@html:<span class="ja">これは慢性疾患だ。</span>@@

There is some genetics that can increase the chance of getting schizophrenia. @@html:<span class="ja">統合失調症になる可能性を高める遺伝もある。</span>@@

The symptoms are separated into positive symptoms and negative symptoms. @@html:<span class="ja">症状は陽性症状と陰性症状に分けられる。</span>@@

Positive symptoms are changes in behaviour. For example, delusions and hallucinations. @@html:<span class="ja">陽性症状とは行動の変化である。例えば、妄想や幻覚などである。</span>@@

Negative symptoms are things like feeling depressed and social isolation. Another interesting example of negative symptoms is that the patient will speak very little... this is called alogia. @@html:<span class="ja">陰性症状とは、気分が落ち込んだり、社会的に孤立したりすることです。陰性症状のもう一つの興味深い例は、患者がほとんど話さなくなることである。</span>@@

If you know the trigger that started the schizophrenia, then the patient will have a better prognosis. @@html:<span class="ja">精神分裂病が始まったきっかけが分かれば、患者の予後は良くなる。</span>@@

** Signs and symptoms
:PROPERTIES:
:CUSTOM_ID: org1b24e0a
:END:

@@html:You need to remember the first-rank symptoms of acute schizophrenia (<mark>ABCD</mark>) <span class="ja">急性統合失調症の第一級症状（<mark>ABCD</mark>）を覚えておく必要がある</span>@@:
- @@html:<mark>A</mark>uditory hallucinations@@
- @@html:<mark>B</mark>roadcasting: so, the patient will say that other people can hear their thoughts. Or, sometimes the patient might think that people are taking the thoughts from the patient's brain. <span class="ja">患者は、他人が自分の考えを聞くことができると言う。あるいは、患者が、自分の脳から思考が取り出されていると考えることもある。</span>@@
- @@html:<mark>C</mark>ontrolled feelings: the patient will say that their own actions are being controlled. <span class="ja">患者は自分の行動がコントロールされていると言うだろう。</span>@@
- @@html:<mark>D</mark>elusional perception: for example, the patient might see a blue car, and then they might think that this is a sign from the universe that it will rain today. <span class="ja">例えば、患者は青い車を見て、これは今日雨が降るという宇宙からのサインだと思うかもしれない。</span>@@

** Investigations
:PROPERTIES:
:CUSTOM_ID: org9e887fa
:END:

- This is clinical diagnosis.

** Treatment
:PROPERTIES:
:CUSTOM_ID: org556c72e
:END:

- You need to give antipsychotics. So, you can give risperidone. Then, if risperidone did not work, you might want to try something like olanzapine. @@html:<span class="ja">抗精神病薬を投与する必要があります。リスペリドンを投与すればいい。リスペリドンが効かなかったら、オランザピンなどを試してみるとよいでしょう。</span>@@
- Please note that risperidone and olanzapine are just an example. You can use any antipsychotic you want! @@html:<span class="ja">リスペリドンとオランザピンは単なる例であることに注意してください。どの抗精神病薬を使っても構いません！</span>@@
- So, what do you do if 2 antipsychotics did not treat the patient? Give clozapine! @@html:<span class="ja">では、2種類の抗精神病薬で治療できなかった場合はどうするのか？クロザピンを投与する！</span>@@
- If you have tried using 2 antipsychotics, but they have not worked, then you should give clozapine! Remember this! Very important!! @@html:<span class="ja">抗精神病薬を2種類使ってみたが効果がなかった場合は、クロザピンという薬を投与する必要がある。この情報を覚えておかなければならない！とても重要なことだ！！</span>@@

* Medications in Psychiatry
:PROPERTIES:
:CUSTOM_ID: orgdbe155d
:END:

Posted: 2023-07-24 | Updated: 2023-07-24

This will give you an overview of the drugs used in Psychiatry.

** Antipsychotics in Psychiatry
:PROPERTIES:
:CUSTOM_ID: org0753ba3
:END:

Antipsychotics block the dopamine receptors. @@html:<span class="ja">抗精神病薬はドーパミン受容体をブロックする。</span>@@

First, you need to know that there are 2 types @@html:<span class="ja">まず、2つのタイプがあることを知っておく必要がある</span>@@:
1. @@html:First generation antipsychotics: there is one main one that you need to know, and it is called "haloperidol". These drugs are usually called "typical". <span class="ja">「ハロペリドール」と呼ばれる薬だ。これらの薬は通常「典型的な」と呼ばれる。</span>@@
2. @@html:Second generation antipsychotics: aripiprazole, any drug that ends with -apine (cloz<mark>apine</mark>, olanz<mark>apine</mark>), any drug that ends with -idone (risper<mark>idone</mark>). These drugs are usually called "atypical". <span class="ja">アリピプラゾール、-apineで終わる薬（クロザピン、オランザピン）、-idoneで終わる薬（リスペリドン）。これらの薬は通常「非定型」と呼ばれる。</span>@@

Let's first talk about the first generation typical antipsychotics (for example, haloperidol) @@html:<span class="ja">まず第一世代の定型抗精神病薬（例えばハロペリドール）について説明しよう</span>@@:
- These have very bad side effects. There are more on PassMedicine, so please have a look there. @@html:<span class="ja">これらは非常に悪い副作用があります。PassMedicineにもっとたくさん掲載されていますので、そちらをご覧ください。</span>@@
- First of all, they cause increased stroke! @@html:<span class="ja">まず、脳卒中が増える！</span>@@
- Also, these drugs cause the patient's nipple to produce milk. This is called galactorrhoea. @@html:<span class="ja">また、これらの薬剤は患者の乳首に乳汁を分泌させる。これを乳汁分泌症といいます。</span>@@
- Another important side effect is weight gain! @@html:<span class="ja">もう一つの重要な副作用は体重増加である！</span>@@
- @@html:The side effects are called "extrapyramidal side effects". This means that the patient will get involuntary movements or muscle problems. You can remember these by using the word <mark>ADAPT</mark> <span class="ja">この副作用は「錐体外路性副作用」と呼ばれる。これは、患者が不随意運動や筋肉の問題を起こすことを意味する。これらはADAPTという単語で覚えられます。</span>@@:
  - @@html:<mark>A</mark>cute <mark>d</mark>ystonia@@: this a muscle spasm. In here, the muscle will be contracted for a long time. You need to treat this with a drug called /procyclidine/. @@html:<span class="ja">これは筋肉の痙攣である。この場合、筋肉は長時間収縮します。プロサイクリジンという薬で治療する必要があります。</span>@@
  - @@html:<mark>A</mark>kathisia@@: in here, the patient will feel restless. The patient wants to keep moving. @@html:<span class="ja">ここにいると、患者は落ち着かなくなる。患者は動き続けたいのだ。</span>@@
  - @@html:<mark>P</mark>arkinsonism@@: this is a word that we use to describe a group of symptoms that are similar to Parkinson's disease. @@html:<span class="ja">これは、パーキンソン病に似た症状群を表す言葉である。</span>@@
  - @@html:<mark>T</mark>ardive dyskinesia@@: this is movement issue that happen after long-term use of the drugs. Watch this [[https://www.youtube.com/watch?v=FUr8ltXh1Pc][video]]. @@html:<span class="ja">これは、薬の長期使用後に起こる筋肉の動きの問題である。</span>@@

Now, let's talk about the second generation antipsychotics (for example, clozapine and olanzapine) @@html:<span class="ja">では、第二世代の抗精神病薬（例えば、クロザピンやオランザピン）について説明しよう</span>@@:
- These have less side effects. But, they still have a high risk of stroke. @@html:<span class="ja">これらは副作用が少ない。しかし、それでも脳卒中のリスクは高い。</span>@@
- One of the drugs, clozapine, has a side effect called agranulocytosis. This is when the patient has a very low number of white cells. @@html:<span class="ja">そのひとつであるクロザピンには、無顆粒球症という副作用がある。これは患者の白血球の数が非常に少なくなることである。</span>@@

* Multiple sclerosis
:PROPERTIES:
:CUSTOM_ID: orgc78efac
:END:

Posted: 2023-07-22 | Updated: 2023-07-22

Multiple sclerosis is when the immune system accidently attacks the protective coating (myelin sheath) of nerve fibers in the brain. @@html:<span class="ja">多発性硬化症は、免疫系が脳の神経線維の保護膜（ミエリン鞘）を誤って攻撃することで発症する。</span>@@

It is more common in Caucasian women. @@html:<span class="ja">白人女性に多い。</span>@@

There are different type of multiple sclerosis. Look at this [[https://drive.google.com/uc?export=view&id=1EdiMh9yVmeZoSPWsYih-XdwrkWv6ga42][picture]] @@html:<span class="ja">多発性硬化症にはさまざまなタイプがある</span>@@:
01. Relapsing-remitting: this is the most common. The symptoms come and go. The patient will get acute attacks of multiple sclerosis, and then will have no symptoms. This will keep repeating. @@html:<span class="ja">再発寛解型：これが最も一般的だ。症状は出たり消えたりする。患者は多発性硬化症の急性発作を起こし、その後症状がなくなる。これが繰り返される。</span>@@
02. Secondary progressive disease: this comes after the "Relapsing-remitting" type. Basically, the patient will now develop permanent neurological symptoms. So, the patient will usually start with the "Relapsing-remitting" type, and will then become "Secondary progressive". @@html:<span class="ja">二次進行型：これは「再発寛解型」の後に起こる。基本的に、患者は永続的な神経症状を呈するようになる。つまり、患者は通常「再発寛解型」で始まり、その後「二次進行型」になる。</span>@@
03. Primary progressive disease: this is constant deterioration from the beginning of the disease. The patient will keep getting worse, and worse, and worse, and worse! @@html:<span class="ja">原発性進行性疾患：これは病気の初期から絶え間ない悪化である。患者はどんどん悪化していく！</span>@@

** Signs and symptoms
:PROPERTIES:
:CUSTOM_ID: org0034d4f
:END:

- The symptoms are usually general. @@html:<span class="ja">通常、症状は一般的である。</span>@@
- Tired. @@html:<span class="ja">いつも疲れている。</span>@@
- Optic neuritis: this is the inflammation of the optic nerve. The patient will be unable to see colours properly. The patient cannot see the colour red. Optic neuritis causes a lot of pain. @@html:<span class="ja">これは視神経の炎症である。患者は色を正しく見ることができなくなる。患者は赤い色を見ることができない。視神経炎は多くの痛みを引き起こします。</span>@@
- Uhthoff's phenomenon: this is an interesting one. Basically, the patient will have worse symptoms when they have a high body temperature. @@html:<span class="ja">これは興味深い。基本的に、患者は体温が高いと症状が悪化する。</span>@@
- Pins and needles.
- Numb.
- Leg weakness.

** Investigations
:PROPERTIES:
:CUSTOM_ID: org737d56e
:END:

- You need to find the lesions in the brain. @@html:<span class="ja">脳の病変を見つける必要がある。</span>@@
- To do that, you need to do MRI scan of the brain and spinal cord. @@html:<span class="ja">そのためには、脳と脊髄のMRIスキャンが必要です。</span>@@
- When you do MRI scan, you will find something called high signal T2 lesions. Look at this [[https://drive.google.com/uc?export=view&id=1Jj3qXf5O8MyMXKVumcfSo6wqfb6sUMqn][picture]]. @@html:<span class="ja">MRI検査をすると、高信号T2病変と呼ばれるものが見つかります。</span>@@
- On the MRI, the patient might also have something called Dawson fingers. Look at this [[https://drive.google.com/uc?export=view&id=1aVIaOgylg1tsDxFEhbGtLl6rMW3nB37T][picture]]. They look like fingers... @@html:<span class="ja">MRI上では、ドーソンフィンガーと呼ばれるものも認められる。これは指のように見えますね？</span>@@
- If you do a lumbar puncture, you will see things called "oligoclonal bands". These are weird proteins (immunoglobulins). @@html:<span class="ja">腰椎穿刺をすると、「オリゴクローナル・バンド」と呼ばれるものが見えます。これは奇妙なタンパク質（免疫グロブリン）です。</span>@@

** Treatment
:PROPERTIES:
:CUSTOM_ID: orgcca981e
:END:

- If the patient is having an acute attack, then you should give them high dose of steroid for 5 days. This is used for acute management. @@html:<span class="ja">もし患者が急性発作を起こしているのであれば、ステロイドを5日間大量に投与する必要がある。これは急性期の治療に使われます。</span>@@
- To reduce the number of future attacks, you can use a drug called interferon-beta. This is used for long-term management. @@html:<span class="ja">将来の発作の回数を減らすために、インターフェロン-βという薬を使うことができます。これは長期的な管理に用いられます。</span>@@
- @@html:If the patient feels tired, then you can give them amantadine. One day, there was <mark>a man</mark> who always felt tired... so, we gave him <mark>aman</mark>tadine. <span class="ja">患者が疲れを感じているなら、アマンタジンを投与すればいい。</span>@@
- If the patient has spasm, then give them baclofen or gabapentin. @@html:<span class="ja">筋痙攣があれば、バクロフェンかガバペンチンを投与する。</span>@@

Here is a table:
| Type of treatment | Drug                           |
|-------------------+--------------------------------|
| Acute attack      | Steroid                        |
| Long-term         | Interferon-beta                |
| Tired             | Amantadine                     |
| Spasm             | Baclofen or gabapentin         |

* Parkinson disease
:PROPERTIES:
:CUSTOM_ID: org87512dc
:END:

Posted: 2023-06-22 | Updated: 2023-06-22

This is a disease which causes a problem in a part of the brain called substantia nigra. This causes less dopamine to be released. @@html:<span class="ja">これは、脳の黒質と呼ばれる部分に問題が生じる病気である。そのため、ドーパミンの放出が少なくなる。</span>@@

Sometimes, during treatment, the patient might still get some symptoms. This is called "on-off" effect. @@html:<span class="ja">治療中、患者に何らかの症状が残ることがある。これは「on-off」効果と呼ばれる。</span>@@

** Signs and symptoms
:PROPERTIES:
:CUSTOM_ID: orgb838b6a
:END:

@@html:The symptoms are easy to remember. Parkinson <mark>TRAPS</mark> the body@@:
1. @@html:<mark>T</mark>remor: this tremor happens when the patient is resting.  <span class="ja">この振戦は患者が安静にしているときに起こる。</span>@@
2. @@html:<mark>R</mark>@@igidity.
3. @@html:<mark>A</mark>kinesia: this means that the body is slow at moving. <span class="ja">つまり、体の動きが鈍いということだ</span>@@
4. @@html:<mark>P</mark>ostural instability: this means that the patient might be wobbly. <span class="ja">これは、患者がふらつく可能性があることを意味する。</span>@@
5. @@html:<mark>S</mark>@@huffling gait: watch this [[https://www.youtube.com/watch?v=yhj1PktNA1c][video]]!

** Investigations
:PROPERTIES:
:CUSTOM_ID: orga95ae0a
:END:

- This is a clinical diagnosis. So, you have to look at the symptoms of the patient. @@html:<span class="ja">これは臨床診断です。ですから、患者の症状を見なければなりません。</span>@@
- You can also do CT scan if you are not sure. @@html:<span class="ja">確信が持てない場合は、CTスキャンをすることもできます。</span>@@

** Treatment
:PROPERTIES:
:CUSTOM_ID: orgd06d41c
:END:

Because the patient does not have a lot of dopamine, we need to give them drugs that increase the dopamine level. There are many drugs that can do this. @@html:<span class="ja">患者にはドーパミンがあまりないので、ドーパミンを増やす薬を投与する必要がある。これを可能にする薬はたくさんある。</span>@@

Here are the main types (there are more on PassMedicine):
| Drug group                                                                           | Examples                                                   | How does it improve Parkinson                                                             | Side effects                                                                                                                                                                                                                                   |
|--------------------------------------------------------------------------------------+------------------------------------------------------------+-------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| DOPA drugs                                                                           | @@html:Levo<mark>dopa</mark>/carbi<mark>dopa</mark>@@      | These cause more dopamine to be in the body.                                              | "On-off" effect. If the patient gets these effects, then you should give them drugs that prevent the breakdown of dopamine. They can also cause involuntary movements!                                                                         |
| @@html:<mark>C</mark>OMT inhibitors@@                                                | @@html:Enta<mark>capone</mark>, tol<mark>capone</mark>@@   | These prevent dopamine breakdown. Give these to the patient if they have "on-off" effect. | Nothing important!                                                                                                                                                                                                                             |
| MAO-B                                                                                | @@html:Sele<mark>giline</mark>, rasa<mark>giline</mark>@@  | These prevent dopamine breakdown.                                                         | Nothing important!                                                                                                                                                                                                                             |
| @@html:<mark>Do</mark>pamine agonists (not used anymore because of bad side effects)@@ | @@html:Pramipex<mark>ole</mark>, ropinir<mark>ole</mark>@@ | This affect the dopamine receptors in the brain.                                          | @@html:Because they affect the receptors at the brain, they will cause impulsive behaviour and addiction to things like gambling and spending a lot of money. Remember, <mark>do</mark>pamine makes you spend a lot of <mark>do</mark>llars!@@ |

Here is a Japanese table:
| 薬剤群                                                                                | 例えば                                                     | パーキンソン病はどのように改善されるのですか？                                       | 薬の副作用                                                                                                                                                                                |
|----------------------------------------------------------------------------------------+------------------------------------------------------------+--------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| DOPA drugs                                                                             | @@html:Levo<mark>dopa</mark>/carbi<mark>dopa</mark>@@      | これらは、体内のドーパミンを増加させる。                                             | 「On-off」効果。もし患者にこのような作用が現れたら、ドーパミンの分解を防ぐ薬を与えるべきです。また、不随意運動を引き起こすこともある！                                                    |
| @@html:<mark>C</mark>OMT inhibitors@@                                                                        | @@html:Enta<mark>capone</mark>, tol<mark>capone</mark>@@   | これらはドーパミンの分解を防ぐ。「on-off」の効果がある場合は、患者にこれらを与える。 | 重要なことは何もない！                                                                                                                                                                    |
| MAO-B                                                                                  | @@html:Sele<mark>giline</mark>, rasa<mark>giline</mark>@@  | これらはドーパミンの分解を防ぐ。                                                     | 重要なことは何もない！                                                                                                                                                                    |
| @@html:<mark>Do</mark>pamine agonists (これらの薬は副作用がひどいため、今では使われていない)@@ | @@html:Pramipex<mark>ole</mark>, ropinir<mark>ole</mark>@@ | これは脳のドーパミン受容体に影響を与える。                                           | @@html:脳の受容体に作用するため、衝動的な行動を引き起こし、ギャンブルや散財などの中毒を引き起こす。<mark>ド</mark>ーパミンは<mark>ド</mark>ルラルをたくさん使わせることを覚えておこう！@@ |

- If the patient is having symptoms which is affecting their daily life, you should give levodopa and carbidopa (use both of these!). This is the first line treatment. @@html:<span class="ja">日常生活に影響を及ぼすような症状がある場合は、レボドパとカルビドパを投与する。これは第一選択の治療法である。</span>@@
- If the patient is getting weird movements in the arms or legs, then it is probably because of levodopa! @@html:<span class="ja">もし患者が手足に奇妙な動きをするなら、それはおそらくレボドパのせいだろう！</span>@@
- If the patient is spending a lot of money, then it is probably dopamine agonists! @@html:<span class="ja">もし患者が多額のお金を費やしているのであれば、それはおそらくドーパミン作動薬だろう！</span>@@

* Epilepsy
:PROPERTIES:
:CUSTOM_ID: org70426c1
:END:

Posted: 2023-04-20 | Updated: 2023-05-09

First, let's define the word "seizure". Seizure is high-frequency activation of neurons. @@html:<span class="ja">まず、「発作」という言葉の定義を説明します。発作とは、神経細胞が高周波で活性化することです。</span>@@

There are two types of seizures:
1. Focal: this affects a single part of the brain. It /focuses/ on a single part!!! @@html:<span class="ja">これは脳の一部分に作用します。一つの部分に集中するのです！！！</span>@@
2. Generalised: this affects /all/ of the braiiiiiiiiiiiiiiiiin! Have a look at this [[https://drive.google.com/uc?export=view&id=1NvB6YoGGyj85FEzOGqbHul4mM9ls7y2W][picture]] to see the types of seizures and their classifications! @@html:<span class="ja">これは脳の全てに影響します！</span>@@

Epilepsy is having many /unprovoked/ seizures. @@html:<span class="ja">てんかんは、誘発されない発作が何度も起こることです。</span>@@

** Signs and symptoms
:PROPERTIES:
:CUSTOM_ID: orgab07f76
:END:

See this [[https://drive.google.com/uc?export=view&id=1NvB6YoGGyj85FEzOGqbHul4mM9ls7y2W][picture]].

If you want to have a look at a /tonic/ seizure, see this [[https://drive.google.com/uc?export=view&id=1aMHxSS02PY5Heja5-XtQRTNVnJaCntCa][picture]].

If you want to have a look at a /clonic/ seizure, see this [[https://drive.google.com/uc?export=view&id=1Ld8tfdzcIdSrcAhcCrLBYelKBRWampa1][picture]].

- There is a cool video of a guy putting salt frog legs. Here is the video [[https://www.youtube.com/watch?v=2YZJt_Bw3eo][link]]. Do you see how the legs keep shaking? It looks like they are having a /myoclonic seizure/. @@html:<span class="ja">カエルの足を塩漬けにするかっこいい動画があります。脚がずっと震えているのがわかりますか？まるで「ミオクロニー発作」を起こしているように見えます。</span>@@
  - This guy put /sodium/ on the legs first, and then he /leaves/ them. Keep repeating this sentence: "This guy put /sodium/ on the legs first, and then he /leaves/ them"!!

** Investigations
:PROPERTIES:
:CUSTOM_ID: org4f97aec
:END:

- Do EEG and MRI for anyone who presents with a seizure.

** Treatment
:PROPERTIES:
:CUSTOM_ID: org5c8ada3
:END:

Here is a summary. Click on this link to [[file:../cp/001.org::#epilepsy][see the story of these epilepsy drugs]]:
| Seizure type             | First line       | Second line      | Story                                                                                |
|--------------------------+------------------+------------------+--------------------------------------------------------------------------------------|
| Absence                  | Ethosuximide     | Sodium valproate | @@html:<mark>え～と</mark> and I give you <mark>salt</mark>@@                        |
| Generalised tonic-clonic | Sodium valproate | Lamotrigine      | @@html:魔神 putting <mark>salt</mark> on person and driving <mark>リムジン</mark>@@  |
| Myoclonic                | Sodium valproate | Levetiracetam    | @@html:Put <mark>salt</mark> on frog legs then <mark>leave</mark> them@@             |
| Focal                    | Lamotrigine      | Carbamazepine    | @@html:Guy focusing on driving <mark>リムジン</mark> then he hits <mark>car</mark>@@ |

- Absence seizure:
  1. Ethosuximide. @@html:<span class="ja"><mark>エト</mark>スクシミド。 わ！！！！見てください！これは「エト」です？私はこの薬を「え～と」ヒーラーと呼びたいのです。え～～と～～～～～～～～～...。誰かが「え～と」と言うたびに その人が欠神発作を起こしているのではないかと考えるようになる。そこにいるように見えて、実はいないのです。</span>@@
  2. Sodium valproate. @@html:<span class="ja">あなたは「え～と 」が好きでよく言っています。まず、エトスキシミドを投与してみます。しかし、それが失敗したら...だから、今度あなたがそれを言ったら、私はあなたに塩をあげます(言い換えれば、私はあなたにナトリウム(sodium)をあげます)。そうすれば、あなたは「え～と」を言わなくなります。ごめん笑。問題は解決しました... ククククク。</span>@@

- Generalised tonic-clonic seizure. See this [[https://drive.google.com/uc?export=view&id=11KZITEZnwseCgMCFYzeGpMX2N8EpB4FE][picture]]:
  1. Sodium valproate. @@html:Sodium is salty... so, imagine that one day there was someone having tonic-clonic seizure on the ground. Then, some genie (<mark>genie</mark> sounds like <mark>gene</mark>ralised seizure) came and put salt on that person... <span class="ja">ナトリウムは塩辛い...だから、ある日、地面で強直間代発作を起こしている人がいたとする。すると、ある<mark>魔神</mark>(これを「ま<mark>じん</mark>」、「<mark>gene</mark>ralised」という言葉とよく似ていますね。)がやってきて、その人に塩を塗った...。</span>@@
  2. Lamotrigine. @@html:<span class="ja"><mark>ラモ</mark>トリギン。ラモ... リム... お！<mark>リム</mark>ジンですね！！！そこで今度は、悪人が塩を撒いた後、<mark>リム</mark>ジンを使って現場から逃走したとする。</span>@@

- Myoclonic seizure:
  1. Sodium valproate. There is a cool video of a guy putting salt frog legs. Here is the [[https://www.youtube.com/watch?v=2YZJt_Bw3eo][link]]. Do you see how the legs keep shaking? It looks like they are having a /myoclonic seizure/. This guy put /sodium/ on the legs first, and then he /leaves/ them.
  2. @@html:<mark>Leve</mark>tiracetam. This sounds like <mark>leave</mark>@@. So, after the guy puts salt on the frog legs, he /leaves/ them to keep shaking and dancing...

- Focal seizure. See this [[https://drive.google.com/uc?export=view&id=1osIOa0XvD2tvfmBusNsyRQryFVBpHgja][picture]]:
  1. Lamotrigine. @@html:One day, there was a guy focusing (<mark>focus</mark> sounds like "<mark>focal</mark> seizure") soooooooooo much on driving a limousine. <span class="ja">ある日、<mark>リム</mark>ジンの運転に集中（「<mark>集中</mark>」は「<mark>焦点</mark>発作」のような響き）している男がいた。</span>@@
  2. Carbamazepine. @@html:<span class="ja">カルバマゼピン。カル... カー！</span> <mark>Car</mark>bamazepine sounds like a <mark>car</mark>! So, the guy who was driving the limousine accidentally hit another car on the road! <span class="ja">リムジンを運転していた人が、誤って道路で他の<mark>カー</mark>にぶつかってしまったんですね！やれやれ...。</span>@@

- Epilepsy in pregnancy:
  - These drugs can affect the development of the baby. So, we only give one drug to the pregnant woman because we want to keep the baby safe. @@html:<span class="ja">これらの薬は、赤ちゃんの発育に影響を与える可能性があります。ですから、赤ちゃんの安全を考え、妊婦さんには1種類の薬しか投与しません。</span>@@
  - If the woman is pregnant, then you should give her /only 1/ antiepileptic drug! Just 1!!!@@html:<span class="ja">妊娠している場合は、てんかん治療薬を1種類だけ投与する！ひとつだけ！！！</span>@@
  - Only choose one drug! You can choose any one of those @@html:<span class="ja">薬剤は1つだけ選んでください！どれか1つを選ぶことができます</span>@@:
    - Carbamazepine /OR/ lamotrigine
  - @@html:Because the woman is pregnant, it means that she cannot walk a lot. So we should give her a <mark>car</mark> or you can give her a <mark>リムジン</mark><span class="ja">この女性は妊娠しているので、たくさん歩くことはできないということです。ですから、彼女に車を贈るべきですし、リムジンを贈ることもできます。</span>@@

** Questions
:PROPERTIES:
:CUSTOM_ID: org068fd27
:END:

1. What is the first line treatment of myoclonic seizure?
2. What is the first line treatment of absence seizure?
3. What is the second line treatment of myoclonic seizure?
4. What is the second line treatment of generalised tonic-clonic seizure?
5. What is the second line treatment of focal seizure?
6. What is the first line treatment of generalised tonic-clonic seizure?
7. What is the first line treatment of focal seizure?
8. What is the second line treatment of absence seizure?

@@html:<div onclick="reveal()">Click this sentence to see the answers! <span class="ja">この文章をクリックすると、答えが表示されます！</span></div><div style="display: none;">@@
1. @@html:Sodium valproate. Frog legs! Remember the <mark>salt</mark> on the dancing frog legs!!!@@
2. @@html:Ethosuximide. Remember the <mark>え～と</mark>?@@
3. @@html:Levetiracetam. After the man put salt on the dancing frog legs, he <mark>leaves</mark> the kitchen!@@
4. @@html:Lamotrigine. After the genie puts salt on people, he escaped using his <mark>limousine</mark>!@@
5. @@html:Carbamazepine. The guy who was driving the limousine hit another <mark>car</mark>! <span class="ja">やれやれ...。</span>@@
6. @@html:Sodium valproate. Remember the genie that is putting <mark>salt</mark> on the people?@@
7. @@html:Lamotrigine. Remember the guy focusing on driving his <mark>limousine</mark>? He's so すごい...。@@
8. @@html:Sodium valproate. When you keep saying え～と, I give you <mark>salt</mark>!@@
@@html:</div>@@

#+BEGIN_EXPORT html
<script src="https://ahisu6.github.io/assets/js/revealAnswer.js"></script>
#+END_EXPORT
