#+TITLE: Neurology 002

#+BEGIN_EXPORT html
<div class="engt">Neurology</div>
<div class="japt">神経学</div>
<div class="engt">Page 002</div>
#+END_EXPORT

[[https://github.com/ahisu6/ahisu6.github.io/edit/main/src/n/002.org][Edit]]

[[file:./index.org][Home]]

[[file:./001.org][<< Previous page]] - [[file:./003.org][Next page >>]]

-----

#+TOC: headlines 2

* Attention Deficit Hyperactivity Disorder
:PROPERTIES:
:CUSTOM_ID: org88d56f8
:END:

Posted: 2023-09-30 | Updated: 2023-09-30

Attention Deficit Hyperactivity Disorder (ADHD) is a disease that causes the person to have reduced attention and increased activity. @@html:<span class="ja">注意欠陥多動性障害（ADHD）は、注意力が低下し、活動性が亢進する病気である。</span>@@

It is more common in boys. @@html:<span class="ja">男子に多い。</span>@@

The symptoms for ADHD have to happen in 2 different places. So, the patient must have the same symptoms at the park and at home. @@html:<span class="ja">ADHDの症状は、2つの異なる場所で起こらなければならない。だから、患者は公園でも家でも同じ症状でなければならない。</span>@@

** Signs and symptoms
:PROPERTIES:
:CUSTOM_ID: org55da0d7
:END:

There are 3 main symptoms for ADHD @@html:<span class="ja">ADHDには3つの主な症状がある</span>@@:
1. Inattention: this means that the patient cannot pay a lot of attention. @@html:<span class="ja">不注意：これは、患者が多くの注意を払うことができないことを意味する。</span>@@
2. Hyperactivity: high level of energy. The patient will be very active. For example, the patient will play a lot and talk a lot. @@html:<span class="ja">多動：エネルギーが旺盛。患者は非常に活動的である。例えば、よく遊び、よく話す。</span>@@
3. Impulsivity: the patient will interrupt other people. @@html:<span class="ja">衝動性：他人の邪魔をする。</span>@@

** Investigations
:PROPERTIES:
:CUSTOM_ID: orgb7b97d2
:END:

- This is a clinical diagnosis. So, no tests are needed. @@html:<span class="ja">これは臨床診断である。だから検査は必要ない。</span>@@

** Treatment
:PROPERTIES:
:CUSTOM_ID: org2821b11
:END:

- First, you need to observe the child for at least 10 weeks. @@html:<span class="ja">まず、少なくとも10週間は子どもを観察する必要がある。</span>@@
- If the patient still has the symptoms for more than 10 weeks, then you need to refer to the hospital or to Child and Adolescent Mental Health Service (CAMHS). The child will be seen by a specialist. @@html:<span class="ja">それでも10週間以上症状が続く場合は、病院か児童青年精神保健サービス（CAMHS）に紹介する必要があります。専門医が診察します。</span>@@
- Drugs are last resort. If you want to use drugs, then the patient has to be more than 5 years old. @@html:<span class="ja">薬は最後の手段だ。もし薬を使いたいなら、患者は5歳以上でなければならない。</span>@@
- The first-line drug is methylphenidate. @@html:<span class="ja">第一選択薬はメチルフェニデートである。</span>@@
  - @@html:Look at the word 「メ<mark>チル</mark>フェニデート」...@@
  - @@html:<mark>チル</mark> means "chill/cold".@@
  - @@html:ADHD children play a lot, and they become very hot. So, we have to give them メ<mark>チル</mark>フェニデート to make them colder. <span class="ja">ADHDの子どもたちはよく遊び、とても暑くなります。だから、メ<mark>チル</mark>フェニデートを与えて寒がりにさせなければならない。</span>@@
  - When you give methylphenidate, you have to monitor the height, weight, and the blood pressure of the child every 6 months. @@html:<span class="ja">メチルフェニデートを投与する場合は、6ヵ月ごとに子どもの身長、体重、血圧をモニターしなければならない。</span>@@
- If methylphenidate did not work, then you need to switch to lisdexamfetamine. @@html:<span class="ja">メチルフェニデートが効かなかったのなら、リスデキサムフェタミンに切り替える必要がある。</span>@@

** Complications
:PROPERTIES:
:CUSTOM_ID: orgc196c6d
:END:

- The ADHD drugs are very toxic to the heart. So, we have to do ECG. @@html:<span class="ja">ADHDの薬は心臓にとても毒性がある。だから心電図をとらなければならない。</span>@@

** Questions
:PROPERTIES:
:CUSTOM_ID: org9be37ba
:END:

1. ADHD is more common is boys or girls?
2. What is a requirement for the symptoms of ADHD?
3. What are the 3 main symptoms for ADHD?
4. What does "impulsivity" mean in ADHD?
5. What is the first-line treatment for ADHD?
6. What is the first-line drug treatment for ADHD?
7. What should you monitor when you give the drug to ADHD patient?
8. How often should the child be monitored when taking ADHD drugs?

@@html:<div onclick="reveal()">Click this sentence to see the answers! <span class="ja">この文章をクリックすると、答えが表示されます！</span></div><div style="display: none;">@@
1. Boys.
2. The symptoms for ADHD have to occur in 2 different places.
3. The 3 main symptoms for ADHD are: inattention, hyperactivity, impulsivity.
4. The patient will interrupt other people.
5. 10 weeks of observation.
6. Methylphenidate.
7. You should monitor: height, weight, and the blood pressure.
8. Every 6 months.
@@html:</div>@@

* Psychosis vs. Schizophrenia
:PROPERTIES:
:CUSTOM_ID: orgdf0793e
:END:

Posted: 2023-09-29 | Updated: 2023-09-29

You asked me about the difference between psychosis and Schizophrenia. @@html:<span class="ja">精神病と統合失調症の違いについて尋ねられましたね。</span>@@

Psychosis is the distorted perception of reality which which includes things like delusions, speech issues, thought issues, and hallucinations. @@html:<span class="ja">精神病とは、妄想、発話の問題、思考の問題、幻覚などを含む現実の歪んだ認識のことである。</span>@@

People who have a mental illness might get psychosis. Some drugs cause psychosis. @@html:<span class="ja">精神疾患を持つ人は精神病になるかもしれない。精神病を引き起こす薬もあります。</span>@@

Schizophrenia is a disease. Schizophrenia has many symptoms. One of the symptoms in Schizophrenia is psychosis. Please read this explanation of Schizophrenia [[file:./001.org::#orgdd7f1a5][here]]! @@html:<span class="ja">統合失調症は病気である。統合失調症には多くの症状がある。統合失調症の症状のひとつに精神病がある。</span>@@

Think of psychosis like a symptom @@html:<span class="ja">精神病は症状のようなものだと考えてください</span>@@:
- Psychosis = symptom
- Schizophrenia = disease

* Encephalitis
:PROPERTIES:
:CUSTOM_ID: org99809f1
:END:

Posted: 2023-07-31 | Updated: 2023-07-31

Encephalitis is inflammation of the brain. @@html:<span class="ja">脳炎は脳の炎症である。</span>@@

Encephalitis can happen because of many reasons. The most common reason is viral or bacterial infections. @@html:<span class="ja">脳炎はさまざまな原因で起こる。最も一般的な理由は、ウイルスや細菌の感染です。</span>@@

The herpes simplex virus is the most common cause of encephalitis. Herpes simplex virus mainly affect the temporal lobe of the brain. See this [[https://drive.google.com/uc?export=view&id=1-jvvL_HfEO6jYZGxOBK6Jao6vd_ZXdCJ][picture]] of temporal lobe encephalitis (I got it from this [[https://radiopaedia.org/cases/10644/][website]]). @@html:<span class="ja">単純ヘルペスウイルスは脳炎の最も一般的な原因である。単純ヘルペスウイルスは主に脳の側頭葉を侵す。</span>@@

When the brain becomes inflamed, many problems can happen. For example, confusion and seizures. @@html:<span class="ja">脳が炎症を起こすと、さまざまな問題が起こる。例えば、錯乱や発作などだ。</span>@@

** Signs and symptoms
:PROPERTIES:
:CUSTOM_ID: org698963b
:END:

- Fever.
- Confusion.
- Seizures.
- The patient might start behaving in a strange way and their personality might change. @@html:<span class="ja">患者は奇妙な行動をとるようになり、性格が変わるかもしれない。</span>@@

** Investigations
:PROPERTIES:
:CUSTOM_ID: orgdf7dabe
:END:

- You need to check the cerebrospinal fluid (CSF). And, you need to do PCR to see if there are any viruses. @@html:<span class="ja">脳脊髄液（CSF）をチェックする必要があります。そして、ウイルスがあるかどうかを確認するためにPCRを行う必要がある。</span>@@
- Do MRI to see the place of inflammation. If the patient has herpes simplex encephalitis, then you will notice that the temporal lobes are inflamed. See this [[https://drive.google.com/uc?export=view&id=1-jvvL_HfEO6jYZGxOBK6Jao6vd_ZXdCJ][picture]] of temporal lobe encephalitis (I got it from this [[https://radiopaedia.org/cases/10644/][website]]). @@html:<span class="ja">MRIで炎症の場所を見る。患者が単純ヘルペス脳炎であれば、側頭葉が炎症を起こしていることがわかります。</span>@@

** Treatment
:PROPERTIES:
:CUSTOM_ID: org0383cf2
:END:

- If the patient has herpes simplex encephalitis, then you need to give them... IV aciclovir! @@html:<span class="ja">もし患者が単純ヘルペス脳炎に罹患しているのであれば... アシクロビルの静脈内投与！</span>@@

#+BEGIN_EXPORT html
<script src="https://ahisu6.github.io/assets/js/revealAnswer.js"></script>
#+END_EXPORT
